### ISSUE TITLE
URI malformed when notebook contains %

### ISSUE THREAD

**Issue by devgrok** [jupyter/help#108]
If I have a notebook with a % anywhere in the code lines then I get the following error when I try to save:
> utils.js:623 API request failed (0): URIError: URI malformed

Notebook containing a single cell with contents:
`%matplotlib inline`

Versions:
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Chrome  54.0.2840.99 m (64-bit)
Windows 7 64-bit

**Comment by devgrok** [comment]
I had discovered that it was the % culprit after seeing this angular bug which may assist in fixing the bug in the front-end:
https://github.com/angular/angular.js/issues/13165

**Comment by takluyver** [comment]
You have the Lastpass extension installed in Chrome, right? There seems to be a bug specifically in the Lastpass Chrome extension (it works fine with Lastpass+Firefox). See jupyter/notebook#1966.

**Comment by devgrok** [comment]
Yep cheers this is a duplicate of that bug.
I had searched the wrong repo for the issue.
