### ISSUE TITLE
After conda update I now have two kernals

### ISSUE THREAD

**Issue by pvrsykes** [jupyter/help#112]
version: Windows 10, Python_anaconda\Jupyter_nb: py35
I am a beginner programmer!
After running the "conda update" command I now have two kernels.
When I open jupyter notebook using the anaconda prompt,
Python [conda root] and  Python [default] are the choices.

Questions:
1. Which kernel should I use and which one should I delete?
2. Can I delete one of the kernels?
3. How do I delete a kernel?
4. Why did two kernels show up after the update?

Thank you for any help on my questions.

**Comment by takluyver** [comment]
Short answer: use 'Python [default]' and don't worry about the fact that there are two of them.

Conda does something to expose conda environments as kernels. If you haven't created any conda environments, then 'conda root' and 'default' will do the same thing. If you create additional environments with ipykernel installed, they will show up on the list. The 'default' option runs the kernel in the same environment that Jupyter is running in.

Conda does not provide a way to delete these, other than by removing the conda kernels extension.

**Comment by pvrsykes** [comment]
Thank you for the concise answer, I will continue as you suggest.
