### ISSUE TITLE
How can I change notebook saving behavior on a per-object/cell basis?

### ISSUE THREAD

**Issue by eteq** [jupyter/help#12]
Is there a way to  change what gets saved in a jupyter notebook for a specific python object? I'm thinking of something akin to `_repr_html_`, but that operates only when the notebook is saved (i.e., it could produce the relevant html content for the cell to be saved as).

I found the on-save hook functions in jupyter, but what I really want is something that would operate on a python class/object level, rather than having to have a single global hook for a notebook - we want to be able to distribute this functionality with another package, and I imagine it's not very good practice to override a global function like that?

**Comment by Carreau** [comment]
I'm not sure I completely understand what you want, with a real example, that might be easier to respond. 
But as far as I can tell, if I understand correctly, no, there is no way to trigger that on save.

In particular, since what you ask is Python specific, it look hard to achieve as the notebook is pure Json.

But with a practical use case of what you are trying to achieve,  we might be able to find a work around.

**Comment by eteq** [comment]
Good point that a more concrete example would help, @Carreau.  The *real* use case is too complex for this format, but let me try to distill the essence of it.  I've already made an object  do something like this:
```
class HTMLGUIServer:
    def __init__(self, ...):
        ... sets  up an HTML server that interacts with other processes on the system and yields mainly an image but also a few other things...
        self.server_url= url_to_the_server_created_above

    def screenshot(self):
        """
        Returns a screenshot of the important content contained in this server's current view
        """
        ...
        return imagedata

    def _repr_html_(self):
        return IPython.display.IFrame(self.server_url)
```
That correctly displays an HTML "GUI" in the notebook as an ``IFrame``, which I can interact with to do various science visualization tools. But if I later on open up the notebook, I just get an empty IFrame/broken link symbol, because the server is no longer running.

So what I would like to be able to do is something like this:
```
def __on_nb_save_(self):
    return IPython.core.display.Image(data=self.screenshot())
```
and then the *saved* version of the notebook would have the screenshot instead of the IFrame.  I realize that might be a specific use case, so I could also settle for:
```
def _on_nb_save_(self, nb, cell):
    screenshot=self.screenshot()
    ... do something with the nb or cell object to manually inject the image data ...
```

Does that make more sense?

(Also, I realize this simplified version could be implemented as proper Jupyter/IPython interactive widgets, but there are various reasons why that's not true in the real use case, so lets not worry about that for now...)

**Comment by takluyver** [comment]
The kernel is not involved when saving a notebook at all, and I suspect it would add all sorts of extra complexity if it was.

You may be able to hack something like that together with some displayed Javascript that detects a save event and rewrites the output, but it's probably going to be as brittle as it sounds.

We do need to work out something for how interactive elements gracefully degrade when the kernel they're talking to is not running (this goes for widgets too), but IMO that should involve HTML output that can cope with that situation, not asking the kernel about each output before saving.

**Comment by Carreau** [comment]
@jdfreder that's what the widgets are currently doing, and might be a use case of companion file.
You might be better suited to respond to that.

**Comment by eteq** [comment]
@takluyver - Hmm, my reading of this: http://jupyter-notebook.readthedocs.org/en/latest/extending/savehooks.html  is that there's at least some way to "opt in" to the kernel getting a call on-save, right?  I could write my own machinery to hack into that and override, but that seems potentially just as brittle as your first suggestion here (although it has the advantage of living entirely in kernel-land and not mixed kernel/JS-land).  My question here is if there's a way to use that machinery on a more fine-grained basis. I gather the answer is "no" right now, but it does seem like it would be possible to modify that hook to do something more like what I am thinking?

**Comment by takluyver** [comment]
Save hooks are run in the notebook server, not in the kernel. You could,  I suppose, write a save hook that makes a request to the kernel and waits for a response, but (a) please don't ;-) and (b) it would still need some way to match up the output data stored in the notebook with the objects the kernel knows about.

**Comment by jdfreder** [comment]
@Carreau are you talking about the save with widget images feature?  That's done entirely in Javascript with no involvement of the kernel.

**Comment by Carreau** [comment]
Yes, but that's seem what @eteq wants to achieve : a saved version that  has an "image" of what is at some point in the IFrame.

**Comment by jdfreder** [comment]
Oh yeah, it's a bit annoying to implement at the moment because we don't have proper asynchronous save hooks in the Javascript.  That's why the widgets implements it's own save function-

Asynchronously rasterize widgets to display data
When done, invoke standard notebook save function

Because of this, ctrl-s doesn't save with the rasterized images.  In order to allow that, we need to add an asynchronous save hook to the notebook frontend.

**Comment by Carreau** [comment]
Well I guess that @eteq would not mind even if it men (for now) press an extra button before saving, like a "freeze" button.

**Comment by eteq** [comment]
@Carreau - hmm, that's not ideal, because this application is often used for "quick look" sort of use cases, and "quick look" often means "in a hurry and therefore likely to forget to hit the save button".  But definitely that's still an improvement if that can be made to work!

**Comment by eteq** [comment]
And thanks for clearing that up about the server vs. kernel distinction, @takluyver - that clears things up and prevented me from going down that hole only to find it would be fundamentally flawed ;)

So does it seem

**Comment by jdfreder** [comment]
@eteq I think an asynchronous save hood is a good idea

**Comment by willingc** [comment]
It looks like from @eteq's latest message that @eteq's questions have been answered. Thanks @eteq and all who responded for a good exchange of knowledge :sunny:

I'm closing this support issue as triaged. I have added it to the "Reference" milestone in hopes that this discussion may assist others in the future. Please feel free to reopen this issue if needed. Thanks!

**Comment by eteq** [comment]
@willingc - just so we're clear, my question was *not* exactly answered: my last message actually was saying that my best-guess solution will *not* work. 

That said, it sounds like the best solution was judged to be "wait for the  async save hook to be implemented". So it might still be fair to triage it.

One question for @jdfreder - can you point me to *where* the widgets do their magic right to implement this right now just so I have something to go on if need be?

**Comment by jdfreder** [comment]
Sure, https://github.com/ipython/ipywidgets/blob/master/widgetsnbextension/src/manager.js#L377-L406

Instead, if you have a synchronous pre-save action you can use https://github.com/ipython/ipywidgets/blob/master/widgetsnbextension/src/manager.js#L87-L100 !synchronous only

**Comment by willingc** [comment]
Hi @eteq, I agree "answered" was a poor choice of wording on my part. Sorry about that :disappointed: I'm happy to reopen the issue if you would like me to do so.

**Comment by eteq** [comment]
With the last comment by @jdfreder above I actually think *is* now answered, so we are good!

@jdfreder - should I open an issue somewhere about an async save option?  Am I right that this belongs in jupyte/notebook, not jupyter/jupyter?
