### ISSUE TITLE
How to install packages 

### ISSUE THREAD

**Issue by ugmurthy** [jupyter/help#121]
I am using a pre-build Docker container to run Jupyter as part of  UDACITY's deeplearning course.

I need the h5py to load some .mat (MatLab) files. 
used the following code to do so:

`import numpy as np`
`import h5py `
`f = h5py.File('train/digitStruct.mat','r')`

While doing so I get an import error
`ImportError: No module named h5py`
as h5py module is not installed

**Question**: How do I install h5py module?

**Comment by takluyver** [comment]
If it's built using conda, you can run `conda install h5py` (in a command line, not in Python). Otherwise, `pip install h5py`.

**Comment by ugmurthy** [comment]
Thanks for your quick response **takluyver**

python imports the h5py module when I run python from the command line and import h5py.

As I mentioned, I am running Jupyter in a Docker Container and that's where I get the error - Jupyter does not recognize the h5py that I installed at the command line.

**Comment by takluyver** [comment]
Then you need to use a command line inside the docker container to install it in that container.

Inside Jupyter (with the default Python kernel), you can run command line commands by putting a `!` before them, i.e.:

```
!pip install h5py
```

**Comment by ugmurthy** [comment]
That worked. Thanks very much.

**Comment by takluyver** [comment]
Great
