### ISSUE TITLE
jupyter-notebook and ipython memory clearing

### ISSUE THREAD

**Issue by manawy** [jupyter/help#122]
Hello,

I have a computation tools which computes equilibrium in solutions [1]. It's coded in c++, but I also wrote a python interface[2] using cython.

When I run a simulation using the C++ code, or the interface with python (or ipython, using the script downloaded from the notebook) I get the solution that I expect.
However, when I run the same simulation in the jupyter-notebook the rate of failure is 50%. The failure is the optimization algorithm failing to converge. When I do get an answer, the solution is the same as in the C++ binary.

I won't classify this behavior directly as a jupyter-notebook bug, it's probably a freaky memory management issue due to the special settings of jupyter-notebook (un-initialized variable ?). However, I'm not sure how to get to the source of the problem. It's worth noting that my c++ program runs in valgrind memcheck tool without problem, and the clang ubsan and asan static analyser. So I have the following questions :

- What does "kernel restart" really do ? 
- In particular, does it destroy all objects created in the notebook ? (My impression is that it should)
- Otherwise, is there a method do to that ?
- How do you go about solving such problems when developing ipython/jupyter ?

If it's important, I use ipython 5.1.0, jupyter 4.2, python 3.4.5 and cython 0.24.1.

Best regards,
Fabien

[1] https://bitbucket.org/specmicp/specmicp
[2] https://bitbucket.org/specmicp/specmicppy

**Comment by takluyver** [comment]
> What does "kernel restart" really do ?
> In particular, does it destroy all objects created in the notebook ? (My impression is that it should)

Kernel restart asks the kernel process to exit (and if it doesn't exit promptly, kills it), and then starts a new kernel process. So yes, it does destroy all the variables created and reset the kernel to a clean state.

No idea what's causing your issue, but I hope knowing that helps.

**Comment by manawy** [comment]
Thanks, it helps to know that it's probable not directly related to how jupyter. I'll keep you informed if I find something interesting.

**Comment by manawy** [comment]
I solved the problem by fixing an uninitialized variable issue and re-compiling every library. It's definitely not a direct Jupyter notebook problem, though it's very interesting how it's more visible in this setting, it'd be very interesting to know why.
