### ISSUE TITLE
Conda environment and Error message for jupyter.widget.version

### ISSUE THREAD

**Issue by philippegr** [jupyter/help#126]
I would like to use the following setting for Jupyter Notebook and conda environments:

 - Jupyter Notebook installed as part of my default Python (the one that comes with Anaconda, basically)
 - Create a conda environment, __without__ installing the complete Notebook inside, just the kernel. (most answers online tell you to install a complete Jupyter in each and every environment, which works of course, but makes little sense given the purpose of the Notebook IMO)

So far, I'm doing (as recommended by the [documentation][1] ):

    conda create -n myNewEnv python=2 ipykernel 
    source activate myNewEnv
    python -m ipykernel install --user

And that works almost ok (all my environment are listed in Jupyter), except that I get in the terminal ` [IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version `. I haven't yet have any problem that I could link with this message, but I don't like leaving an error message hanging around.
Some forums/issues (for example [here][2]) recommend (in myNewEnv) `conda install ipywidgets --no-deps` to fix that, and it does fix it.

I understand that there has been a lot of work in 2016 to have Jupyter work nicely with conda environments (having them all listed when you click on new, and so on). So could you confirm if, as of today, the correct procedure is (the 4th line is new)? 
    
    conda create -n myNewEnv python=2 ipykernel 
    source activate myNewEnv
    python -m ipykernel install --user
    conda install ipywidgets --no-deps

Thanks a lot!

(Issue on OS X 10.11, also on Ubuntu 16.04 LTS, and I think I got it on Windows 10 as well)

  [1]: http://ipython.readthedocs.io/en/stable/install/kernel_install.html
  [2]: https://github.com/ipython/ipywidgets/issues/586

**Comment by takluyver** [comment]
If you want to get rid of the message, installing ipywidgets is the way to do it (I don't think `--no-deps` is necessary). I believe that the message is harmless if you don't want to use widgets.

**Comment by philippegr** [comment]
@takluyver, indeed the extra line `conda install ipywidgets --no-deps`solve the problem.
However, I think the --no-deps is needed, otherwise, it would install a Notebook in the environment, and that's not the point.
So would the 4 lines snippet I suggest be a proper install procedure?

**Comment by takluyver** [comment]
Ah, OK. Then yes, in that case, it's fine. It's also fine to ignore the message if you don't want to use widgets, though.

**Comment by philippegr** [comment]
Ok, thank you very much!
Just created a pull request to update the install doc
