### ISSUE TITLE
Cannot change Jupyter QtConsole font size (ipython_config.py)

### ISSUE THREAD

**Issue by jimbo1qaz** [jupyter/help#13]
OS: Windows 7 x64
Jupyter 4.1.0

I can't change the default font size for ipython qtconsole.

So far, I've tried creating `.ipython/profile_default/ipython_config.py`
```python
c = get_config()

c.IPythonWidget.font_size = 24
c.IPythonWidget.font_family = 'Consolas'
```
But this does not change the font size. I have to manually zoom in using Ctrl-Shift-+ (that should be fixed as well).

(I confirmed that the file is being run by ipython. When I add deliberate syntax errors, they show up in Command Prompt, **NOT qtconsole**)

**Comment by Carreau** [comment]
hi @jimbo1qaz , 

I think you are probably used to an older version of QtConsole, when it was part of IPython. 
Now that Qtconsole is part of Jupyter, I think that the name of the config option have changed:

```
$ jupyter qtconsole --help-all | grep font
--JupyterWidget.font_family=<Unicode>
    The font family to use for the console. On OSX this defaults to Monaco, on
--JupyterWidget.font_size=<Int>
    The font size. If unconfigured, Qt will be entrusted with the size of the
    font.
```

And you likely want to put the config in the QtConsole specific config file, which you can create with :
```
$ jupyter qtconsole --generate-config
Writing default config to: ~/.jupyter/jupyter_qtconsole_config.py
```

Does that fix your issues ?

**Comment by jimbo1qaz** [comment]
"--help-all"

Where did that come from?

**Comment by Carreau** [comment]
> "--help-all"
> 
> Where did that come from?

`--help-all` should available on all jupyter application when using the command line. @willingc this might be badly documented. Can we do something about that ?

Basically this is the same thing that generate the config file.

You should be able to find more info here: http://qtconsole.readthedocs.org/en/latest/config_options.html#options

Unfortunately there are so many options, that we cannot write a tutorial for each of them. 

Does that help a bit ?

**Comment by willingc** [comment]
I'm closing this issue. I have opened a PR in the qtconsole docs https://github.com/jupyter/qtconsole/pull/128 that adds info about ``--help-all`` there. Info about ``--help-all`` is also available [here](http://jupyter.readthedocs.io/en/latest/projects/config.html#command-line-options-for-configuration).
