### ISSUE TITLE
Problem trying to set the height of a Textarea widget

### ISSUE THREAD

**Issue by nleclercq** [jupyter/help#132]
Hi all, 
Forcing the height of a Textarea doesn't work properly (I'm using ipywidgets 6 beta 6).
Attached is a picture illustrating the problem. 
Am I doing something wrong ?
N.

![textarea_size_problem](https://cloud.githubusercontent.com/assets/19185982/22594685/5f09c54e-ea24-11e6-94ad-ed3ecab4994c.jpg)

**Comment by jasongrout** [comment]
Can you move this issue over to the ipywidgets repo? https://github.com/ipython/ipywidgets

I'm working right now on making sure setting `.layout.width` works correctly. I can check out that setting the height works too.

**Comment by nleclercq** [comment]
Ok.
