### ISSUE TITLE
cannot install jupyter on ppc64le architecture

### ISSUE THREAD

**Issue by hjk1023** [jupyter/help#137]
I can not install jupyter on ubuntu with ppc64le architecture. I want to konw whether jupyter can be installed on this architecture or not.
Thanks.

**Comment by takluyver** [comment]
Jupyter requires Python and pyzmq (bindings to the zeromq messaging library). If you can get those things installed on your platform, all the rest is Python code, for which the architecture doesn't matter. Shouldn't matter, anyway - you may hit edge cases because I don't know that anyone else has tried that. Let us know how you get on!

**Comment by hjk1023** [comment]
when installing anaconda I got the follow message:
`WARNING：Your operating system appears not to be 64-bit, but you are trying to                                                                                install a 64-bit version of Anaconda2.Are sure you want to continue the installation? [yes|no]`
but my ststem is 64-bit.
`Anaconda2-4.2.0-Linux-x86_64.sh: line 496: /root/anaconda/pkgs/python-2.7.12-1/bin/python: cannot execute binary file: Exec format error
ERROR:
cannot execute native linux-64 binary, output from 'uname -a' is:
Linux nova-0b261ed2-7602-4f4d-bf1b-3b4fdf84004d 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:17:43 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux`

**Comment by SylvainCorlay** [comment]
Then you probably need to download a 32 bits version of anaconda.

**Comment by hjk1023** [comment]
I tried and still got this error:
`Anaconda2-4.3.0-Linux-x86.sh: line 494: /root/anaconda2/pkgs/python-2.7.13-0/bin/python: cannot execute binary file: Exec format error               ERROR:                                                                                                                                               cannot execute native linux-32 binary, output from 'uname -a' is:                                                                                    Linux nova-c2e4bee0-3750-484e-bdd5-e1a43473a962 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:17:43 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux`

**Comment by takluyver** [comment]
'32-bit' and '64-bit' refer to x86 and x86_64 (aka amd64) architectures, respectively. I'm pretty sure Anaconda does not ship binaries compiled for ppc64le (though maybe Continuum do it or would do it with a commercial contract).

I imagine you have Python installed or can install it as part of Ubuntu. Can you also use apt to install `python3-zmq` or `python-zmq`? If so, then you should be able to `pip install jupyter`.

**Comment by hjk1023** [comment]
I have installed jupyter successfully according to your instruction.
Many thanks!
