### ISSUE TITLE
mysterious ipywidgets problem

### ISSUE THREAD

**Issue by akhmerov** [jupyter/help#139]
I observe the weirdest thing: two notebooks, *full* copies of each other (`diff nb1.ipynb nb2.ipynb` shows nothing).  If I execute the first one, each cell with widgets shows the warning `Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"`, but the widgets do render and run correctly (!). However in the other identical notebook the warning isn't shown (!!!)

The notebook filenames are not special: `grade.ipynb` `debug.ipynb`. Doing `mv grade.ipynb grader.ipynb` makes the warnings disappear, but renaming it back makes the warnings return.

Also previously I've registered the `widgetsnbextension` both `--sys-prefix` and `--user`.

Any idea how I could investigate the issue further?

**Comment by SylvainCorlay** [comment]
Can you check if the warning shows if you wait for the kernel to be fully launched before running any cell?

**Comment by akhmerov** [comment]
Ahh! It seems to be indeed dependent on some timing: if I execute the cells by hand, there's no warning, and it only appears with "restart and run all". Is this a known issue?

**Comment by SylvainCorlay** [comment]
Ok. This is a bug in notebook.

**Comment by akhmerov** [comment]
Thanks. Do you mind mind opening the issue? I'm unsure what to provide in the description, and you seem to understand better what is happening.

**Comment by SylvainCorlay** [comment]
There is one but I am afk at the moment. I Will provide a link tomorrow.

**Comment by jasongrout** [comment]
I think this is the issue Sylvain is referring to: https://github.com/jupyter/notebook/issues/2087

**Comment by akhmerov** [comment]
Thanks! The mystery is resolved.
