### ISSUE TITLE
LaTeX in python code cell like with Julia?

### ISSUE THREAD

**Issue by 17643015** [jupyter/help#143]
Is there a way such that one may use LaTeX symbols in a python code environment like one can do in Julia environments?

For example "\alpha" and pressing tab in Julia environment would yield the alpha symbol. Perhaps there is a widget or nb_extension for this I have been unable to find?

**Comment by takluyver** [comment]
Exactly the same thing (`\alpha<tab>`) should work so long as your kernel is running on Python 3 (because unicode letters are valid in identifiers on Python 3).

**Comment by 17643015** [comment]
Thank you for the response, unfortunately I am running python 2.7.12. Is there a way to get the same result with python 2.7.12?

**Comment by takluyver** [comment]
Not at present, no. Upgrading to Python 3 is recommended, especially if you want to use unicode symbols.

**Comment by 17643015** [comment]
Ok I will change over to python 3 then. Thank you for the information.

**Comment by 17643015** [comment]
Do you know of a complete list of unicode symbols together with their jupyter commands eg "\alpha"?

**Comment by takluyver** [comment]
For IPython, the list is stored in this file: https://github.com/ipython/ipython/blob/master/IPython/core/latex_symbols.py

I think we copied it off Julia, taking out some that weren't valid in Python names.
