### ISSUE TITLE
[traitlets] how to re-trigger initialization

### ISSUE THREAD

**Issue by akhmerov** [jupyter/help#144]
I'm making a class where two traits are related and change in one can invalidate the other. If this happens, I would like to assign a new value to the invalidated trait by generating its default value. What is the way to achieve that most compatible with the traitlets design?

**Comment by akhmerov** [comment]
Uhm, sometimes trying things first helps. Turns out this happens automatically.

**Comment by minrk** [comment]
If I understand correctly, I would do it by calling the `a` initializer when `b` changes:


```python

class C(HasTraits):
    a = Unicode()
    @default('a')
    def _default_a(self):
        return 'default a'

    b = Unicode()
    @observe('b')
    def _b_changed(self, change):
        self.a = self._a_default()
```

**Comment by akhmerov** [comment]
Thanks. This is also the solution I ended up with. It feels a little like a hack since from the traits point of view I'm using internal functionality. I hoped there was something like `change_to_default_if_invalid` option for the trait config, but there isn't.

**Comment by minrk** [comment]
@akhmerov you aren't using functionality internal to anything other than your own object, which defines the method. Note that since the `@default` decorator came in, the name of the method is no longer significant, only that it is decorated with `@default('a')`.

**Comment by akhmerov** [comment]
@minrk my concern is not so much about a private method use, but rather having a `HasTraits` instance that would raise on trying to do `c.a = c.a` (because it is brought to an invalid state by changing `c.b`). Of course I can fix this, but it seems reasonable to enforce this pattern so that getting `c.a` *never* returns and invalid value.
