### ISSUE TITLE
Update HTML function in a loop

### ISSUE THREAD

**Issue by ysg410** [jupyter/help#146]
My application needs some computations running on multiple threads. Due to which, as soon as some python variable is changed, I need to update it in the UI by using the HTML component of IPython.core.display. My issue is that, when called inside in a loop or a function, the HTML component does not render the UI at all. I am using Template(from string library) to pass data between Python and JS.

My template code looks like : 
`html_template = Template('''
    <div id="chartContainer" style="height:300px; width:95%;"></div>
    <script> $js_text </script>
    ''')`
And i render the UI by using : 
`HTML(html_template.substitute({'js_text': js_text}))`

These commands do not work inside a loop or from inside a function.

**Comment by minrk** [comment]
Calling `HTML()` only instantiates an object, it does not display it. If this is at the end of the cell, it gets displayed as the result of the cell. Otherwise, you need to call `display(HTML(...))` explicitly.
