### ISSUE TITLE
errors in docs

### ISSUE THREAD

**Issue by wotanii** [jupyter/help#152]
Where did I report errors in the docs?

The error I want to report: 

> on [this page in the docs](
> http://jupyter.readthedocs.io/en/latest/projects/content-projects.html#how-do-i-decide-which-packages-i-need) is a diagram, that contains references. Some of those references are wrong: 
> - "Extensions" links to https://github.com/jupyter/help
> - "Dasboards" links to https://github.com/ipython-contrib/jupyter_contrib_nbextensions

**Comment by takluyver** [comment]
Reporting errors here is OK, or the gold standard would be reporting them on the repo containing those docs - in the case of jupyter.readthedocs.org, that's the [jupyter/jupyter repo](https://github.com/jupyter/jupyter).

Actually, the gold standard would be making a pull request ;-) Here's the file in question:
https://github.com/jupyter/jupyter/blob/master/docs/source/projects/content-projects.rst

**Comment by wotanii** [comment]
> Actually, the gold standard would be making a pull request ;-)

[done :-)](https://github.com/jupyter/jupyter/pull/250)
