### ISSUE TITLE
What triggers kernel restart?

### ISSUE THREAD

**Issue by BoPeng** [jupyter/help#153]
I have been puzzled by this for quite a few days so it is perhaps better to ask for some help.

My kernel (http://github.com/vatlab/SOS) works most the time. I could see `kernel created`, `kernel connected`, and `kernel ready`, and I can use it properly. However, from time to time, when I start a new notebook with the  sos kernel, the cell would be running forever with `*`, and sometimes with an output but with `*` in input, and I cannot execute any more cell. The problem happens most often when I start a cell and evaluate something very fast before the kernel is ready.

Now, from the JS console, I can see a kernel created event after kernel ready, and I cannot see a second kernel ready message (which is likely the problem)

```
Loading extension: jupyter-js-widgets/extension
extension.js:88 loaded widgets
main.min.js:22480 Kernel: kernel_connected (7185e96a-a60b-49ab-9d33-f46f4a002119)
kernel.js?v=20170323223000:275 sos comm registered
kernel.js?v=20170323223000:295 executor patched
main.min.js:22480 Kernel: kernel_ready (7185e96a-a60b-49ab-9d33-f46f4a002119)
kernel.js?v=20170323223000:284 kernel list requested
2manager-base.js:195 Widget backend and frontend versions are compatible
main.min.js:22480 Kernel: kernel_created (7185e96a-a60b-49ab-9d33-f46f4a002119)
main.min.js:22833 Starting WebSockets: ws://localhost:8888/api/kernels/7185e96a-a60b-49ab-9d33-f46f4a002119
main.min.js:22480 Kernel: kernel_connected (7185e96a-a60b-49ab-9d33-f46f4a002119)
kernel.js?v=20170323223000:275 sos comm registered
sos.js Failed to load resource: the server responded with a status of 404 (Not Found)
:8888/kernelspecs/sos/kernel.js?v=20170323223000:181 kernel list updated
:8888/nbextensions/jupyter-js-widgets/extension.js?v=20170323223000:264 Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.
    at :8888/nbextensions/jupyter-js-widgets/extension.js?v=20170323223000:32285
```
so it appears to me that the first kernel is executing something, then the kernel is restarted for some reason, and the notebook cannot get the output from the preview session and hang forever.

From the terminal (with `--debug` option), I can see

```
[D 22:30:16.590 NotebookApp] Starting kernel: ['python', '-m', 'sos.jupyter.kernel', '-f', '/Users/bpeng1/Library/Jupyter/runtime/kernel-7185e96a-a60b-49ab-9d33-f46f4a002119.json']
[D 22:30:16.597 NotebookApp] Connecting to: tcp://127.0.0.1:51812
[I 22:30:16.599 NotebookApp] Kernel started: 7185e96a-a60b-49ab-9d33-f46f4a002119
[D 22:30:16.599 NotebookApp] Kernel args: {'kernel_name': 'sos', 'cwd': '/Users/bpeng1/sos'}
[D 22:30:16.601 NotebookApp] 201 POST /api/sessions (::1) 38.22ms
[D 22:30:16.605 NotebookApp] Serving kernel resource from: /Users/bpeng1/anaconda/share/jupyter/kernels/sos
[D 22:30:16.606 NotebookApp] 200 GET /kernelspecs/sos/kernel.js?v=20170323223000 (::1) 3.58ms
[D 22:30:16.608 NotebookApp] Path components/MathJax/extensions/Safe.js served from /Users/bpeng1/anaconda/lib/python3.6/site-packages/notebook/static/components/MathJax/extensions/Safe.js
[D 22:30:16.609 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?rev=2.6.0 (::1) 2.53ms
[D 22:30:16.611 NotebookApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?_=1490326216233 (::1) 1.79ms
[D 22:30:16.613 NotebookApp] Path jupyter-js-widgets/extension.js served from /Users/bpeng1/anaconda/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
[D 22:30:16.630 NotebookApp] Initializing websocket connection /api/kernels/7185e96a-a60b-49ab-9d33-f46f4a002119/channels
[D 22:30:16.634 NotebookApp] Requesting kernel info from 7185e96a-a60b-49ab-9d33-f46f4a002119
[D 22:30:16.634 NotebookApp] Connecting to: tcp://127.0.0.1:51809
[D 22:30:16.644 NotebookApp] 200 GET /nbextensions/jupyter-js-widgets/extension.js?v=20170323223000 (::1) 32.30ms
[D 22:30:16.671 NotebookApp] Path components/codemirror/addon/selection/active-line.js served from /Users/bpeng1/anaconda/lib/python3.6/site-packages/notebook/static/components/codemirror/addon/selection/active-line.js
[D 22:30:16.673 NotebookApp] 200 GET /static/components/codemirror/addon/selection/active-line.js?v=20170323223000 (::1) 2.66ms
[D 22:30:17.720 NotebookApp] Starting kernel: ['python', '-m', 'sos.jupyter.kernel', '-f', '/Users/bpeng1/Library/Jupyter/runtime/kernel-7185e96a-a60b-49ab-9d33-f46f4a002119.json']
[D 22:30:17.723 NotebookApp] Connecting to: tcp://127.0.0.1:51812
[I 22:30:17.724 NotebookApp] Kernel restarted: 7185e96a-a60b-49ab-9d33-f46f4a002119
[D 22:30:17.724 NotebookApp] Connecting to: tcp://127.0.0.1:51809
[D 22:30:17.726 NotebookApp] Path components/jquery-ui/themes/smoothness/images/ui-icons_222222_256x240.png served from /Users/bpeng1/anaconda/lib/python3.6/site-packages/notebook/static/components/jquery-ui/themes/smoothness/images/ui-icons_222222_256x240.png
[D 22:30:17.727 NotebookApp] 304 GET /static/components/jquery-ui/themes/smoothness/images/ui-icons_222222_256x240.png (::1) 1.36ms
[D 22:30:19.650 NotebookApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.0', 'implementation': 'SOS', 'implementation_version': '0.9.4', 'language_info': {'mimetype': 'text/x-sos', 'name': 'sos', 'file_extension': '.sos', 'pygments_lexer': 'sos', 'codemirror_mode': 'sos', 'nbconvert_exporter': 'sos.jupyter.converter.SoS_Exporter'}, 'banner': 'SoS kernel - script of scripts\nConnection file kernel-7185e96a-a60b-49ab-9d33-f46f4a002119.json', 'help_links': [{'text': 'Python', 'url': 'http://docs.python.org/3.6'}, {'text': 'IPython', 'url': 'http://ipython.org/documentation.html'}, {'text': 'NumPy', 'url': 'http://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy', 'url': 'http://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib', 'url': 'http://matplotlib.org/contents.html'}, {'text': 'SymPy', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas', 'url': 'http://pandas.pydata.org/pandas-docs/stable/'}]}
[D 22:30:19.651 NotebookApp] Opening websocket /api/kernels/7185e96a-a60b-49ab-9d33-f46f4a002119/channels
[D 22:30:19.651 NotebookApp] Connecting to: tcp://127.0.0.1:51809
[D 22:30:19.652 NotebookApp] Connecting to: tcp://127.0.0.1:51810
[D 22:30:19.652 NotebookApp] Connecting to: tcp://127.0.0.1:51811
[D 22:30:19.675 NotebookApp] Kernel info reply received: 7185e96a-a60b-49ab-9d33-f46f4a002119
[D 22:30:19.675 NotebookApp] 200 POST /api/kernels/7185e96a-a60b-49ab-9d33-f46f4a002119/restart (::1) 2979.47ms
...
```

but I do not see any particular reason why the kernel is restarted after it seems to be running ok. I understand that there might be something wrong with my customized kernel but any insight or how I can continue to debug this problem would be highly apprecaited.

Many thanks in advance!

**Comment by takluyver** [comment]
The server restarts the kernel if it dies unexpectedly, but I'm not sure that that's what's going on here. The final line of the logging you shows indicates that the server handled an HTTP request asking it to restart the kernel. I'm not sure what would trigger that - maybe there's something in the JS that tries to handle a kernel not being ready quickly enough. :confused:

**Comment by BoPeng** [comment]
'kernel not being ready quickly enough' sounds right because I see 

```
[D 06:50:35.086 NotebookApp] Connecting to: tcp://127.0.0.1:49667
[D 06:50:36.185 NotebookApp] Starting kernel: ['python', '-m', 'sos.jupyter.kernel', '-f', '/Users/bpeng1/Library/Jupyter/runtime/kernel-22652e06-363b-4753-9eb3-daf0f9c97e98.json']
[D 06:50:36.189 NotebookApp] Connecting to: tcp://127.0.0.1:49670
[I 06:50:36.189 NotebookApp] Kernel restarted: 22652e06-363b-4753-9eb3-daf0f9c97e98
[D 06:50:36.190 NotebookApp] Connecting to: tcp://127.0.0.1:49667
[D 06:50:36.193 NotebookApp] 200 GET /api/sessions?_=1490355791932 (::1) 1.19ms
[D 06:50:36.195 NotebookApp] 200 GET /api/terminals?_=1490355791933 (::1) 0.92ms
[D 06:50:36.197 NotebookApp] 304 GET /static/components/jquery-ui/themes/smoothness/images/ui-icons_222222_256x240.png (::1) 1.19ms
[D 06:50:36.207 NotebookApp] 200 GET /api/contents?type=directory&_=1490355791934 (::1) 8.34ms
[D 06:50:37.704 NotebookApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.0', 'implementation': 'SOS', 'implementation_version': '0.9.4', 'language_info': {'mimetype': 'text/x-sos', 'name': 'sos', 'file_extension': '.sos', 'pygments_lexer': 'sos', 'codemirror_mode': 'sos', 'nbconvert_exporter': 'sos.jupyter.converter.SoS_Exporter'}, 'banner': 'SoS kernel - script of scripts\nConnection file kernel-22652e06-363b-4753-9eb3-daf0f9c97e98.json', 'help_links': [{'text': 'Python', 'url': 'http://docs.python.org/3.6'}, {'text': 'IPython', 'url': 'http://ipython.org/documentation.html'}, {'text': 'NumPy', 'url': 'http://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy', 'url': 'http://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib', 'url': 'http://matplotlib.org/contents.html'}, {'text': 'SymPy', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas', 'url': 'http://pandas.pydata.org/pandas-docs/stable/'}]}
[D 06:50:37.705 NotebookApp] Kernel info reply received: 22652e06-363b-4753-9eb3-daf0f9c97e98
[D 06:50:37.705 NotebookApp] Opening websocket /api/kernels/22652e06-363b-4753-9eb3-daf0f9c97e98/channels
```

If kernel being ready is the amount of time to run the command in log file (`['python', '-m', 'sos.jupyter.kernel', '-f', ` ...), sos is indeed slower than others.

```
$ time python -c 'import sos.jupyter.kernel'

real	0m1.407s
user	0m1.251s
sys	0m0.147s
```

```
$ time python -c 'import ipykernel'

real	0m0.809s
user	0m0.722s
sys	0m0.083s
```

```
$ time python -c 'import bash_kernel'

real	0m0.835s
user	0m0.721s
sys	0m0.082s
```

I can try to improve the loading time of sos but do you think what I was describing (Namely, cell was sent to kernel for evaluation, kernel restarted, and frontend got stuck) was the problem? If so, is there anyway for the newly started kernel to "clean up" and "unfreeze" the frontend (e.g. on `kernel_connected.Kernel`)?

**Comment by takluyver** [comment]
There have been some strange issues with kernel startup in the past. Can you try the notebook 5.0 release candidate (`pip install --upgrade --pre notebook`) and see if it works any better for you?

Other than that, does the notebook interface say that the kernel is ready before you try to send a cell for evaluation, or are you sending it before the kernel finishes starting?

**Comment by BoPeng** [comment]
I do not know how to "wait for the kernel to be ready to start evaluating". From what I have seen, the cell is sent for evaluation before the kernel is ready. If I understand correctly, the  cell would be queued and be evaluated after the server is ready, but in my case the cell has started evaluation but the kernel is restarted.

**Comment by BoPeng** [comment]
I notice a difference with notebook 5.0. Namely if I evaluate a cell right after the notebook appears, the cell could evaluate then stop (no result with `*` cleared), which I suppose was because the kernel is not ready. Then the cell could be evaluated normally after the kernel is ready, which is a HUGE improvement.

Thank you very much for the help. Perhaps I should open a ticket earlier next time. :smile:

**Comment by takluyver** [comment]
Great! Still not perfect, because I thought there was something that queued the execution until the kernel was ready. @jasongrout @SylvainCorlay am I right about that? I think I recall something about that and widgets.

**Comment by BoPeng** [comment]
It is a bit complicated because sos sends a request for a list of available kernels immediately after the kernel is ready, maybe that delays the communication.

But upon checking the JS code, I think the real issue is [a forced "restart" call](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.js#L996) if a kernel already exists during `onload`. The reason for this restart is that when a page is refreshed, the cached `comm` object is lost so the frontend and kernel can no longer communicate. Removing this line of code seems to fix the restart issue (not 100% sure because the problem happens randomly), but the comm issue after refresh comes back (with error message `Comm promise not found for comm id c4b838ce0c384e67a521ea91d053753f`).

I googled and found that the Julia kernel also has [this issue](https://github.com/sglyon/PlotlyJS.jl/pull/92). Since restarting the kernel seems to be a wrong fix, what would be your recommended way of fixing this? The relevant code is

kernel [creates a Comm](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.py#L381) if there is no comm.

[frontend register comm](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.js#L128) upon [kernel connect](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.js#L998)

**Comment by BoPeng** [comment]
I fixed the comm-disconnect-upon-page-reload issue by [re-registering comm and notifying the kernel](https://github.com/vatlab/SOS/commit/973264bc9373c2135739dcf468c37b5b81228988) so that the kernel would use a new `Comm` object.  I will see if this also fixed the notebook-get-stuck issue.
