### ISSUE TITLE
Python 3.6-style formatted string literals beginning with `f'` or `f"` are not highlighted correctly

### ISSUE THREAD

**Issue by NickAnderegg** [jupyter/help#155]
Python introduced [formatted string literals](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) in 3.6. With this syntax, a string literal prefixed with `f` can directly accept variables in replacement fields.

For example, in this code:

```python
print(data_file.name) # Output: file_101.csv
file_name = data_file.name # file_name = "file_101.csv"
file_name = f'./fixed_data/{file_name}' # file_name = "./fixed_data/file_101.csv"
fixed_file = pathlib.Path(file_name)
print(fixed_file) # Output: fixed_data/file_101.csv
```
line 3 sets `file_name` to be equal to "./fixed_data/file_101.csv" because the original `file_name` variable is inserted into the replacement field in a string literal prefixed with `f`.

However, this string literal formatting seems to break the code highlighting in Juypter. For whatever reason, everything passed the `f'` or `f"` is highlighted as if it is part of the string literal:

![image](https://cloud.githubusercontent.com/assets/542937/24480750/f7bdd91a-14b3-11e7-84f5-e6e90a886995.png)

The output of this cell is exactly as expected, indicated that this is an issue with Jupyter's code highlighting parses, rather than anything specifically related to the underlying kernel.

**Comment by takluyver** [comment]
This seems to have been fixed somewhere along the line - hopefully you've also got the fix by now. :-)
