### ISSUE TITLE
can't import sklearn in python2

### ISSUE THREAD

**Issue by Fiasco-zh** [jupyter/help#156]
"ImportError: No module named sklearn.model_selection"
In env(python=2) I can import sklearn in command line or termination opened from jupyter notebook, but can't successfully import sklearn while using notebook . 
In env(python=3), have no problem with it.

**Comment by takluyver** [comment]
The kernel may not be running in the env you think it is - check `sys.executable`. You can use `jupyter kernelspec list` to see where it's finding information about the available kernels.

**Comment by Fiasco-zh** [comment]
Available kernels:
  python3    /Users/Yujia/anaconda/envs/Boston2/lib/python3.6/site-packages/ipykernel/resources
  python2    /Users/Yujia/Library/Jupyter/kernels/python2

how can I do to solve the problem?

**Comment by minrk** [comment]
What is `sys.executable` when you can import `sklearn` successfully?

**Comment by Fiasco-zh** [comment]
I create a new evn named Boston.
here is the jupyter kernelspec list:
Available kernels:
  python2    /Users/Yujia/Library/Jupyter/kernels/python2

and this is the sys.executable:
'/Users/Yujia/anaconda/envs/Boston/bin/python'

**Comment by Fiasco-zh** [comment]
Hi, I try it. 
`Installed kernelspec boston in /Users/Yujia/Library/Jupyter/kernels/boston`
but still not work. 
I found some thing may cause the error, when the notebook launch, 
`[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version`

**Comment by minrk** [comment]
When it doesn't work, do you pick the kernel "boston" from the Kernel menu?

**Comment by Fiasco-zh** [comment]
It works! Thank you very much! Apology for replying so late.
