### ISSUE TITLE
How to get comm object from JS side to send message?

### ISSUE THREAD

**Issue by BoPeng** [jupyter/help#158]
Following the [comm documentation](http://jupyter-notebook.readthedocs.io/en/latest/comms.html), I am able to create a comm object in the kernel and send message to the frontend. Basically, on the frontend/javascript side, I have

```
        Jupyter.notebook.kernel.comm_manager.register_target('my_comm',
            function(comm, msg) {
                comm.on_msg(function(msg) { ... 
            }
        )
```
and on the kernel/Python side, I have
```
frontend_comm = Comm(target_name="my_comm", data={})
frontend_comm.send(my_msg)
```

Now I would like to send some message from the frontend to the kernel, not as a response to kernel message, but I do not know how to get hold of the frontend comm, is there something like the following?

```
comm = Jupyter.notebook.kernel.comm_manager.get_comm('my_comm')
comm.send(msg_to_kernel)
```

**Comment by BoPeng** [comment]
I "solved" this problem by creating another comm channel from the frontend, please close this ticket if comm is supposed to work this way.

**Comment by takluyver** [comment]
The `my_comm` target name can be reused to open multiple comms, so it doesn't identify the comm once it's open. There is a unique comm ID that can be used to retrieve the comm object like `comm_manager.comms[comm_id]` - but if you can pass the ID around, you can probably pass the Comm object itself around.

**Comment by jasongrout** [comment]
In widgets, we store all of the opened comm objects in a single global-ish store, which we can then interact with as needed. It's meant to be two-way communication channels between specific object instances, created every time a comm open message is sent, so if you can pass around the comm object from a newly created comm, that's the way it's supposed to work.

**Comment by BoPeng** [comment]
I guess I am missing something really obvious here, from the frontend, after calling,

```
        Jupyter.notebook.kernel.comm_manager.register_target('my_comm',
            function(comm, msg) {
                comm.on_msg(function(msg) { ... 
            }
        )
```

how can I get the `comm` object (or `comm_id`) so that I can send message from frontend?

**Comment by BoPeng** [comment]
Looking again at the doc, am I supposed to keep a copy of `comm` as follows?

```
Jupyter.notebook.kernel.comm_manager.register_target('my_comm_target',
    function(comm, msg) {
        // comm is the frontend comm instance
        // msg is the comm_open message, which can carry data
        window.my_comm = comm;

        // Register handlers for later messages:
        comm.on_msg(function(msg) {...});
        comm.on_close(function(msg) {...});
        comm.send({'foo': 0});
    });
```
and then use the saved `comm` instance as follows?
```
window.my_comm.send(some_msg)
```

**Comment by jasongrout** [comment]
That's one way, but I probably wouldn't set it on the window object as a global variable if I could help it. In JupyterLab, you could have multiple notebooks on a single page, and they would stomp on each other that way.

I think it would be better to have all the code that could send or receive messages in one place, one object, and then instantiate that object with the comm from the target handler.

**Comment by BoPeng** [comment]
Thanks for the advice. I will try to make it work.
