### ISSUE TITLE
DockerSpawner Failed to Start

### ISSUE THREAD

**Issue by tjcrone** [jupyter/help#159]
Hello I am having trouble starting a notebook using dockerspawner. I am getting a Spawner failed to start message. Here are the log messages and the docker logs output:

[I 2017-04-15 11:09:41.720 JupyterHub dockerspawner:449] Starting container 'jupyter-tjc' (id: ba60216)
[W 2017-04-15 11:09:51.721 JupyterHub web:1545] 500 GET /hub/user/tjc (::ffff:64.145.79.220): Spawner failed to start [status=ExitCode=127, Error='', FinishedAt=2017-04-15T15:09:42.017134584Z]

root@berna:/etc/jupyterhub# docker logs jupyter-tjc
/usr/local/bin/start-singleuser.sh: 13: exec: jupyterhub-singleuser: not found
/usr/local/bin/start-singleuser.sh: 13: exec: jupyterhub-singleuser: not found
/usr/local/bin/start-singleuser.sh: 13: exec: jupyterhub-singleuser: not found

Any idea what is going on? Thanks!

**Comment by dmvieira** [comment]
Hey guy, could you please share your solution?

**Comment by tjcrone** [comment]
We continued this issue here: https://github.com/jupyterhub/jupyterhub/issues/1083

**Comment by dmvieira** [comment]
It's just conda path that's not in path. Add it at jupyterhub_config.py:

`c.DockerSpawner.extra_create_kwargs = {"command": 'env PATH="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" /usr/local/bin/start-singleuser.sh'}
`
Solved for me
