### ISSUE TITLE
jupyter notebook issue after clicking on conda tab

### ISSUE THREAD

**Issue by mlohri** [jupyter/help#160]
Hi,
I intend to use jupyter notebook from the conda prompt. My environment is Windows 10, Python 2.

After having started jupyter notebook from a specific conda environment [DAND], the notebook starts as expected. But as soon as I click on the conda tab, I get the following error messages.

<img width="481" alt="capture" src="https://cloud.githubusercontent.com/assets/27675209/25085172/04911c7c-2361-11e7-94f9-4c47580e0c2f.PNG">
<img width="646" alt="capture1" src="https://cloud.githubusercontent.com/assets/27675209/25085173/04920862-2361-11e7-9822-55f7bd09176f.PNG">
<img width="878" alt="capture2" src="https://cloud.githubusercontent.com/assets/27675209/25085171/048f671a-2361-11e7-8253-0da3774165dd.PNG">

How can I resolve the issue?

Thank you
Marius

**Comment by takluyver** [comment]
That error appears to be coming from nb_conda code, not code we control. You can ask them about it at https://github.com/Anaconda-Platform/nb_conda
