### ISSUE TITLE
PDF'ing with Jupyter Notebook

### ISSUE THREAD

**Issue by eddy-ojb** [jupyter/help#163]
Hello,

At the end of this message there is json code. Please save it in to a text file, save the file as .ipynb and open in Jupyter to view an illustration of my main issue with Jupyter, which is that exporting to pdf is not useable.

Jupyter is superb in a lot of respects but there is real demand in the data science cumminity when it comes to presenting documents properly with Jupyter. We end up having to translate all the work we've done in Jupyter to another editor so that documents that can be pdf'ed and printed. Tedious and prone to mistakes.

Unfortunately, most of the world uses pdf's for viewing and printing professional documents. It would be handy to produce work with figures using code in the background, selectively hide inputs or outputs and pdf efficiently for professional presentation. This is handy in the event that documents are printed and annotated by hand (we all do it).

If Jupyter tries to appear like everything is laid out on a page and allows the use of markdown, HTML and Latex editing, why not actually try and achieve the real thing instead of presenting the illusion?

Ed

----------------

{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "toc": "true"
   },
   "source": [
    "# Table of Contents\n",
    " <p><div class=\"lev1 toc-item\"><a href=\"#Some-code:\" data-toc-modified-id=\"Some-code:-1\"><span class=\"toc-item-num\">1&nbsp;&nbsp;</span>Some code:</a></div><div class=\"lev1 toc-item\"><a href=\"#Test-pdf'ing-of-bullet-points\" data-toc-modified-id=\"Test-pdf'ing-of-bullet-points-2\"><span class=\"toc-item-num\">2&nbsp;&nbsp;</span>Test pdf'ing of bullet points</a></div><div class=\"lev1 toc-item\"><a href=\"#Line-breaks\" data-toc-modified-id=\"Line-breaks-3\"><span class=\"toc-item-num\">3&nbsp;&nbsp;</span>Line breaks</a></div><div class=\"lev1 toc-item\"><a href=\"#More-HTML-imcompatibility:\" data-toc-modified-id=\"More-HTML-imcompatibility:-4\"><span class=\"toc-item-num\">4&nbsp;&nbsp;</span>More HTML imcompatibility:</a></div><div class=\"lev1 toc-item\"><a href=\"#Page-Break\" data-toc-modified-id=\"Page-Break-5\"><span class=\"toc-item-num\">5&nbsp;&nbsp;</span>Page Break</a></div><div class=\"lev1 toc-item\"><a href=\"#Margins\" data-toc-modified-id=\"Margins-6\"><span class=\"toc-item-num\">6&nbsp;&nbsp;</span>Margins</a></div><div class=\"lev1 toc-item\"><a href=\"#Referencing\" data-toc-modified-id=\"Referencing-7\"><span class=\"toc-item-num\">7&nbsp;&nbsp;</span>Referencing</a></div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Some code:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>HomeID</th>\n",
       "      <th>Price</th>\n",
       "      <th>SqFt</th>\n",
       "      <th>Bedrooms</th>\n",
       "      <th>Bathrooms</th>\n",
       "      <th>Offers</th>\n",
       "      <th>Brick</th>\n",
       "      <th>Neighborhood</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>114300</td>\n",
       "      <td>1790</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>East</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   HomeID   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood\n",
       "0       1  114300  1790         2          2       2    No         East"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv('house_prices.csv')\n",
    "\n",
    "df.head(n=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Test pdf'ing of bullet points"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<ul>\n",
    "  <li>Lorem ipsum dolor sit amet</li>\n",
    "  <ul>\n",
    "      <li>Phasellus iaculis neque</li>\n",
    "      <li>Purus sodales ultricies</li>\n",
    "    </ul>\n",
    "</ul>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Line breaks"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Here is a line break because I want to start a new paragraph. <br>\n",
    "\n",
    "Now here are some example quotes:\n",
    "\n",
    "\n",
    "1. “If you're not failing every now and again, it's a sign you're not doing anything very innovative.”\n",
    "2. “Confidence is what you have before you understand the problem.”"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Why does Jupyter give the appearence that everything is on pages. <br>\n",
    "We can alter the justification of the text but this doesn't translate to pdf:<br>\n",
    "\n",
    "<div style=\"text-align: center\"> some text</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# More HTML imcompatibility:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div class=\"alert alert-block alert-info\">\n",
    "\n",
    "Hello"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Page Break"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "-----"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Did the page break work?"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Margins"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "No clear way of achieving this"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Referencing"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Again, no clear way of achieving this"
   ]
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python [conda root]",
   "language": "python",
   "name": "conda-root-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  },
  "toc": {
   "colors": {
    "hover_highlight": "#DAA520",
    "navigate_num": "#000000",
    "navigate_text": "#333333",
    "running_highlight": "#FF0000",
    "selected_highlight": "#FFD700",
    "sidebar_border": "#EEEEEE",
    "wrapper_background": "#FFFFFF"
   },
   "moveMenuLeft": true,
   "nav_menu": {
    "height": "141px",
    "width": "252px"
   },
   "navigate_menu": true,
   "number_sections": true,
   "sideBar": false,
   "threshold": 4,
   "toc_cell": true,
   "toc_section_display": "block",
   "toc_window_display": false,
   "widenNotebook": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}

**Comment by takluyver** [comment]
We're working on some bits of this (cc @mpacer), but our PDF export is based on Latex, and HTML/Markdown doesn't translate easily to Latex code. Latex is both a more semantic way to describe a document, and a Turing-complete programming language, so it's not the easiest environment to target.

You may have more luck exporting to HTML and then 'printing' the resulting document to a PDF from a web browser. It would be possible to write an nbconvert exporter which automated this using a headless browser such as [wkhtmltopdf](https://wkhtmltopdf.org/).

A couple of specific points:

- Your Markdown 'page break' produces a line across the document (HTML `<hr>` tag), not a page break. So I think the horizontal line in the PDF is what I'd expect.
- Referencing: I have a side project [cite2c](https://github.com/takluyver/cite2c) to add references, though the citations do not yet show up on export (takluyver/cite2c#7).
- If you want to show a notebook, rather than pasting the raw JSON in an issue, you can put it in a [gist](https://gist.github.com/), and then use [nbviewer](http://nbviewer.jupyter.org/) to get a link that shows the content as HTML.

**Comment by eddy-ojb** [comment]
Thanks takluver.

Cite2c looks awesome!

This post:

https://github.com/jupyter/notebook/issues/2458#issuecomment-298208501

is a duplicate of this one, which I wrote and revisited later on in the day after my pdf'ing nightmare only to find it wasn't on the thread. That was because I was searching the wrong thread, so assumed I hadn't submitted properly. Are you OK if I close this thread and append your cite2c solution to the other thread?

Thanks for the pointers.

Best

Ed

**Comment by takluyver** [comment]
Yep, let's close this so the conversation can be in one place.
