### ISSUE TITLE
XSRF cookie does not match POST argument

### ISSUE THREAD

**Issue by SaintNazaire** [jupyter/help#172]
I am trying to transfert files using a python program running on a local Anaconda to a local Jupyter within a docker container using the Jupyter rest API.

I managed already to execute a requests.get() succesfully after muddling-through a bit on how to input the token.

Now I would like to execute a requests.post() command to transfert the files.

Configuration:
1. local docker container running on docker toolbox for windows
- docker version 17.04.0-ce, build 4845c56
- tensorflow/tensorflow incl. Jupyter latest version install
- jupyter_kernel_gateway==0.3.1
2. local Anaconda v. 4.3.14 running on a windows 10 machine

Code:
```
token = token_code_provided_by_jupyter_at_startup
api_url = "http://192.168.99.100:8888/api/contents"
# getting the file's data from disk and converting into a json file
cwd` = os.getcwd()
file_location` = cwd+r'\Resources\Test\test_post.py'
payload` = open(file_location, 'r').read()
b64payload` = base64.encodestring(payload)
body = json.dumps({
            'content':b64payload,
            'name': 'test_post.py',
            'path': '/api/contents/',
            'format': 'base64',
            'type':'file'
        })
# getting the xsrf cookie
client` = requests.session()
client.get('http://192.168.99.100:8888/')
csrftoken` = client.cookies['_xsrf']
cookies = dict(client.cookies)
headers ={'Content-type': 'application/json', 'X-CSRFToken':csrftoken, Referer':'http://192.168.99.100:8888/api/contents', 'token':token}
response = requests.post(api_url, data=body, headers=headers, verify=True)
```
Error returned

> [W 12:22:36.710 NotebookApp] 403 POST /api/contents (192.168.99.1): XSRF cookie does not match POST argument
> [W 12:22:36.713 NotebookApp] 403 POST /api/contents (192.168.99.1) 4.17ms referer=http://192.168.99.100:8888/api/contents

**Comment by takluyver** [comment]
If I recall correctly, you can use the original token with every request and not need to handle cookies or xsrf tokens at all. This is intended precisely to make it easier to write code like this using the Jupyter API.

**Comment by SaintNazaire** [comment]
Actually I get an error message requiring the xsrf cookie when passing only the token as header :

Simplifying to the following (which works fine for requests.get) to post or put:

```
    headers ={'token': token} 
    response = requests.put(api_url, data=body, headers=headers, verify=True)
```
I get the following error:

> [I 15:23:24.255 NotebookApp] 302 GET /api/contents/test_post.py (192.168.99.1) 0.77ms
> [W 15:23:24.907 NotebookApp] 403 PUT /api/contents (192.168.99.1): '_xsrf' argument missing from POST
> [W 15:23:24.923 NotebookApp] 403 PUT /api/contents (192.168.99.1) 16.23ms referer=None

**Comment by takluyver** [comment]
If you pass the token as a header, the format it expects is like this:

```python
headers = {'Authorization': 'token ' + token}
```

Docs: http://jupyter-notebook.readthedocs.io/en/latest/security.html

**Comment by SaintNazaire** [comment]
Ahhh very nice thank you!
