### ISSUE TITLE
Notebook normalization for version control

### ISSUE THREAD

**Issue by akhmerov** [jupyter/help#174]
For a while we are using nbconvert with `ClearOutputPreprocessor` to make notebooks git-friendly. However I have observed that there are several cell and notebook metadata fields that are left intact by it. Looking at the latest `nbformat`, it appears that the following cell metadata doesn't belong to VC:
* `collapsed`
* `autoscroll`
* output metadata `isolated`

I cannot quite find the standard kernelspec json entries, but I remember that at the very least the minor language version was causing troubles sometimes.

Now to my question: what is the best way to strip the above metadata and is there anything available short of writing an own preprocessor?

**Comment by takluyver** [comment]
[nbdime](http://nbdime.readthedocs.io/en/latest/) can hide metadata changes, which may be some help. We also try to leave fields like those out of the metadata when they would have their default value, to minimise clutter in version control.

**Comment by akhmerov** [comment]
Yes, we use nbdime in our workflow, but I didn't realize that it can be used as a git filter; can it?

Would it be reasonable to remove output-related metadata when the corresponding output is removed?

**Comment by takluyver** [comment]
Possibly not as a filter, looks like it integrates with the diff and merge operations themselves:
http://nbdime.readthedocs.io/en/latest/vcs.html

Yes, I think metadata related to outputs should probably be cleared when the outputs are.

**Comment by akhmerov** [comment]
Without having a filter there's extra VCS noise generated.

> Yes, I think metadata related to outputs should probably be cleared when the outputs are.

Where shall I open the issue? Definitely nbconvert, but also the notebook UI doesn't clean the metadata on clearing output.

**Comment by takluyver** [comment]
I'd go for it on the notebook repo.

**Comment by rsvp** [comment]
In the meantime, is there a way to **clear output cells with just images?**
For example, lines containing `"image/png":` -- without losing trust state.

A major issue in committing notebooks in repositories is, of course, the size 
bulk introduced by images.

**Comment by takluyver** [comment]
I don't think there's anything ready-made to do that, but it should be pretty easy (~10 lines in Python) to load a notebook, filter out image outputs and write the result out.

**Comment by rsvp** [comment]
@takluyver I suppose the filter could be a *sed* one-liner, but 
the notebook will probably lose its trusted state, so which
non-interactive utilities did you have in mind?

**Comment by takluyver** [comment]
I wouldn't try to `sed` JSON. That's not going to be remotely reliable. i was thinking Python code, using the [nbformat library](http://nbformat.readthedocs.io/en/latest/api.html).

**Comment by akhmerov** [comment]
closing as answered

**Comment by minrk** [comment]
[nbstripout](https://github.com/kynan/nbstripout) provides git filters for notebooks for doing this kind of thing. If it doesn't cover these metadata keys, they can be added pretty easily. It may be appropriate to bring nbstripout's functionality into nbdime eventually if we want to have a single package providing "notebooks in version control" toolkit, but for now nbdime is only a renderer and merge tool.

**Comment by rsvp** [comment]
@minrk Thanks for your great suggestion. Does *nbstripout*
sign out in trusted state using nbformat.sign.NotebookNotary()

Re: stripping only images: kynan/nbstripout/#58
