### ISSUE TITLE
Magic or API to allow skipping of cells during run all?

### ISSUE THREAD

**Issue by BoPeng** [jupyter/help#175]
For reproducibility considerations, I usually rerun my notebook to make sure it executes correctly before I conclude an analysis. However, there are cases that I would like to ignore certain cells during re-execution, for example, cells that involves heavy computations or cells that produce different results each time.

I checked the [source code of run all](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L2369) and it appears that all cells are executed, and there seems to be no way to stop [execution of cell](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codecell.js#L306). Actually in my own [SoS kernel](https://github.com/vatlab/SOS/) I implemented a [`%skip` magic](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.py#L1892) but the magic clears the output of the skipped cells because the cells are actually executed and returned immediately.

So my question is: Is there a  way to mark cells to exclude them from run-all? Or, would you consider a patch that skips cells with certain metadata so that kernels and extensions can make use of it to skip cells?

**Comment by takluyver** [comment]
How about a cell tag? That should be easy to implement and work for all kernels.

**Comment by BoPeng** [comment]
Is cell tag simply an interface to cell metadata? Yes, it would be great have a tag for skipping a cell (`norun`, `skip` etc).

**Comment by takluyver** [comment]
Yep, metadata contains a list of tags, and there's a cell toolbar you can use to edit the tags on each cell.

We'd have to think a bit about the naming and the effects - would it only affect run all, or would trying to run that specific cell be ignored as well?

**Comment by BoPeng** [comment]
I did not notice the tag toolbar before, but now I get it. It is an interface for `metadata['tags']` and perhaps I should convert my own metadata to use this feature (I have a `show_output` metadata to show certain output in the exported HTML report).

Anyway, other than `Run All`, it is not uncommon for users to `Shift-Enter` through a notebook so I would suggest that we skip cells with this tag in all cases. Actually, if we have this feature, people can lock a notebook (tag all cells) so that the notebook cannot be accidentally changed, which was something that bothered me a lot and forced me to save a HTML copy of all notebooks.

**Comment by BoPeng** [comment]
As for a name for this tag, I would suggest `locked`, meaning the cell is locked and cannot be changed.

**Comment by technic** [comment]
You may want to look at [freeze](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/freeze) extension.

**Comment by BoPeng** [comment]
Great. This is exactly what I am looking for.

**Comment by stas00** [comment]
See also: https://github.com/ipython/ipython/issues/11582
