### ISSUE TITLE
I need to uninstall the hacks completely

### ISSUE THREAD

**Issue by ihackifyoudo** [jupyter/help#180]
Once I installed the hacks for the first time they seemed to be working perfectly. However once I shut down my computer and used the same config it acted differently. Now I can't see people through walls even when I have the necessary options checked . I wan't to completely remove everything related to AImTux on my Linux and reinstall it and see if it works properly again. Can I know the prcedure ? Thank you

**Comment by ihackifyoudo** [comment]
@ellisonbg

**Comment by minrk** [comment]
Maybe you are looking for [AimTux](https://github.com/AimTuxOfficial/AimTux)?
