### ISSUE TITLE
Q: Extend interactively support to rmagic cells

### ISSUE THREAD

**Issue by FirasSadiyah** [jupyter/help#183]
I recently discovered the option to use `c.InteractiveShell.ast_node_interactivity = 'all'` in `ipython_config.py` to run the nodes interactively. I found the feature very useful to avoid using print() to show the output of all expressions. The feature worked fine in the coding cells but did not work if the cell is set to use rmagic, i.e. %%R. 

Is there a way to extend the support of this feature to rmagic cells.

**Comment by takluyver** [comment]
Sorry, that setting is specific to handling Python code. The %%R magic is part of the [rpy2 project](https://rpy2.bitbucket.io/).

**Comment by FirasSadiyah** [comment]
No worries. Many thanks for your reply. I will try to post in the rpy2 project.
