### ISSUE TITLE
Setting up a simple home server for private use around the house

### ISSUE THREAD

**Issue by robwebbjr** [jupyter/help#191]
Hi.
I just want to have the jupyter server on my desktop machine and access it from my chromebook via my home wireless network when I'm in another room.
Do I need to install apache and encryption certificates, etc. just to be able to work from another room?
Thanks in advance.
P.S. Ubuntu 16.04 running Jupyter 5.0 accessing from a chromebook; regular home wireless setup.

**Comment by robwebbjr** [comment]
Got it.
Thanks to the community for providing adequate documentation.

**Comment by takluyver** [comment]
I think the answer is: if you're sufficiently confident in managing your network that you're sure you are only exposing the server to your local network, and that that network is only accessible to trusted devices (your computers don't have malware, etc.), then in theory it is OK to expose the notebook server on that network without encryption.

In practice, it's hard to guarantee those conditions, so it's usually a good idea to set up SSL if you're accessing it from any other computer than the one it runs on. That shouldn't need Apache, but it will require a certificate.

More info here: http://jupyter-notebook.readthedocs.io/en/stable/public_server.html
