### ISSUE TITLE
Install Juputer

### ISSUE THREAD

**Issue by hadi9320** [jupyter/help#199]
Hi, 
I am a new comer. I installed Python 3 in Linux Mint but when install Jupyter Notebook, I see this error at the end:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/wcwidth-0.1.7.dist-info'
How can I solve that? Could you help me step by step? 

Thanks so much.

**Comment by takluyver** [comment]
Closing in favour of #200.
