### ISSUE TITLE
Error when Install Jupyter Notebook

### ISSUE THREAD

**Issue by hadi9320** [jupyter/help#200]
Hi,
I am a new comer. I installed Python 3 in Linux Mint but when install Jupyter Notebook, I see this error at the end:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/wcwidth-0.1.7.dist-info'
How can I solve that? Could you help me step by step?

Thanks so much.

**Comment by takluyver** [comment]
It looks like you've done `pip install jupyter` or similar. You can either:

- Do a user install with `pip install --user jupyter`
- Create a virtualenv or conda env to install Jupyter in. I won't give instructions here, but there are plenty if you want to search online.

**Comment by katrinsharp** [comment]
`pip install --user jupyter` works like a charm. Thanks.

**Comment by kalyanghosh** [comment]
Run the command:
$ pip install --user jupyter
