### ISSUE TITLE
Error in "Head" unix command in Jupyter Notebook

### ISSUE THREAD

**Issue by firdos4u** [jupyter/help#201]
While running unix command Head in Jupyter notebook, 

`% head -n 3 $filename`

I am getting below error:
ERROR:root:Line magic function `%head` not found.

![image](https://user-images.githubusercontent.com/31029563/29305051-d37e0a06-8129-11e7-899f-45772d82d27a.png)

**Comment by takluyver** [comment]
To run a system command, start the line with `!` rather than `%`.

`%magic` is a special command inside IPython, while `!system` runs a system command. Some common system commands like `ls` have a magic alias for convenience, but I don't think `head` is one of them.

**Comment by firdos4u** [comment]
!head is giving another error -
'head' is not recognized as an internal or external command,
operable program or batch file.


![image](https://user-images.githubusercontent.com/31029563/29328372-aa7257d2-8185-11e7-9aa5-a5126ae0640c.png)

**Comment by denisBK** [comment]
I'm having the same problem here. Have you found a solution? Thanks!

**Comment by takluyver** [comment]
I think the "not recognized as an internal or external command" error is a Windows error.

`!command` works for system commands. If you're on Windows, those are Windows commands. If you're on a Unix platform (like Linux or Mac), they're Unix commands.

**Comment by PriSawant7** [comment]
so what is the command for windows?

**Comment by takluyver** [comment]
For head? I don't think Windows has an equivalent command. You can do the same with Python code, though. Something like this:

```python
with open('file.txt') as f:
    for _ in range(10):
        print(f.readline())
```

**Comment by PriSawant7** [comment]
i tried this and it worked......
%alias head powershell -command "& {Get-Content %s -Head 30}"
%head car1.csv

**Comment by takluyver** [comment]
Neat solution :-)
