### ISSUE TITLE
How to customize individual notebooks by a configuration file

### ISSUE THREAD

**Issue by p2ya** [jupyter/help#209]
I need to setup configuration file for individual instances of notebooks to grab some meta data and select desired modules to be included in the notebook.
This should also include user access information.
Is there any available solution to do this ?

**Comment by minrk** [comment]
Not in an officially supported capacity where it is loaded automatically, no. To accomplish configuration outside the notebook, you could include code to load configuration in the notebook itself, thus creating a dependency on the additional config file. One such way to do it would be to have a `config.py` and run it in your first cell with:

```python
%run config.py
```

and then have potentially multiple configuration files, where each notebook loads the appropriate configuration file in its first cell.

**Comment by p2ya** [comment]
Hey Min,
That worked nicely, heaps thank.

**Comment by chavellacinema160** [comment]
That isn't me.cant you tell when some else overlaps screen
