### ISSUE TITLE
Cannot Launch Jupyter Notebook from Terminal on OSX 10.12.2

### ISSUE THREAD

**Issue by frank-lzh** [jupyter/help#215]
Hi, I install jupyter notebook through "pip3 install jupyter". The installation succeeds, and when I use pip3 show jupyter to check the status, the message is as below:

_Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: ipykernel, jupyter-console, qtconsole, nbconvert, ipywidgets, notebook_

Then I enter the folder as showed in the "Location", and I do found some folders related to jupyter, but when I try to execute the command "jupyter notebook", the message is "fish: Unknown command 'jupyter'". I have tried to switch to bash, which doesn't help.

**Comment by takluyver** [comment]
Check the `$PATH` environment variable. It should include a directory ending in `.../bin` which contains a file called `jupyter` (among many others). If it doesn't, you'll need to find that directory and add it to $PATH.

**Comment by frank-lzh** [comment]
I found the .../bin directory in /Library/Frameworks/Python.framework/Versions/3.6/bin. Thanks for your suggestion!
