### ISSUE TITLE
Batch execution of notebooks with arguments passed by nbconvert

### ISSUE THREAD

**Issue by khourhin** [jupyter/help#218]
Hi,

Jupyter is great and I would like to use it to produce automatic reports. The idea would be to have a classical data analysis in a single notebook and produce pdfs/htmls reports of this analysis with different inputs. Something which would allow you to do:
`jupyter nbconvert --to html dataAnalysis.ipynb **--var data1.csv** --execute`

The executed notebook, either in R or Python (or other languages) would have the variable **var** set to "data1.csv" and will execute the whole analysis and generate the report based on this specific dataset. This would allow high throughput reports generation with:
`for i in *.csv; do jupyter nbconvert --to html dataAnalysis.ipynb --var $i --output ${i%.*csv}.html --execute; done`

 I looked for a built-in solution for quite a while, and I found none.

On the way I found some information:
https://stackoverflow.com/questions/30080715/batch-execute-ipython-notebook-with-command-line-argument
https://stackoverflow.com/questions/37534440/passing-command-line-arguments-to-argv-in-jupyter-ipython-notebook
https://stackoverflow.com/questions/43057529/how-to-pass-command-line-arguments-in-ipython-jupyter-notebook

libraries/solutions:
https://gist.github.com/gbishop/acf40b86a9bca2d571fa
https://github.com/takluyver/nbparameterise
https://github.com/paulgb/runipy
https://github.com/omar-masmoudi/jupyter-runner
https://github.com/nteract/papermill

So it seems there is a lot of interest in this feature and quite some libraries are addressing it. I tried as well to pass variables through the environment, but it is indeed cumbersome. And it would be nice to have a single implementation for all the programing languages. 

I was wondering if there was a plan to provide built-in functionalities for this feature and/or if you could provide me some advices on which tool would be best to use.

Thanks a lot !

**Comment by takluyver** [comment]
* Advice: Of the solutions you list, I like nbparameterise (which I wrote, so I'm biased) and papermill (by the nteract team, who probably maintain it better than nbparameterise). I think their approach of replacing variables uses the idea of notebooks better than setting environment variables like jupyter-runner.
* Built-in functionality: We don't plan to do that, as far as i know. We're keen on having an ecosystem of tools maintained by different people, and I don't see any problem with this not being an official Jupyter project. If we did decide to, I imagine we'd just adopt one of nbparameterise or papermill.
* Multi-language: Nbparameterise is designed to allow this, but so far only the Python backend has been written. It's a contribution opportunity ;-) It looks like Papermill can also work with different languages (it mentions an R binding), but it's not quite clear what that involves.

Thanks for the links - I hadn't seen Papermill before.

**Comment by takluyver** [comment]
Doing a bit of code reading on Papermill, it looks like the main differences between that and nbparameterise are:

- Papermill has some extra features around storing data in notebooks and collecting data from groups of notebooks. Nbparameterise just deals with parameterising a notebook.
- Nbparameterise can extract the parameter names, current values and types from the notebook code. As far as I can tell, Papermill can only overwrite the parameter cell with new code, so it can't make an input form or verify that parameter names are correct.
- Papermill can use any cell tagged `parameters`, whereas Nbparameterise always uses the first code cell.

cc @willingc @ewmassey

**Comment by willingc** [comment]
> It looks like Papermill can also work with different languages (it mentions an R binding), but it's not quite clear what that involves.

For R, there is a project called papermillr in the nteract repo.

Nbparameterise and papermill are both quality code created by folks that understand Jupyter internals. Feel free to try out papermill and reach out if you have questions.

cc @rgbkrk @mpacer

**Comment by rgbkrk** [comment]
The way to use papermill for batch execution is to treat it as a library for running with parameters, either in Python or at the command line. We _almost_ baked job running into papermill, then began to realize that how people do orchestration and scheduling can differ greatly.

Here's an example parameter sweep on a single machine, no threadpool:

```
run = 0

# Quick and dirty sweep
for x in range(3):
    for y in range(3):
        run = run + 1
        pm.execute_notebook(
            'template.ipynb',
            'out-{}.ipynb'.format(run),
            parameters={"x": x, "y": y}
        )
```

Whereas, if you're doing it with a threadpool it might look like this:

```python
futures = []
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    run = 0

    # Quick and dirty sweep
    for x in range(3):
        for y in range(3):
            run = run + 1
            future = executor.submit(
                pm.execute_notebook, 'template.ipynb', 'tp-out-{}.ipynb'.format(run), parameters={"x": x, "y": y}
            )
            futures.append(future)
```

The way that my colleagues at Netflix are using this is running the individual notebooks as jobs within our Docker cluster, where papermill is installed within the container. We give them some utility functions around this.

**Comment by khourhin** [comment]
Thanks to all of you for the info, suggestions and help ! I'll look into this soon.
