### ISSUE TITLE
Cursor initial position in header MD cells

### ISSUE THREAD

**Issue by andportnoy** [jupyter/help#22]
Hi all. 

When I create a Markdown cell in a Jupyter notebook and decide to format it as a header, this inserts 1–6 pound key symbols (as it should). To edit the cell, I press Enter, and the cursor is positioned at the very left of the cell, before the `#` symbols. 

Wouldn't it be more practical to automatically put the cursor right _after_ the `#` symbols (possibly separated by a blankspace), when editing? 

Thank you.

**Comment by willingc** [comment]
Hi @andportnoy, 

Thanks for the user interface suggestion. I'll label this suggestion as something for those working on the user interface to consider when cells are edited.

Thanks! :cookie:

**Comment by andportnoy** [comment]
Awesome, thank you.

**Comment by Carreau** [comment]
That's likely doable, we would have to define the semantics of when to move the cursor at eh end of the pounds symbols, like if you already have a h4+title and make it a h3, do we still move the cursor. 

But it should be doable.

**Comment by andportnoy** [comment]
Yeah, I really like the speed that comes with using the keyboard shortcuts, and having to use the arrow keys or the mouse to move the cursor is a bottleneck.

**Comment by willingc** [comment]
@andportnoy, thanks for the suggestion to improve user experience.

I'm closing this support issue as triaged. I have tagged the good suggestion as a "User suggested feature" and added it to the "Reference" milestone which the development team monitors for future project enhancements and features.
