### ISSUE TITLE
Can't connect to kernel when hosted on aws instance

### ISSUE THREAD

**Issue by js1972** [jupyter/help#23]
I have installed Jupyter via anaconda on an aws Ubuntu instance. I have the appropriate 433,8888 ports open for access over https from my browser and I can connect and create, save notebooks just fine. However it can never execute a cell as it can connect to the kernel...
What am I missing - is there additional ports that need to be opened for the kernel comms??

I've read that it could be an issue with Safari and self-signed certs but I get the same issue in chrome as well. 
It's probably somethings basic but has got me stumped!

**Comment by js1972** [comment]
"Can not" connect to the kernel that should say above!!! Damn iPhone!!

**Comment by minrk** [comment]
There are not additional ports, but websockets must be allowed to connect. There are various things that can get in the way, and old or misconfigured proxies are the most common. Is there any layer in between the port and the outside world?

**Comment by js1972** [comment]
Not that I know of.... I'm trying to connect from home so there's no silly
corporate proxy in the way....
I haven't had trouble exposing web services with node on ports like 8080
and so on so can't see why the AWS setup would be blocking it unless there
were other required ports... Mystery. ;-)

**Comment by js1972** [comment]
Well I just tried connection to my notebook server on AWS from a desktop browser and it works perfectly.. Looks like its some issue with the iOS browsers not allowing a connection with a self-signed certificate (https). I also tested that it works fine with just http.

**Comment by minrk** [comment]
Sorry, should have thought of that. Yes, Safari (on which all iOS browsers are based) refuses to establish websocket connections to untrusted certs. This is a longstanding issue, not sure if it's a bug or weird intended behavior. [Let's encrypt](https://letsencrypt.org) is making free SSL certs significantly more available, so there should be fewer cases that need self-signed certs.

**Comment by js1972** [comment]
I tried letsencrypt but it's a pain in the arse. Difficult to install so managed it within a docker container. But then it won't let you create a certificate to an Amazon elastic ip. Something about the domain name that it doesn't like and this is not worth registering a proper domain for... It won't create cents to IP address either (which is understandable).

I did however work out how to get the self-signed certificate to work on iOS. You can email it to yourself and tap on the email on the key file in the email (in iOS mail) and it will install it into an iOS profile.
With that I can now access my Jupyter notebook server and the kernel works perfectly!!
Yeehaaa and what a learning experience - taken about 4 hours that I'll never get back....   ;-)

Note: On a Mac the kernel could not be accessed at all via Safari but works perfectly in Chrome. I'm sure there is a way to install the self-signed certain the keychain but I can't be bothered figuring it out.

**Comment by willingc** [comment]
Thanks @js1972 for the update and outlining your steps.

@minrk I'm going to add this issue to the Reference milestone as a flag for potential future documentation.

**Comment by Sandy4321** [comment]
link  https://www.youtube.com/watch?v=q4PrYQOShnE  2:20 suggests to add https port and and custom tsp rule 
so I can use ipython from amazon AWs computer but only for 3 minutes, and then sessoin is closed aoutomatically, pls help to solve this probem with automatical closeing after short time to work. I use MAC

**Comment by Jim-Knoll** [comment]
My jupyter was not 'public' but I still had the same kernel issue.   Turned out it was the aws LB I was using.   Needed to pass tcp port not just the http port..   My server was on 8080 and we lb that to port 80.   Due to ws websockets I needed to insure that all ws header would be delivered and not just http.    

ya that was fun.

**Comment by JoeCodeswell** [comment]
When i try to execute a cell, I get "a connection to the notebook server could not be established", on  https://jups.joecodeswell.org. This site is mine hosted by WebFaction. It DID work in the past when it was

- NOT SSL secured
- Not password protected

Attachment01.txt is some info from the nohup.out file.

"Replacing stale connection" seems to be a hint of what is wrong.

Thanks for the help in advance.

Love and peace,

Joe
[Attachment01.txt](https://github.com/jupyter/help/files/604431/Attachment01.txt)



`

**Comment by Ujjwal-9** [comment]
even ssh tunneling helps, just run the following command on your local terminal after starting jupyter notebook on aws instance on port 8888
```
ssh -i /path/to/your/AWS/key/file -NL 8157:localhost:8888 user@host
````

**Comment by dominicneeraj** [comment]
As my internet is behind a proxy server and its blocking WebSockets, what is suggested to run my Jupyter notebook?

**Comment by takluyver** [comment]
If you're running it locally, configure your proxy settings not to use the proxy for `localhost` or `127.0.0.1`.
