### ISSUE TITLE
Can Someone Please Help Me?

### ISSUE THREAD

**Issue by lguast007** [jupyter/help#234]
I'm trying to build a fun, short quiz for a website's blog(I'm an intern). I know nothing about coding, but I got a quiz put together and it looks ok. Except, now the pages are not linked within github. PLEASE.HELP.ME. Ive spent a whole week on this stupid thing.

**Comment by Carreau** [comment]
Hi there, 

Is your project related to Jupyter, and do you have a bit more information about it. From your description it is hard to know what is going wrong.

**Comment by lguast007** [comment]
Hey Carreau,

It's not.. I thought this was just a general help section! I'm sorry! But the issue is having my "index.html" (the first opening page, its own html gist page) linking to the "QuizTest.html"(the start of the quiz, on its own gist page). The QuizTest.html links fine with the result pages (also separate html code). I'm not sure why the index.html will not link to the quiztest.html. I get the 404 error page.
If you wouldn't mind, I appreciate any help!

**Comment by Carreau** [comment]
You need to be extra careful about the syntax:

```
<form ... action="https://lguast007.github.io/lguast007.github.io/QuizTest.html>
```

You have two mistakes in this link:

1) you have `lguast007.github.io` twice, 
2) you forgot a closing double quote after `.html` (computers are picky)

You can see that  by clicking on "test the quiz" and see the following in the URL.
<img width="893" alt="screen shot 2017-10-24 at 15 51 49" src="https://user-images.githubusercontent.com/335567/31972005-5c4cb662-b8d3-11e7-8e8d-0ca1ba5fa750.png">

You'll learn in time that there are a number of tool to help you find that out automatically.

You're lucky I knew [where to look for these files](lguast007.github.io), in general you want to give links to the work you did and describe what you tried. You should also try to find help in relevant forums (not sure how you ended up here). You are probably learning this in a specific context that might have people better suited to help you. If you are an intern, then you likely have a mentor, or should have. If you don't you should ask for one.

I'm going to close the issue (but you can still comment!) as is is not related to Jupyter. 

Congrats for getting stated on GitHub and learning Html/Css and web programming. Don't get discouraged, learning programming can sometime looks daunting. You will both have good and bad interaction on the web, do not let the discouraging interaction influence you, and find a community where you have your place.

Thanks,

**Comment by lguast007** [comment]
Thank you so much! I've never coded anything before, so its extremely daunting, but I'm excited for the challenge. Thank you for taking the time to explain all of that to me! I really appreciate it!

Cheers!
