### ISSUE TITLE
Path of current working dir in notebook on Windows 7 64b with winpython 3.6

### ISSUE THREAD

**Issue by theoky** [jupyter/help#236]
I have setup winpython 3.6.1 on a win 7 64bit machine with ipython (6.2.1) and jupyter-core (4.3.0) in the following path: `C:\apps\WinPython-64bit-3.6.1.0Qt5`

My notebooks are stored in `C:\...\synched\Python\notebooks3x` which is also defined as `c.ContentsManager.root_dir`in the file `jupyter_notebook_config.py`.
The content of this path is also synched with other computers, where the path is not necessarily identical. 

When I start the notebook server, all notebooks in the directory are listed and I can use them.

Now I'm planning on having some local python files in the notebook-directory, and as far as I understand, I can import them from the current dir.

Unfortunately, entering this in a cell of a new notebook
```python
import os
os.getcwd()
```
yields `'C:\\apps\\WinPython-64bit-3.6.1.0Qt5\\notebooks'`, which is not the path of the notebooks specified in `root_dir`, as I expected.

When doing the same from an ipython-Shell I get `C:\\...\\synched\\Python\\notebooks3x`, so that's why I think this has something to do with jupyter.
*edit:* although in retrospect this probably was an artifact of some other operation... */edit*

What I tried:
* modifying the shortcut of the notebook launcher with the directory of the notebooks as working dir: 
* starting the notebook server from the notebook directory

Nothing changed the current dir. Changing to the path hardcoded in a notebook cell is not an option as the path may vary on the different synched machines.

Even the file `nbserver-[pid].json` in `C:\apps\WinPython-64bit-3.6.1.0Qt5\settings\runtime` contains
```json
   "notebook_dir": "C:\\apps\\WinPython-64bit-3.6.1.0Qt5\\notebooks",
 ```
  	
My questions are:
* Is there a way to get the initial working directory to be the notebook directory specified in c.ContentsManager.root_dir?
* Is there another way to get the current dir to be set on the notebook dir?
* What did I miss?

My current workaround for getting the python import to work is to add a file to `C:\apps\WinPython-64bit-3.6.1.0Qt5\settings\.ipython\profile_default\startup` 
which modifies the `sys.path` with
`sys.path.append('C:\\...\\synched\\Python\\notebooks3x')`

This file needs obviously to be different for each synched machine.

I hope this is the right place for these questions.

**Comment by minrk** [comment]
I think what you want is

```python
c.NotebookApp.notebook_dir = "..."
```

instead of `ContentsManager.root_dir`. Setting root_dir directly is typically for special circumstances where your notebook files and your kernels shouldn't have the same base directory (e.g. kernels and files do not reside on the same filesystem).

**Comment by theoky** [comment]
I knew I missed something.
Thanks, that fixed my problem.
