### ISSUE TITLE
Syntax highlighting doesn't recognize the "@" now used for NumPy matrix multiplication.

### ISSUE THREAD

**Issue by josephcslater** [jupyter/help#24]
Using the `@`  symbol changes the color of everything subsequent to the same color as the `@`  (which is purple for me). I'm not sure if making the syntax highlighting local would change something else where  `@`  is used, but in math, this makes for some odd highlighting. 

Example attached. 

![temp](https://cloud.githubusercontent.com/assets/12815335/14469511/fdcfbc1c-00b2-11e6-98c0-369982590278.png)

**Comment by willingc** [comment]
Hi @josephcslater,
The syntax highlighting may be something that is already configurable. Pinging @carreau @jdfreder for the best solution on this: config file, extension or ?.
Thanks :sunny:

**Comment by Carreau** [comment]
[Codemirror](http://codemirror.net/mode/python/index.html) has been updated to support PEP 465  syntax wiht `@` as a binary operator, but apparently not correctly. Will open a bug upstream.

**Comment by Carreau** [comment]
Upstream bug: https://github.com/codemirror/CodeMirror/issues/3957

**Comment by willingc** [comment]
Thanks @Carreau.

I'm closing this issue while it is pending upstream activity. I have labeled this issue upstream with a milestone of **Review monthly** as a reminder for the developer team to review upstream issue status.

Thanks @josephcslater for sharing this with us.

**Comment by josephcslater** [comment]
My pleasure, and my appreciate for the work that you do.

**Comment by janschulz** [comment]
@willingc Maybe add the the review item as a `* [ ] ...` task to the first message in this issue so that it can be reviewed more easily?

**Comment by Carreau** [comment]
https://github.com/codemirror/CodeMirror/pull/3973 should take care of that (if accepted).

**Comment by willingc** [comment]
Thanks @carreau for linking to the PR. I went ahead and added @janschulz' suggestion as well. Redundancy FTW :wink:
