### ISSUE TITLE
Add reStructuredText support for notebooks

### ISSUE THREAD

**Issue by JakobJakobson** [jupyter/help#241]
Dear developers,

Could you add reStructuredText support for the jupyter notebooks?

Regards

Jakob

**Comment by takluyver** [comment]
We considered this when the notebook was started, but we have no plans to do it at the moment. rST is designed to be processed as a whole document, or even a collection of documents. This doesn't work well with the interactive notebook where you're editing and re-rendering cells individually. Markdown fits nicely with this mode of operation.

**Comment by akaihola** [comment]
As a work-around for the simplest use cases, try this in a notebook:
```python
import docutils.core
import docutils.writers.html5_polyglot
from IPython.core.magic import register_cell_magic
from IPython.display import HTML

@register_cell_magic
def rst(line, cell):
    "Render ReStructuredText"
    writer = docutils.writers.html5_polyglot.Writer()
    return HTML(docutils.core.publish_string(cell, writer=writer).decode('UTF-8'))
```
```rst
%%rst
============
 Main title
============

Some **heavy** markup.
```

The downside is that you see both the ReStructuredText source and the rendered output.
