### ISSUE TITLE
code syntax highliting not working

### ISSUE THREAD

**Issue by dst47** [jupyter/help#243]
I wrote a custom kernel. but syntax highlight and auto indent features not working. I tried with
calling auto_highlight() function for each cell. But no luck. Could you please give me any instruction for this ?

**Comment by takluyver** [comment]
If there's a [Codemirror mode](http://codemirror.net/mode/) available for your language, all you should need to do is specify the necessary metadata in the [kernel info reply](http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-info) message to point to it. If your kernel is written as a Python 'wrapper' kernel, you can do this with [attributes on the kernel class](http://jupyter-client.readthedocs.io/en/latest/wrapperkernels.html#MyKernel.language_info). You shouldn't need any Javascript for this.

If your kernel does not have a Codemirror mode, you'll need to define one. I think some existing kernels have examples of this, but I forget which.

**Comment by dst47** [comment]
Hi takluyver, your instructions worked. Thanks a lot.
