### ISSUE TITLE
Markdown on Github

### ISSUE THREAD

**Issue by primitiveDataType** [jupyter/help#25]
Hello!

Text within Markdown` <center> `tags in a .ipynb file are not displaying when uploaded to Github. See how the title seems to be missing on my Introduction.ipynb file: (https://github.com/primitiveDataType/PolyratingsDataScience/blob/master/Introduction.ipynb)
I have verified that the text is present within the center tags in the raw code.

Thanks!

**Comment by Carreau** [comment]
GitHub has a stricter policy on what can be included for security reason, it will likely be rendered on nbviewer.  You will need to contact GitHub for more info, we have no power of what GitHub renders.

Also  `<center>`, is not a valid html5 tag.

Finaly,  I believed that if used, it should be used outside of headers, and not inside, and will render if browsers supports it.
