### ISSUE TITLE
Creating a Custom Environment

### ISSUE THREAD

**Issue by jonathanrobie** [jupyter/help#258]
I would like to set up a custom environment to allow people to write Jupyter notebooks that query Greek syntax trees using XQuery / XPath together with Python or R.  This environment would run XQuery / XPath on a BaseX server running on the Web (or perhaps in a Docker image).

This illustrates the kind of thing I want to do, except that I would like to spare users the part found in the first section, "Opening the Database, Defining some Functions":

http://jonathanrobie.biblicalhumanities.org/assets/friendlier.html

I have been using Jupyter for only a few weeks, and I do not yet have a solid grasp of the architecture.  I assume what I describe above is possible?  How would you go about doing it?

**Comment by takluyver** [comment]
It depends a bit who you want to make this available to.

One relatively straightforward option is to make a Python package with the functions and the database connection you want. That could be a file alongside the notebooks, or a package installable with `pip`. You can't get rid of the setup in the notebook entirely, but you can condense it to one line like:

```python
from greeksyntax import *
```

A more involved way is to make a Jupyter kernel. That's normally done for supporting a different programming language, but there's no reason it couldn't be for a 'dialect' of Python that has some things predefined. This can completely eliminate the setup code, but it's more complex for you, and users would have to install your kernel in addition to Jupyter.

If the people are in an environment you control (e.g. students using a JupyterHub deployment you run), you can put these commands in a startup file, so they are run each time the user starts a notebook.

**Comment by jonathanrobie** [comment]
Thanks - since I'm distributing these notebooks along with the data and the stylesheets, a package distributed with the notebooks seems like the most straightforward way to go.  And the simplest, so I'll try that first, and move to something else if I need to.

**Comment by jonathanrobie** [comment]
I implemented this and have been using it happily.  You can read about it here:

[Exploring Greek Syntax with Jupyter Notebooks](http://jonathanrobie.biblicalhumanities.org/blog/2017/12/08/jupyter-tutorial/)

**Comment by takluyver** [comment]
Excellent, nice one :-)
