### ISSUE TITLE
notebook出现404和302错误

### ISSUE THREAD

**Issue by Ontheroad123** [jupyter/help#259]
在Notebook上运行这段代码
import numpy as np
import matplotlib.pyplot as plt
from testCases import *
import sklearn
import sklearn.datasets
import sklearn.linear_model
from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets
from numpy import random

%matplotlib inline

np.random.seed(1)

X, Y = load_planar_dataset()

plt.scatter(X[0, :], X[1, :], c=Y, s=40, cmap=plt.cm .Spectral)
报错，图画不出来，导致后面的工作无法继续，错误提示：
ypeError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py in to_rgba(c, alpha)
    131     try:
--> 132         rgba = _colors_full_map.cache[c, alpha]
    133     except (KeyError, TypeError):  # Not in cache, or unhashable.

TypeError: unhashable type: 'numpy.ndarray'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4049                 # must be acceptable as PathCollection facecolors
-> 4050                 colors = mcolors.to_rgba_array(c)
   4051             except ValueError:

~/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py in to_rgba_array(c, alpha)
    232     for i, cc in enumerate(c):
--> 233         result[i] = to_rgba(cc, alpha)
    234     return result

~/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py in to_rgba(c, alpha)
    133     except (KeyError, TypeError):  # Not in cache, or unhashable.
--> 134         rgba = _to_rgba_no_colorcycle(c, alpha)
    135         try:

~/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py in _to_rgba_no_colorcycle(c, alpha)
    188     if len(c) not in [3, 4]:
--> 189         raise ValueError("RGBA sequence should have length 3 or 4")
    190     if len(c) == 3 and alpha is None:

ValueError: RGBA sequence should have length 3 or 4

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-d3c6708dd697> in <module>()
      1 # Visualize the data:
----> 2 plt.scatter(X[0, :], X[1, :], c=Y, s=40, cmap=plt.cm .Spectral)

~/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py in scatter(x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, hold, data, **kwargs)
   3355                          vmin=vmin, vmax=vmax, alpha=alpha,
   3356                          linewidths=linewidths, verts=verts,
-> 3357                          edgecolors=edgecolors, data=data, **kwargs)
   3358     finally:
   3359         ax._hold = washold

~/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1708                     warnings.warn(msg % (label_namer, func.__name__),
   1709                                   RuntimeWarning, stacklevel=2)
-> 1710             return func(ax, *args, **kwargs)
   1711         pre_doc = inner.__doc__
   1712         if pre_doc is None:

~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4053                 msg = ("c of shape {0} not acceptable as a color sequence "
   4054                        "for x with size {1}, y with size {2}")
-> 4055                 raise ValueError(msg.format(c.shape, x.size, y.size))
   4056         else:
   4057             colors = None  # use cmap, norm after collection is created

ValueError: c of shape (1, 400) not acceptable as a color sequence for x with size 400, y with size 400

排除是初始化矩阵的错误，matplotlib也更新了，不知道该怎么解决了
这是终端上显示的：
[W 15:40:08.602 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20171205152529 (127.0.0.1) 3.72ms referer=http://localhost:8889/notebooks/%E6%A1%8C%E9%9D%A2/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99/%E7%AC%AC%E4%B8%80%E8%AF%BE%E7%AC%AC%E4%B8%89%E5%91%A8/assignment3/assignment3.ipynb

**Comment by Ontheroad123** [comment]
The solution:
plt.scatter(X[0, :], X[1, :], c=Y.reshape(X[0,:].shape), s=40, cmap=plt.cm .Spectral)

**Comment by takluyver** [comment]
Thanks for posting the solution yourself.
