### ISSUE TITLE
Is it possible to add something to indicate the server isn't running on the notebook dashboard?

### ISSUE THREAD

**Issue by roomthily** [jupyter/help#26]
(Apologies I can't provide details on when the server failed re: windows and versions etc or simply user error) but, assuming the dashboard hasn't been refreshed, could some error notification be added to the browser to indicate the server is no longer available? The errors when trying to do something like create a new notebook are not super informative ("error") and for people interacting with it from a launcher like Anaconda's Navigator, the CLI is not an obvious signal.

Or even just change the error message when making a new notebook when it's in that state to something more legible and actionable than "error"? 

It came up during a training course with some frustrated students looking at an interface that looked fine but was no longer active.

Cheers.

**Comment by Carreau** [comment]
Good idea, we should be able to replace the list of file by "something wrong".
But knowing what is wrong, is likely hard. It could be error to connect, wifi-down, timeout...

**Comment by willingc** [comment]
Thanks @roomthily for the suggestion to improve user experience.

I'm closing this support issue as triaged. I have tagged the good suggestion as a "User suggested feature" and added it to the "Reference" milestone which the development team monitors for future project enhancements and features.
