### ISSUE TITLE
How to run IPython by default?

### ISSUE THREAD

**Issue by BorisHollas** [jupyter/help#260]
I've installed Jupyter via pip on Ubuntu. When I run
`jupyter notebook`
a file browser appears in my web browser. To start an interactive console for computing and plotting, I click New -> Python 3.
Is this the right way to start the notebook formerly known as IPython? What command or configuration do I need to start IPython right away?
Also, Jupyter creates lots of ipynb-Files in my ~. How do I prevent Jupyter from littering my home directory?

**Comment by takluyver** [comment]
Yes, that's the right way to start the notebook. The ipynb files are your saved notebooks. It will save them in the directory you launch the notebook in.

It sounds like you might want a console interface rather than a notebook. IPython still exists, and you can get it by running `ipython`.

**Comment by BorisHollas** [comment]
No, I don't want a console interface, I want graphical output for function plots. I want to start the IPython notebook without having to click New -> Python 3 and I don't want Jupyter to create lots of ipynb-files in my home.

**Comment by takluyver** [comment]
You can put the files somewhere else by using `cd` ing to another folder before you launch it, Or you can set a different notebook directory in the config file. But notebook files go with using the notebook interface. 

If you really want to launch the notebook interface directly, you can install [nbopen](https://pypi.python.org/pypi/nbopen) and run `nbopen --new some_filename.ipynb`. But that will obviously create .ipynb files.

You can have a console with graphical output - that's the [qtconsole](https://github.com/jupyter/qtconsole#jupyter-qt-console).

**Comment by BorisHollas** [comment]
Thanks, nbopen does what I want.
