### ISSUE TITLE
Setting up a public notebook environment

### ISSUE THREAD

**Issue by jonathanrobie** [jupyter/help#267]
I have written some tutorials for using Jupyter Notebooks with Greek syntax using a Python package I wrote - thanks, @takluyver for your help in issue #258!

Here are some sample notebooks:

- [Tutorial: Greek Syntax Queries using Lowfat and Jupyter Notebooks](http://jonathanrobie.github.io/assets/greeksyntax-tutorial.html)
- [Tutorial: Greek Syntax Queries using PROIEL and Jupyter Notebooks](http://jonathanrobie.biblicalhumanities.org/assets/greeksyntax-tutorial-proiel.html)
- [Split Constituents](http://jonathanrobie.biblicalhumanities.org/assets/SplitConstituents.html)

Now I want to make it easy for other digital humanists who work with biblical Greek - I want to set up a notebook environment like [https://try.jupyter.org/](https://try.jupyter.org/) that uses a database server - probably located on the same machine for efficiency.

And I want to make it really easy for people to share notebooks with each other in this environment, creating new notebooks in their own subdirectories, etc.

Where do I get started learning how to do this?  Are there environments like what I describe online that allow people to save and share their notebooks?  What security concerns should I have?  What other concerns should I have?

**Comment by takluyver** [comment]
Hi Jonathan :-)

In general, https://mybinder.org/ is a nice way to share notebooks - you make a Github repository with the notebooks and a specification of the environment it needs. Binder builds that environment in the cloud and lets you run the notebooks.

Depending on the nature of your database, that may or may not be practical - I don't know if there's any size limit on the docker containers built for Binder. If you can't use Binder, you can set up a demo server similar to try.jupyter.org using JupyterHub. I've recently done this for some software at my university, and the deployment machinery for that is here: https://github.com/joommf/try-joommf-deploy (try.jupyter.org itself uses a different codebase, called tmpnb, but that's probably going to be retired).

**Comment by jonathanrobie** [comment]
Excellent!  Thanks!  I need to finish building the environment out first, so it may be early January before I actually do this.  I will close the issue now and reopen if I hit snags.
