### ISSUE TITLE
How can I get the path of the folder Jupyter Notebook was started?

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/help#269]
Hi,

I would like to know how to get the current folder (via Python code) Jupyter was started. I need to know this folder in order to read the saved notebook files and modify some information.

Thanks

**Comment by orobsonpires** [comment]
Maybe was not really clear in my question, so my approach is that I have a server extension and from there I would like to get the root_dir where I have all my notebook files. I have tried the following:
server_cm = ConfigManager(config_dir=jupyter_config_dir())
cfg = server_cm.get('jupyter_notebook_config')

However, I get always an empty object instead of my jupyter_notebook_config

**Comment by takluyver** [comment]
Your extension can define a function which the server will call when it loads it. You can use that to get the root directory from which the server can access files:

```python
def load_jupyter_server_extension(app)
    app.notebook_dir  # Path to the root directory of the server
```

**Comment by orobsonpires** [comment]
Thanks!!
