### ISSUE TITLE
Full Jupyter Directory

### ISSUE THREAD

**Issue by christiankur** [jupyter/help#27]
Hey everyone, I am a beginner in using Jupyter. I have actually the problem that my directory is overloaded. I have about 3.000 folders and files. The browser is crashing becaus of the big number. I uninstalled and installed it again. But the files are already there. If I try to delete it the message appears that I have not the permission.

Thanks for your help!

**Comment by Carreau** [comment]
Hi @christiankur I believe you already asked the question on the Mailing list and [got a response asking for more informations](https://groups.google.com/d/msg/jupyter/TMM64ziUisg/D-tinbrRAQAJ), can you provide more informations as asked  ?

Thanks.

**Comment by christiankur** [comment]
Hey Carreau,

ah ok - now I see the answer. I thought my question had be deleted. 
Attached there is a picture of it - maybe it is right that the notebook starts in a wrong directory?

![jupyter](https://cloud.githubusercontent.com/assets/18462072/14526930/e304a9fc-0246-11e6-9466-f2f3ddd9adb0.png)

**Comment by Carreau** [comment]
Yes, you seem to be starting the notebook from `%SYSTEMROOT%\System32` or equivalent, and all the  file you see there are necessary for windows to work (hence you do not have the permission to remove them, or your computer will likely not boot, which I guess you would prefer not happen), try starting the notebook in your home directory, by using the `--notebook-dir=` flag.

**Comment by takluyver** [comment]
Or, in the command prompt, use `cd` to change to your user directory before launching the notebook.

**Comment by christiankur** [comment]
Guys, thank you very much! Did not think that I get so fast answers. I think you can close this issue.

**Comment by takluyver** [comment]
Thanks, glad we could work it out.
