### ISSUE TITLE
Error! jupyter-notebook.exe is not UTF-8 encoded issue

### ISSUE THREAD

**Issue by Cityjohn** [jupyter/help#271]
I'm a little new to jupyter and have tried to install it twice now using pip but if I open jupyter it will state the error mentioned in the title, and not allow me to execute code. I've done my best to figure this out but the internet has been no help at all and I'm only versed in basic Python. Wondering what to do to make it work, it would be very useful to have the mathematica like interface for python.

**Comment by takluyver** [comment]
How are you trying to run it?

**Comment by Cityjohn** [comment]
By typing "C:\Program Files\Python36\Scripts>jupyter notebook" into cmd prompt.
A chrome tab pops up showing all the scripts (jupyter tree), I press notebook, it opens another chrome tab and shows the Error: "C:\Program Files\Python36\Scripts>jupyter-notebook.exe is not UTF-8 encoded, saving disabled. See Console for more details."
The console shows the Error:

"[I 16:13:47.113 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 16:14:09.169 NotebookApp] 400 GET /api/contents/jupyter-notebook.exe?type=file&format=text&_=1514992449025 (::1): C:\Program Files\Python
36\Scripts\jupyter-notebook.exe is not UTF-8 encoded"

I tried login with the specific token shown at the top "Copy/paste this URL into your browser when you connect for the first time"
And then it says "[I 16:14:42.482 NotebookApp] 302 GET /?token=cee057432402665b18e25a20b93c8d5979a199b5d446c453 (::1) 0.00ms
[W 16:14:49.505 NotebookApp] 400 GET /api/contents/jupyter-notebook.exe?type=file&format=text&_=1514992489371 (::1): C:\Program Files\Python
36\Scripts\jupyter-notebook.exe is not UTF-8 encoded"

I've already uninstalled the complete package and reinstalled it again.

**Comment by takluyver** [comment]
OK, I think you're a bit confused. The Chrome tab that pops up is the notebook interface. It's already running. What you probably want to do next is click the 'New' button, and make a new notebook.

However, it probably won't let you save notebooks in that folder. Use `cd` in the command prompt to change to a folder like `C:\Users\<USERNAME>` and launch `jupyter notebook` from there. Then you should be able to create and save notebooks.

**Comment by Cityjohn** [comment]
O! hehehehe... that makes so much sense I'm blushing, this was fun.

Thanks you so much for pointing that out.
