### ISSUE TITLE
404 link on try.jupyter.org

### ISSUE THREAD

**Issue by jonahweissman** [jupyter/help#276]
On the [browser demo of Jupyter](https://try.jupyter.org/), the file `Welcome to Python.ipynb` has a broken link. In the second cell this link returns 404:

```
A full tutorial for using the notebook interface is available [here](ipython_examples/Notebook/Index.ipynb).
```

**Comment by takluyver** [comment]
Thanks - the file comes from here if you can figure out how to update it:
https://github.com/jupyter/docker-demo-images/blob/master/notebooks/Welcome%20to%20Python.ipynb
