### ISSUE TITLE
Dead Kernel

### ISSUE THREAD

**Issue by saif567** [jupyter/help#279]
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

Please help me with this..

here is the command prompt screen

![error](https://user-images.githubusercontent.com/28825298/34719994-084b4db8-f563-11e7-9550-a6124e5ccc07.png)

 @takluyver

**Comment by takluyver** [comment]
It seems to be detecting your home directory as `C:\Program Files\Java\jdk-9` - any idea why that might be? Can you check environment variables/

**Comment by saif567** [comment]
Yes, i setted my Home variable as "C:\Program Files\Java\jdk-9" for the sake of java programming.


![image](https://user-images.githubusercontent.com/28825298/34728750-be516e7c-f580-11e7-867d-008998092752.png)

**Comment by takluyver** [comment]
OK, I'm not sure why Java would need that, but IPython expects your home directory to be somewhere that you have write permissions. On Windows, it's usually `C:\Users\<Username>` .

**Comment by saif567** [comment]
So, should i set my home directory to c:\users\<username> .

**Comment by takluyver** [comment]
Yeah, replacing `<username>` with your username on the computer. Or if you just delete the environment variable, it should use that location by default.

**Comment by saif567** [comment]
Thanks a lot for the help sir .

**Comment by takluyver** [comment]
No problem
