### ISSUE TITLE
Start a Notebook from a link in another Notebook

### ISSUE THREAD

**Issue by ssackett** [jupyter/help#280]
Hi,
I am trying to put a link to another Notebook inside a Notebook.  The idea is to have a hyperlink in a markdown cell in Notebook A that starts Notebook B when it is clicked.  Notebook B opens in another tab and both Notebooks continue to run.  (I am operating in JupyterHub and the same user owns both Notebooks).

Is there a way to do this? 
Thanks,
Steve

**Comment by takluyver** [comment]
The link should work with something as simple as `[Click here to open notebook B](Notebook B.ipynb)` . You might need an HTML link to make it open in a new tab, though.

**Comment by ssackett** [comment]
Hi,
I have tried the suggested solution and written it two different ways (see below):
---- First way
 [**Quick Start Guide**](Quick Start Guide.pynb) 

      When clicked this produces the URL: https://gitinsight.mars-insight.us/user/gitinsight/notebooks/Quick%20Start%20Guide.pynb
-----

-----Second way
<a href="Quick Start Guide.pynb">**Quick Start Guide**</a>

     When clicked this produces the URL:  https://gitinsight.mars-insight.us/user/gitinsight/notebooks/Quick%20Start%20Guide.pynb
-------
In each case the URLs are identical and both requests fail with a 404 error.

A Notebook named "Quick Start Guide.pynb" is located at ../gitinsight/notebooks/  and is able to be started from the file list.

Can you tell me if I have done something improperly?  If not is there a way to make it work?

Thanks,
Steve

**Comment by ssackett** [comment]
Hi,
I figured it out.  I spelled the filename wrong.  I used the extension .pynb and should have used .ipynb.
Thanks for your help.

Steve

**Comment by takluyver** [comment]
Great, glad you figured it out!
