### ISSUE TITLE
Running for the first time (kinda)

### ISSUE THREAD

**Issue by skarthik94** [jupyter/help#284]
So I'm a grad student and pretty new to jupyter notebook. After the installation, I noticed that I couldn't get it to display output, neither could my professor. Ran it on chrome, firefox and edge, didn't work on any of them. Changed the port, no go. Next to 'python 3' in the top right hand, it says 'no connection to kernel'

This appears in the console.

```
Adapting to protocol v5.1 for kernel 13a4524a-b424-418d-b534-07620a153e48
WebSocket ping timeout after 90011 ms.
```

Command prompt tells me that python is installed.

I've tried re-installing anaconda multiple times but it doesn't fix the problem. Also, I installed notebook about a year ago and it functioned then.
Any help would be appreciated.

**Comment by takluyver** [comment]
The 'ping timeout' means that it's lost the connection. Do you have any internet security software, or do you have a proxy configured?

**Comment by skarthik94** [comment]
I've disabled security and I have no proxy configured

**Comment by skarthik94** [comment]
So I gave jupyter full access in the permissions setting and it's working now. Nothing bad could happen because of this right? My code will be solely for academic purposes

**Comment by takluyver** [comment]
I don't know which permissions thing you mean ;-). Can you provide a screenshot?

**Comment by skarthik94** [comment]
In properties->security, I've enabled full control. Sorry about the ambiguous language.
![image](https://user-images.githubusercontent.com/35552140/35116799-a51f1a2c-fc5a-11e7-9231-8ac129bc12b3.png)

**Comment by takluyver** [comment]
I would have thought that only controls who can modify the start menu shortcut, which should make no difference to running the notebook. So if it does make a difference, I don't know what it's doing. ;-)

If it's a personal computer that you're the only user of, I would guess it's OK to enable those settings.

**Comment by skarthik94** [comment]
Yup that's the case, but out of curiosity, why would it be a bad if it wasn't?

**Comment by takluyver** [comment]
If it was on a server that multiple people use, those settings might let someone else modify your shortcut so that you end up running a program you didn't mean to, which could steal or change your files.
