### ISSUE TITLE
jupyter_mac.command is not executable with fish.

### ISSUE THREAD

**Issue by hal0taso** [jupyter/help#287]
Dear All

Getting following error when I launch Jupyter-notebook via Anaconda-Navigator.

```
/Users/hal0taso/anaconda3/bin/jupyter_mac.command ; exit;
Failed to execute process '/Users/hal0taso/anaconda3/bin/jupyter_mac.command'. Reason:
exec: Exec format error
The file '/Users/hal0taso/anaconda3/bin/jupyter_mac.command' is marked as an executable but could not be run by the operating system.
```

so I check `jupyter_mac.command`, and it was following

```
DIR=$(dirname $0)

$DIR/jupyter-notebook
```

It only executes `jupyter-notebook` but doesn't assign which interpreter it uses.

I use `fish` to login shell, so this script doesn't work.

When I exeucute via `sh` or `bash` on terminal, it work.

I think we'd better add `#!/bin/sh` on first line, but I don't know where to ask my issue. What should I do?

I use Anaconda-Navigator 1.6.9, Jupyter-notebook 5.0.0, and MacOS HighSierra 10.13.2.

(Sorry for my poor English)

**Comment by takluyver** [comment]
I think this should be an [anaconda issue](https://github.com/ContinuumIO/anaconda-issues/). The `jupyter_mac.command` file isn't something Jupyter created.

**Comment by hal0taso** [comment]
@takluyver 
Thanks for the reply.
I opened this issue  at anaconda issue and [here](https://github.com/ContinuumIO/anaconda-issues/issues/8222).
