### ISSUE TITLE
No kernels available

### ISSUE THREAD

**Issue by teto** [jupyter/help#29]
hi, my jupyter stopped working after an update. 
I updated it with "python3.5 -mpip install -U jupyter --user" and now upon "jupyter qtconsole" I have "jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3"
Upon running `jupyter kernelspec list`, I have:
```
[ListKernelSpecs] WARNING | Native kernel (python2) is not available
No kernels available
```
I removed the python 2 kernel as I thought I had a python3 installed (before I knesw about kernelspec list) and the pythoné was preventing jupyter from seeing a python3 kernel. 
I tried installing a python3 kernel following some github comments to no avail: 
`python3 -m ipykernel install --user` does not work:
`/usr/bin/python3: Error while finding spec for 'ipykernel.main' (<class 'ImportError'>: No module named 'IPython.paths'); 'ipykernel' is a package and cannot be directly executed`

**Comment by takluyver** [comment]
> No module named 'IPython.paths'

This usually means it's finding an older version of IPython installed somewhere. Try uninstalling all copies of IPython (including through your system package manager, if you're on Linux), and installing the latest again.

**Comment by teto** [comment]
thx that fixed it, I now exclusively install in --user and forgot about the system install
