### ISSUE TITLE
Can't create Jupyter Notebook in a subdirectory

### ISSUE THREAD

**Issue by gabraganca** [jupyter/help#291]
Hi.

I am having issues creating a Jupyter Notebook inside a subdirectory. Instead of creating in the subdirectory, it creates in the root path.

Let me exemplify. Let us suppose that I have the following path structure:

![b2tlj](https://user-images.githubusercontent.com/2700254/35478075-d5f6b706-03ba-11e8-8aa7-54015742d97d.png)

Then, I open `Subdirectory_1` and asks it to create a Notebook. 

![xvq1p](https://user-images.githubusercontent.com/2700254/35478081-eac29dd0-03ba-11e8-8f48-e5fc72742979.png)

But instead of creating it in the `Subdirectory_1`, it creates in the root path.
![5euc4](https://user-images.githubusercontent.com/2700254/35478084-fa6915b6-03ba-11e8-9d2b-8755183642f6.png)

And these are the log messages:

![ryxr5](https://user-images.githubusercontent.com/2700254/35478085-041a3bda-03bb-11e8-8de4-dfa90a62672e.png)

I've created [a question on SO](https://stackoverflow.com/q/48429807/2029132) before finding this repository.

**Comment by takluyver** [comment]
Sorry, this is a bug in notebook 5.3. I'm going to release 5.4 soon with the fix (https://github.com/jupyter/notebook/pull/3264).

**Comment by gabraganca** [comment]
Thanks, @takluyver . I will downgrade to 5.2 in meantime.
