### ISSUE TITLE
pip install error on Windows.

### ISSUE THREAD

**Issue by firehawk12** [jupyter/help#293]
Hello,
I am trying to install a package via pip on Windows using the command: **!pip install tweepy**

> 
> But I get an error:
> Collecting tweepy
>   Using cached tweepy-3.5.0-py2.py3-none-any.whl
> Collecting requests-oauthlib>=0.4.1 (from tweepy)
>   Using cached requests_oauthlib-0.8.0-py2.py3-none-any.whl
> Requirement already satisfied: requests>=2.4.3 in c:\program files\anaconda3\lib\site-packages (from tweepy)
> Requirement already satisfied: six>=1.7.3 in c:\program files\anaconda3\lib\site-packages (from tweepy)
> Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.4.1->tweepy)
> Installing collected packages: oauthlib, requests-oauthlib, tweepy
> Exception:
> Traceback (most recent call last):
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
>     **kwargs
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
>     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
>     isolated=self.isolated,
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
>     clobber(source, lib_dir, True)
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\wheel.py", line 316, in clobber
>     ensure_dir(destdir)
>   File "C:\Program Files\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
>     os.makedirs(path)
>   File "C:\Program Files\Anaconda3\lib\os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Anaconda3\\Lib\\site-packages\\oauthlib'
> 

I've been Googling around and I can't find a solution specific to Jupyter Notebook - they essentially say that I should run python as administrator - but I am running Jupyter Notebook through Anaconda, so I'm not sure what I can do on my end.

Any help would be greatly appreciated.  Thank you.

**Comment by takluyver** [comment]
You can either add the `--user` flag to install packages for your user without admin access, or create separate conda environments to work on particular projects, and install packages into an environment.

**Comment by firehawk12** [comment]
Thanks!  How would I start a new Conda environment?

Sent from my iPhone

On Feb 2, 2018, at 5:10 AM, Thomas Kluyver <notifications@github.com<mailto:notifications@github.com>> wrote:


You can either add the --user flag to install packages for your user without admin access, or create separate conda environments to work on particular projects, and install packages into an environment.

**Comment by takluyver** [comment]
Have a look at the conda docs here: https://conda.io/docs/user-guide/getting-started.html

**Comment by firehawk12** [comment]
Thank you for your help!
