### ISSUE TITLE
JavaScript-based Visualizations as Response from Kernel?!?

### ISSUE THREAD

**Issue by HelgeCPH** [jupyter/help#296]
Hi,

I am new here and since I do not know where in the Jupyter universe my questions would fit, I am asking them here :)

During the weekend I started learning how to write a kernel for Jupyter. I started experimenting with the Echo kernel and modified it into a kernel for the Cypher language (https://neo4j.com/developer/cypher/), which is the query language of Neo4j (a graph database). I followed the documentation (http://jupyter-client.readthedocs.io/en/latest/wrapperkernels.html) and took inspiration of the IMongo kernel (https://github.com/gusutabopb/imongo).

Currently, my `cypher_kernel` (https://github.com/HelgeCPH/cypher_kernel) wraps the database's HTTP API with the help of the `requests` module. In the end it should work similar to the Neo4j Browser, which is Neo4j's browser based REPL, see https://neo4j.com/developer/guide-neo4j-browser/.

That is, when a Cypher query returns graph elements (nodes or edges) the query result should be visualized in a graph. Additionally, all queries should return the result in textual form. Even though it is not polished yet, I know how to do the latter. For the former, I was thinking to create visualizations with the help of Alchemy.js (http://graphalchemist.github.io/Alchemy/#/) as suggested on Neo4j's homepage https://neo4j.com/developer/guide-data-visualization/#_library_alchemy_js_open_source_graph_visualization.

Currently, the code in my kernel converts the response of the HTTP API into a JSON document, which is put into a HTML page, see `_response_to_html` line 165ff. https://github.com/HelgeCPH/cypher_kernel/blob/a1fae0fbf11c74d4013b05dff110139099f4a457/cypher_kernel/kernel.py#L165 The result for a code cell should look similar to
https://github.com/HelgeCPH/cypher_kernel/blob/master/example/bike.html or 

![screenshot](https://github.com/HelgeCPH/cypher_kernel/blob/master/example/query_screenshot.png?raw=true)

However, I do not think that JavaScript-based visualization should be returned by the kernel as HTML pages. First, I am receiving errors such as:

```
Javascript error adding output!
ReferenceError: Can't find variable: Alchemy
See your browser Javascript console for more details.
```

and 

```
Javascript error adding output!
Error: Mismatched anonymous define() module: [object Object] http://requirejs.org/docs/errors.html#mismatch
See your browser Javascript console for more details.
```

Furthermore, all visualizations are always put into the output of the first code cell in a notebook.

I have **absolutely no experience with web-development and JavaScript**. Can someone please describe how my kernel has to return JavaScript-based visualization correctly? Alternatively, can someone please point me to some code that does something similarly so that I can try to understand it from there?

Additionally, I have another smaller question: How do I add syntax highlighting to the kernel? I read something about notebook extensions but I am not really sure how that relates to a language kernel and if this is what I have to check.

Thank you in advance for your help,
HelgeCPH

**Comment by HelgeCPH** [comment]
Hej all,

The following will answer my question: How to return Javascript-based visualizations from my own language kernel?

Since I could not find anything related in the documentation on writing language kernels and since I guess it might be of help for others, it will get a bit longer...

As mentioned, I am not webdeveloper. I do not know Javascript or anything related :) Consequently, I was talking to webdevelopers and they explained to me what the above errors mean and how to track them down within a browser's development tools, I understood my problem and was able to find the mistake.

What I learned:

  1. In Jupyter, one cannot include JS packages via HTML `<script>` tags.
  2. Jupyter notebooks use [`require.js`](http://www.requirejs.org) to import JS packages, see https://blog.thedataincubator.com/2015/08/embedding-d3-in-an-ipython-notebook/. Consequently, the errors above are described in http://requirejs.org/docs/errors.html#mismatch.
  3. I did not want to use `alchemy.js` as indicated in the question above, as I ran into similar problems as described [here](https://stackoverflow.com/questions/42042085/alchemy-js-simple-example-not-working). Instead, I switched to [`vis.js`](http://visjs.org), mostly due to its extensive list of examples, see http://visjs.org/network_examples.html



Consequently, find documentation for your Javascript library on how to use it with `require.js`. For `vis.js` I found the following example in their repository:
https://github.com/almende/vis/blob/master/examples/timeline/other/requirejs/scripts/main.js

Then take this code and split it into two sections:

  1. An HTML message containing a `<div>` element for your JS script.
  2. The actual script to fill into that `<div>` element.


Code that will work in a Jupyter kernel can look similar to the following.

The HTML code as a multi-line string.
```python
html_str = '''<link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css" rel="stylesheet" type="text/css">
<div id="mynetwork"></div>
'''
```

And the corresponding JS script.

```python
js_str = '''require(["https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js"], function(vis) {

  // create an array with nodes
  var nodes = new vis.DataSet([
    {id: 1, label: 'Node 1'},
    {id: 2, label: 'Node 2'},
    {id: 3, label: 'Node 3'},
    {id: 4, label: 'Node 4'},
    {id: 5, label: 'Node 5'}
  ]);

  // create an array with edges
  var edges = new vis.DataSet([
    {from: 1, to: 3},
    {from: 1, to: 2},
    {from: 2, to: 4},
    {from: 2, to: 5},
    {from: 3, to: 3}
  ]);

  // create a network
  var container = document.getElementById('mynetwork');
  var data = {
    nodes: nodes,
    edges: edges
  };
  var options = {};
  var network = new vis.Network(container, data, options);});
'''
```

Then, as far as I understand, one has to send the two strings -`html_str` and `js_str` respectively- via two separate messages to the notebook server.

```python
html_msg = {'data': {'text/html': html_str}, 
            'execution_count' : self.execution_count}
js_msg = {'data': {'application/javascript': js_str}}
self.send_response(self.iopub_socket, 'display_data', js_msg)
self.send_response(self.iopub_socket, 'display_data', html_msg)
```

That code will render a graph as output of your code cell.


However, the important thing that I overlooked and that caused the errors above is that under some circumstances -I do not know which- the anonymous function in the `require` call needs to get a parameter. As in `function(vis)`.

That this parameter is not always needed, can be seen in the following code, which renders a nice JSON string with https://github.com/caldwell/renderjson. The code is similar to the one used in the `imongo` Jupyter kernel, which I checked to learn from. 


```python
html_str = '<div id="test"></div>''
```

```python
js_str = '''require(["https://rawgit.com/caldwell/renderjson/master/renderjson.js"], function() {
    document.getElementById("test").appendChild(
        renderjson({ hello: [1,2,3,4], there: { a:1, b:2, c:["hello", null] } })
    );});
```

```python
html_msg = {'data': {'text/html': html_str}, 
            'execution_count' : self.execution_count}
js_msg = {'data': {'application/javascript': js_str}}
self.send_response(self.iopub_socket, 'display_data', js_msg)
self.send_response(self.iopub_socket, 'display_data', html_msg)
```

Importantly, there the anonymous function -for some reason- does not need to get passed any parameter.



I hope this helps others in a similar situation.

**Comment by SylvainCorlay** [comment]
Hi @HelgeCPH. I think that Jupyter interactive widgets are what you are looking for. They mostly have been developed for the Python kernel but are in fact a fully specified protocol for bi-directional communication between the web frrontend and the kernel.

The way they operate is more robust than inserting script tags in your outputs. Alternate backend implementation of the Jupyter widgets protocol include the xwidgets project which enables widgets for the C++ kernel. The xwidgets project also serves as the foundation for other language implementations such as widgets in the juniper kernel.
