### ISSUE TITLE
Importing Keras does not work

### ISSUE THREAD

**Issue by danieldmm** [jupyter/help#3]
I am unable to run some simple code inside jupyter notebook using Keras that works perfectly well in the normal command interepreter.

Running this works fine:
```
import keras
print "Hello world"
>>> Hello world
```
But running this never executes, or never finishes executing:
```
import keras
from keras.models import Sequential
print "Hello world"
```
It remains stuck on "In: [*]", with the CPU pretty much idle, so it doesn't seem to be processing anything.

If I run the same code in ipython I get this output:
```
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Failed to import scipy.linalg.blas, and Theano flag blas.ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (DLL load failed: The specified module could not be found.)
```

But it works as expected. Do you know what could be causing this problem? Thanks!

**Comment by willingc** [comment]
Hi @danieldmm,
I tried your examples using the Jupyter Notebook with a Python2, Python3, and IPython2 kernel. I'm not experiencing any errors so I suspect that there is an installation issue in your environment. If you start the notebook in debug mode, you may get more helpful error messages ``jupyter notebook --debug``.

My instinct is that scipy may not be installed at the correct version or has some sort of conflict. Here's my environment configuration if you wish to compare:
```
appnope (0.1.0)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
certifi (2016.2.28)
decorator (4.0.9)
functools32 (3.2.3.post2)
gnureadline (6.3.3)
ipykernel (4.3.1)
ipython (4.1.2)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
Keras (0.3.3)
MarkupSafe (0.23)
mistune (0.7.2)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.1.0)
numpy (1.11.0)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.6)
Pillow (3.2.0)
pip (8.1.1)
ptyprocess (0.5.1)
Pygments (2.1.3)
PyYAML (3.11)
pyzmq (15.2.0)
qtconsole (4.2.1)
scipy (0.17.0)
setuptools (20.6.7)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
terminado (0.6)
Theano (0.8.1)
tornado (4.3)
traitlets (4.2.1)
wheel (0.29.0)
```
Another thing that you may wish to try is installing Anaconda and running using a conda environment.

I hope this helps. Please do let us know if it helps or if further troubleshooting is needed. Thanks.

cc/@takluyver @minrk

**Comment by takluyver** [comment]
If stuff gets stuck, you can try interrupting it (stop button in the toolbar). That should give a `KeyboardInterrupt` error, and the traceback might show where it's stuck. Or it might ignore it, in which case you don't know any more...

**Comment by alexandercbooth** [comment]
@danieldmm Have you tried again after upgrading to the latest release of Keras (today's 1.0)?

**Comment by takluyver** [comment]
I think you may need to talk to people who know about Keras to understand what might make it hang. I don't think we know enough about it to debug this.

**Comment by danieldmm** [comment]
Thanks @takluyver , I will!

**Comment by willingc** [comment]
@danieldmm I hope that you got this issue sorted out with Keras. I'm going to close this issue, but please reopen or leave a message to reopen if needed now or in the future. Thanks!
