### ISSUE TITLE
changing drive

### ISSUE THREAD

**Issue by monsteroyd** [jupyter/help#302]
When I am in the jupyter notebook it shows me things on drive c:, but I need to look on another drive, drive D:

I know this sounds stupid, and I am sure it is simple, but I cannot for the life of me figure out how to do it from the current web UI.

Thanks
Monty

**Comment by monsteroyd** [comment]
Nevermind I figured it out, do it before running jupyter, crude but effective

**Comment by takluyver** [comment]
Yup, you got it. By design, it only serves files from the folder it was started in and subfolders below that. On Windows, that means you can't have the whole filesystem accessible from one notebook server, as there's no single root directory.
