### ISSUE TITLE
JupyterHub: environment variables are not available when running the hub with sudo

### ISSUE THREAD

**Issue by chack05** [jupyter/help#303]
Hi,

I'm running JupyterHub 0.8.1 for demonstration purposes with the vanilla default configuration on an Ubuntu 16 LTS Server.

(EDIT: installed by pip)

Now I've run into the problem that environment variables like `PYTHONPATH` are not set/preserved when running the hub with `sudo`, even with `sudo -E` which apparently is supposed to preserve the environment. 

Without root privileges it works, which manifests in being able to import custom Python modules and printing out the environment variables in a notebook. But according to the documentation, root privileges are required for supporting multiple users with the default spawner, which I'd like to use for its simplicity.

Other steps I've taken:

* uncommenting the env_keep option in the generated jupyter_config file, because it contains `PYTHONPATH`
* adding the paths in `.profile` like so `export PYTHONPATH=~/myownpythonlibrary:$PYTHONPATH`
* adding the paths in `.bashrc`

Unfortunately, none of that worked and I'm out of ideas, so I appreciate every clue.

Thanks in advance!

**Comment by takluyver** [comment]
cc @jupyter/jupyterhub

**Comment by willingc** [comment]
Hi @chack05, Please see our responses in https://github.com/jupyter/help/issues/304. Thanks.
