### ISSUE TITLE
JupyterHub: failing to spawn notebooks for other users

### ISSUE THREAD

**Issue by chack05** [jupyter/help#304]
Hi,

I'm running JupyterHub 0.8.1 for demonstration purposes with the vanilla default configuration on an Ubuntu 16 LTS Server, installed by pip. Node version is 4.2.6.

It works mostly successfull (except for some environment var issue) with my own user, both when running with or without root privileges.

However, I created two test users with their own home directory and password and registered them in the control panel. Now, on every attempt to start a single-user server for one of those users — both from the control panel or when logging in as the user — the spawner fails to start with status 1 with the following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 11, in <module>
    from jinja2 import ChoiceLoader, FunctionLoader
ImportError: No module named 'jinja2'
[W 2018-02-21 15:40:22.778 JupyterHub web:1588] 500 POST /hub/login?next= (10.6.3.66): Spawner failed to start [status=1]. The logs for testuser1 may contain details.
[D 2018-02-21 15:40:22.779 JupyterHub base:633] No template for 500
[E 2018-02-21 15:40:22.789 JupyterHub log:114] {
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-Host": "servername",
      "X-Forwarded-Proto": "https",
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate, br",
      "X-Forwarded-For": "10.6.3.66",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0",
      "Content-Type": "application/x-www-form-urlencoded",
      "X-Forwarded-Port": "443",
      "Host": "servername",
      "Cookie": "_xsrf=2|de61a9b2|450c5c37757f48e5439d0a9312f07688|1519219116",
      "Accept-Language": "de,en-US;q=0.7,en;q=0.3",
      "Content-Length": "41",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Referer": "https://servername/hub/login"
    }
[E 2018-02-21 15:40:22.790 JupyterHub log:122] 500 POST /hub/login?next= (@10.6.3.66) 10166.77ms
[D 2018-02-21 15:40:22.909 JupyterHub log:122] 304 GET /favicon.ico (@10.6.3.66) 1.27ms
[W 2018-02-21 15:40:45.619 JupyterHub user:458] testuser1's server never showed up at http://127.0.0.1:58807/user/testuser1/ after 30 seconds. Giving up
[E 2018-02-21 15:40:45.633 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f5b7adf5668> after timeout
    Traceback (most recent call last):
      File "/home/mainuser/.local/lib/python3.5/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:58807/user/testuser1/ didn't respond in 30 seconds

```

Judging from the first couple of lines I guessed it is caused by the lack of jinja2. However, the result of `pip3 list` actually includes jinja2.

If that is just required for a nicer looking error message: There aren't many opportunities where the network configuration could fail, because all the jupyterhub, proxy and notebook processes are apparently preconfigured to communicate at 127.0.0.1 and it all runs with the out-of-the-box configuration on a single server. In fact, I run it with an almost unchanged configuration, with the user notebook folder being ~ and the hub running at 0.0.0.0 (I also tried the servers adress itself.). Then, I also pass certificates for https support to the hub, but that's it, basically.

Any ideas? Aside from the console output, where can I find additional logs, like mentioned in `The logs for testuser1 may contain details.`?

Thanks and best regards.

**Comment by chack05** [comment]
So it turns out that jinja2 as well as some other packages (notebook, tornado) were missing on the test users account.
Is this the expected behavior? If so, is there a way to automate the pip package installation from within JupyterHub? For example, when the option to automatically create users is enabled, would JupyterHub install the required packages?

**Comment by takluyver** [comment]
@jupyter/jupyterhub

**Comment by willingc** [comment]
@chack05 I think that you are running into this configuration issue: https://github.com/jupyterhub/jupyterhub/issues/1467#issuecomment-334726797

If that doesn't resolve the issue for you, please open an issue directly on the jupyterhub repo: https://github.com/jupyterhub/jupyterhub/issues/new

If you can provide the output of `jupyter troubleshoot` when reporting future issues, we'll be able to more easily help you. Thanks!

**Comment by minrk** [comment]
When running jupyterhub in the default configuration, you want to make sure that you are running in a shared env that all users have read+execute permissions. This is the default for system-wide installations of packages, but it means no using packages in a virtualenv in your home directory, and no no `--user` installs of packages, etc.

**Comment by chack05** [comment]
@willingc Thanks, I'll give it a try.
@minrk Thank you. What do you mean by shared environment? Is that a Linux thing or a Python thing? Do you mean putting the path exports into /etc/bash.bashrc? Sorry, I'm not an admin. As for pip, `pip install something` is system-wide by default, right? I should never need to execute pip with root rights, not even in exception for Jupyterhub, is that correct?

**Comment by chack05** [comment]
@willingc Unfortunately `which -a jupyterhub-singleuser` returns only `/usr/local/bin/jupyterhub-singleuser` and no second faulty installation directory, so it is probably not [the linked issue](https://github.com/jupyterhub/jupyterhub/issues/1467#issuecomment-334726797). Guess I'll open an issue in the jupyterhub issues later on.

@minrk To avoid confusion: In the linked issue I saw you mentioning using `sudo pip install somepackage`.

I asked the not-using-sudo thing because during the latest npm shenanigans (running npm with sudo mutates the owner rights of some directories or something like that) some people explicitly stated that one should never run a language package manager with sudo rights, not only limited to npm.

**Comment by minrk** [comment]
> Aside from the console output, where can I find additional logs, like mentioned in The logs for testuser1 may contain details.?

the user server logs are included in the jupyterhub output by default. The log snippet you have pasted includes the tail end of the output of testuser1's server, which is an ImportError on jinja2.

> one should never run a language package manager with sudo rights

"never" is too strong, but you do need to be careful when using sudo. It is often the right thing to do if your goal is to install a package for all users, rather than just yourself. sufficiently recent pip is generally quite well behaved when run with elevated permissions. Other package managers may be less so (the most common mistake they make is placing cache files in your home directory that will be owned by root). If you want to install packages in /usr/local, that typically requires sudo.

> What do you mean by shared environment?

It's a general concept, but what is relevant here is where Python packages are installed to and imported from. In this case 'shared environment' means that all of the packages available to Python (e.g. 'import jupyterhub` or `import jinja2`) are in a location that any user can read (i.e. none of them are coming from your home directory after being installed with `--user`). This is testable by attempting to run a bit of Python code (e.g. `jupyterhub-singleuser -h`, or `python3 -c import jinja2`) as multiple users, and make sure that they get the expected result. The fact that users are not able to import `jinja2` in the traceback suggests that jinja is indeed not in a location importable by other users. One thing to check is where does jinja come from when you import it? You can check with `import jinja2; print(jinja2.__file__)`.

>As for pip, pip install something is system-wide by default, right?

That depends on Python and pip. More precisely, it is *env-wide* by default. If you have made a virtualenv, it will install in the virtualenv. If you are running system Python, it will be in /usr/local, etc.

**Comment by chack05** [comment]
@minrk Thanks a lot!

In the meantime I figured since I installed the "normal" Jupyter version locally first for testing that this probably has caused some of the dependencies to be installed for one user only; `which -a jupyter` showed me only a local directory. So I'll try again with a rolled-back VM.
