### ISSUE TITLE
Customizing jupyterhub routing

### ISSUE THREAD

**Issue by AlecAivazis** [jupyter/help#31]
I'm trying to host jupyterhub "underneath" a specific url (ie,  `/jupyter `) however jupyterhub seems to be directing traffic to a few fixed routes like `/login`, `/logout`,  and `/hub`. What is the easiest way to change these to accommodate a different url structure?

**Comment by willingc** [comment]
Hi @AlecAivazis,

You can [set the single user notebooks to a particular directory](https://jupyterhub.readthedocs.io/en/latest/getting-started.html#configuring-single-user-servers). You also set [file locations](https://jupyterhub.readthedocs.io/en/latest/getting-started.html#configuring-single-user-servers) using the config file. Here's an [example config file](https://jupyterhub.readthedocs.io/en/latest/getting-started.html#example).

**Comment by AlecAivazis** [comment]
The Hub seems to be configured to redirect requests to /hub/<notebook_path> so I'm not sure if changing the notebook directory would do what I want. I'm trying to change the redirect target to /jupyter/hub/<notebook_path> so that the hub can live alongside other parts of an app. From what I can tell in the source code, these handlers are hard coded in the tornado app configuration but it's likely im missing something.

**Comment by yuvipanda** [comment]
If you want to set a 'prefix' you can use:

```
c.JupyterHub.base_url = '/jupyter/'
```

in your jupyter_config.py file.

This will make it listen for `/jupyter/hub/login` etc rather than just
`/hub/login`, etc.

On Sat, Apr 30, 2016 at 7:05 AM, Carol Willing <notifications@github.com>
wrote:

> Hi @AlecAivazis <https://github.com/AlecAivazis>,
>
> You can set the single user notebooks to a particular directory
> <https://jupyterhub.readthedocs.io/en/latest/getting-started.html#configuring-single-user-servers>.
> You also set file locations
> <https://jupyterhub.readthedocs.io/en/latest/getting-started.html#configuring-single-user-servers>
> using the config file. Here's an example config file
> <https://jupyterhub.readthedocs.io/en/latest/getting-started.html#example>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/help/issues/31#issuecomment-215921637>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by AlecAivazis** [comment]
Ah, there we go - I knew I was missing something. Thanks for the fast help as always @yuvipanda and @willingc.

**Comment by yuvipanda** [comment]
glad to help :)

On Sat, Apr 30, 2016 at 11:25 AM, Alec Aivazis <notifications@github.com>
wrote:

> Ah, there we go - I knew I was missing something. Thanks for the fast help
> as always @yuvipanda <https://github.com/yuvipanda> and @willingc
> <https://github.com/willingc>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/help/issues/31#issuecomment-215940636>
>



-- 
Yuvi Panda T
http://yuvi.in/blog
