### ISSUE TITLE
how to run git clone https://.... in jupyter

### ISSUE THREAD

**Issue by isalirezag** [jupyter/help#311]
I am new to jupyter
In python i can easily run git clone https://github..... and it runs and work
My question is how I can do it in jupyter because when i cpy and paste it in jupyter and run it it gives me error that:

```
  File "<ipython-input-4-4d4c63f65776>", line 1
    git clone https://github.com/tensorflow/models"
            ^
SyntaxError: invalid syntax
```

Also can you tell me how I can do cd Desktop/... in jupyter

Thanks

**Comment by itziana** [comment]
did you solve this problem?
now im in it...

**Comment by takluyver** [comment]
`git` is a shell command - if you see that error, you're trying to run it as Python code.

You can get a terminal inside Jupyter (on the files list page, click *New* and then *Terminal*). Or, inside a Python notebook, you can run system commands using a `!` prefix, i.e. `!git ...`.

**Comment by jcasavant** [comment]
@isalirezag  I assumed you solved the problem, but if not the easy way to run a shell command in Jupyter is to prefix with the ! (bang/exclamation).  So the command in the cell should be:
 !git clone https://github.com/tensorflow/models

**Comment by SHAKTISINGH2323** [comment]
## this is the command to run git clone in jupyter notebook
!git clone https://github.com/tensorflow/models 
## to view the the files in it
!ls models
