### ISSUE TITLE
Can IPython's display() prepend to a notebook cell's output area?

### ISSUE THREAD

**Issue by parente** [jupyter/help#33]
By default, it appends. Is there a trick to have it prepend to the output area instead so that newest output is at the top instead of at the bottom?

**Comment by Carreau** [comment]
No, I don't even think it's possible using the message spec, unless you add metadata and have notebook specific plugin that does it.

**Comment by parente** [comment]
Thanks. And now it's here for posterity.

**Comment by parente** [comment]
Closing this made me remember: [CSS is awesome](http://www.amazon.com/CSS-AWESOME-Mug-Cup-ounces/dp/B008LQQD7O)!

```
%%html
.code_cell .output {
    flex-direction: column-reverse;
}
```

This applies it to every output on the page, but with a bit more hacking, it could be targeted at specific outputs, I'm sure.

**Comment by Carreau** [comment]
You are evil.

**Comment by Carreau** [comment]
> You are evil.

And it might be a compliment, and the good kind of evil.
