### ISSUE TITLE
Notebooks only saved in storage root after upgrade

### ISSUE THREAD

**Issue by ab-sk** [jupyter/help#335]
We have updated our Miniconda Jupyter environment from:
python 3.5.3
jupyter_client 5.0.0
jupyter_core 4.3.0
notebook 4.4.1
to:
python 3.6.4
jupyter_client 5.2.1
jupyter_core 4.4.0
notebook 5.3.1
inplace and all notebooks run fine!

However, when creating a new notebook, it is always saved in the root notebook folder, whereas before, a notebook was saved in the folder one had navigated to before creating a new NB.
Moving the notebooks works fine.
The logs do not tell much, except for for the fifth entry at 08:01:33.478:

[I 08:01:19.649 NotebookApp] Kernel started: 7b7e6fa6-4b58-4afe-af4a-5696bc420ba3
[I 08:01:21.040 NotebookApp] Adapting to protocol v5.1 for kernel 7b7e6fa6-4b58-4afe-af4a-5696bc420ba3
[I 08:01:26.681 NotebookApp] Starting buffering for 7b7e6fa6-4b58-4afe-af4a-5696bc420ba3:F723BEA2E50B40CC85B78EC238A2E168
[I 08:01:27.024 NotebookApp] Kernel shutdown: 7b7e6fa6-4b58-4afe-af4a-5696bc420ba3
[I 08:01:33.478 NotebookApp] Creating new notebook in 
[I 08:01:33.978 NotebookApp] Kernel started: 34b4b572-abf5-47c4-bc80-f05cbb2e287e
[I 08:01:35.353 NotebookApp] Adapting to protocol v5.1 for kernel 34b4b572-abf5-47c4-bc80-f05cbb2e287e
[I 08:01:56.806 NotebookApp] Saving file at /Untitled5.ipynb

So, it seems that jupyter "forgot" the currently selected path. Can anybody point me into the direction what to set or where to look? Or might anybody even know why that is happening?

**Comment by takluyver** [comment]
Try doing  hard refresh in your browser a few times (Ctrl-F5), or try in a different browser. Sometimes weird issues when you upgrade are due to your browser caching the JS.

**Comment by ab-sk** [comment]
Thx. We have tried FF, Chrome and IE, cache cleared and from different machines. It does not seem to be the browser.

**Comment by takluyver** [comment]
Ah, I've just noticed that your upgrade didn't get you to the latest version, for some reason. You're running into jupyter/notebook#3248. Upgrade to the latest version (5.4.1) and it should work again.

**Comment by ab-sk** [comment]
Ups just saw the link. I accept this as solution. Thx!
Now, I will need to find a way to upgrade...
