### ISSUE TITLE
Handling different projects with different conda envs

### ISSUE THREAD

**Issue by JoshuaC3** [jupyter/help#342]
I am currently trying to figure out how to go about setting up my ongoing Data Science working environment/setup would love to get some ideas on how to do this.

**Environments**
We are all told it is good practice to have different conda envs, with different dependencies, for each project. However, there seems to be some gaps in the current Jupyter ecosystem for handling this. For example, each `conda create -n xxx` has its own install of Jupyter.

I wish to generate different config files for each instance of jupyter. Using `jupyter notebook --generate-config` even after `conda activate xxx` it tries to generate this in the base `.jupyter` directory and threatens to overwrite my current config file.

**Jupyter Lab**
This is awesome. I have setup a jupyterlab server so that I can run my jupyter notebooks in lab. I also get cmd interface for all of my cmd stuff: sudo pip installs, mv, unzip, ...

However, if I am working on two projects at the same time, I need to setup to two Jupyter Lab instances with two different environments. This can be fairly easily done by starting multiple services. The main problem is now that you have to keep track of the order in which you started them to figure out if they are on ports `8888` or `8889` etc. There is also the added issue of keeping track of which tab contains which project.

**Questions**
How can we setup multiple Jupyter config files, specifically, one for each conda-env/project?

How can I change the [Chrome Tab Title for JupyterLab](https://github.com/jupyterlab/jupyterlab/issues/4422)?

Will it ever be possible/has it been considered that we could run Jupyter Lab in a base conda env and then launch notebooks in different conda envs?

**Comment by takluyver** [comment]
> Will it ever be possible/has it been considered that we could run Jupyter Lab in a base conda env and then launch notebooks in different conda envs?

Yes! It's already possible. The way we support is to install a kernelspec for each environment you want to run in:

http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments

Anaconda has a plugin called [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) which handles things more automatically.

I'm working on better ways of handling different kernels for the same language.

**Comment by jasongrout** [comment]
> How can I change the Chrome Tab Title for JupyterLab?

Answer at the https://github.com/jupyterlab/jupyterlab/issues/4422

**Comment by JoshuaC3** [comment]
@takluyver - Awesome, thank you. This is a massive help. I realise I didnt find anything on this as I was asking (google) for the wrong thing. I should have asked how to run notebooks on different kernels, not on different envs.

Both of these things help my workflow massively, however, if I still needed to run different envs in different services, I still need to rely on the same config file.

Is it possible to to generate multiple config files and get jupyterlab/notebook in specific envs to point to these other configs? My main reason for this is to set a hostname for each instance and with a separate password. Many thanks!

**Comment by takluyver** [comment]
Jupyter applications can be configured per environment, so long as the same values aren't set in your per user config:

http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#configuration-files

However, if you follow my suggestion of running kernels in different environments, Jupyter itself is only running in one environment. It won't pick up config based on which kernels you run.

The kernels themselves also have config options, but the IPython kernel does not expose per-environment configuration ([IPython config docs](http://ipython.readthedocs.io/en/stable/config/intro.html)). You could use a [startup file](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files) which detects which environment it's running in and sets some things up.

**Comment by JoshuaC3** [comment]
That first link solves my config file issue. Thanks.

In summary, for future readers, I see two options:
1) I choose to run multiple services, one service per conda-env, each with its own JupyterLab. This will use its own `JUPYTER_CONFIG_DIR` to its own config file where I will state a host/ip name and password. I will then name each tab as per [jupyterlab/jupyterlab#4422](https://github.com/jupyterlab/jupyterlab/issues/4422).

2) More simply, I can just use kernel [environments](https://github.com/jupyter/help/issues/342#issuecomment-382837602) and have it all running out of a single JupyterLab running on a single service.
