### ISSUE TITLE
Unable to open Jupyter NB after Anaconda RStudio Load

### ISSUE THREAD

**Issue by McCabeJM** [jupyter/help#344]
I'm sorry to be a bother... but I can't determine how to fix this issue.  I recently installed RStudio (v 1.1.423) from within Anaconda Navigator; I did already have an older installation of RStudio (v 1.0.423) on my MacBook Pro (High Sierra 10.13.4).  Unfortunately, I now get the following error when trying to launch Jupyter Notebook from the command line.  I get the same error when trying to launch Jupyter NB from within Navigator.  (BTW RStudio works fine, both installed versions)  I tried to update Anaconda (within the anaconda directory,     conda update conda) in the chance it was a version issue. Can anyone offer a suggestion? 

Last login: Sun Apr 22 09:21:05 on ttys001
Jamess-MBP:~ mikemccabe$ jupyter notebook
Traceback (most recent call last):
  File "/anaconda/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/anaconda/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'
Jamess-MBP:~ mikemccabe$

**Comment by takluyver** [comment]
That looks like the notebook package was updated but not the jupyter_core package. Try `conda update jupyter_core`.

**Comment by McCabeJM** [comment]
Yes!  That solves the issue. Thank you very, very much for the quick reply!
