### ISSUE TITLE
Congrats! ACM Software System Award

### ISSUE THREAD

**Issue by rsvp** [jupyter/help#353]
# Congratuations!

> BIDS Senior Fellow Fernando Perez and the members of the Project Jupyter Steering Council have been honored with this year's Association of Computing Machinery (ACM) prestigious Software System Award for developing software tools that have had a lasting influence on computing. 

> Project Jupyter is a broad collaboration that develops open source, language-agnostic tools for interactive computing. These tools – which include IPython, the Jupyter Notebook and JupyterHub – have become a de facto standard for data analysis in research, education, journalism and industry. Jupyter has broad impact across domains and use cases. Today more than 2,000,000 Jupyter notebooks are on GitHub, each a distinct instance of a Jupyter application, covering a range of uses from technical documentation to course materials, books and academic publications. Jupyter has also gained wide industry adoption. Since 2015, Jupyter-based products have been released by several companies including Google (Cloud DataLab), Microsoft (AzureML, HDInsight), Intel (Trusted Analytics Platform), and IBM (Watson Studio). Bloomberg and Anaconda Inc have partnered with Project Jupyter to develop the next-generation web interface, JupyterLab. 

> The original Project Jupyter Steering Council, led by Perez and Brian Granger (Cal Poly San Luis Obispo), includes BIDS Fellow Matthias Bussonnier, Carol Willing (also of Cal Poly San Luis Obispo), Min Ragan-Kelley (Simula Research Laboratory), Paul Ivanov and Jason Grout (Bloomberg), Thomas Kluyver (European XFEL), Damián Avila (Anaconda, Inc.), Steven Silvester (JP Morgan Chase), Jonathan Frederic (Google), Kyle Kelley (Netflix), Jessica Hamrick (DeepMind), Sylvain Corlay (QuantStack), and Peter Parente (Valassis Digital).  The award and a prize of $35,000 will be presented to the team at the ACM Awards banquet in San Francisco on June 23, 2018.

Source: https://bids.berkeley.edu/perez-project-jupyter-2017-acm-software-system-award

### Thanks very much for your wonderful support.

ATTN: @fperez @minrk @takluyver @Carreau @jasongrout @SylvainCorlay 
Chat at https://gitter.im/jupyter/notebook

**Comment by Carreau** [comment]
Thanks !
we've published some of [our thoughts on the award](https://blog.jupyter.org/jupyter-receives-the-acm-software-system-award-d433b0dfe3a2) and how the whole community deserves it.

**Comment by Carreau** [comment]
(closing as nothing actionable, but feel free to keep commenting.
