### ISSUE TITLE
Problems selecting, copying and pasting

### ISSUE THREAD

**Issue by j3mdamas** [jupyter/help#36]
I am not sure this is strictly related to Jupyter notebooks, but I don't seem to be having the problem in other OS or web applications (CentOS machine). Jupyter version 4.1.0.

On an open notebook, I am finding troubles selecting rows of code. Either using the mouse, or keyboard (Shift+Arrows/Home/End). It always seems to be the first or last row of a snipet of code. When I do manage to select it, and I copy and paste it (Ctrl+C and Ctrl+V), the first (or last) row does not copy...

Nobody else is experiencing this problem?

**Comment by Carreau** [comment]
Hum, I have never seen, or heard of that. 

Do you have any browser extensions ? Does the row appear selected or not ? 
Do you see the same behavior on try.jupyter.org ?

**Comment by j3mdamas** [comment]
Yes, I am on Chrome with extensions. I used try.jupyter.org and same behaviour. I opened Firefox (no extensions) and I saw no problems... So, browser issues? Or weird interaction with extensions?

**Comment by Carreau** [comment]
> Yes, I am on Chrome with extensions. I used try.jupyter.org and same behaviour. I opened Firefox (no extensions) and I saw no problems... So, browser issues? Or weird interaction with extensions?

**might** be weird interaction, but might be an actual bug. Try a new incognito tab. 
I think there is a way to temporarily disable all chrome extensions.

**Comment by j3mdamas** [comment]
I disabled all extensions using a chrome extension to disable them all, and it solved the issue. So it's not Chrome by itself, but some extension. Now, which one is the question.

Well, this is to case specific, maybe it's a non-issue.

**Comment by Carreau** [comment]
> Now, which one is the question.

Binary search ! 

If you find out, please let us know !

**Comment by willingc** [comment]
@carreau @j3mdamas This may be completely unrelated; yet, I will throw it out as a specific Chrome extension that was causing different issues this week. uBlock was the extension. More details in this issue https://github.com/jupyter/notebook/issues/1414

**Comment by j3mdamas** [comment]
I use Ghostery, not uBlock, and it my first try. Pausing the block did not solve, but i'll try disabling it.
@Carreau, what do you mean Binary search? Trial and error one-by-one?

**Comment by willingc** [comment]
@j3mdamas I would turn off half of them and see if it passes or fails. Then take the failing half and halve again until the troublemaker is isolated.

**Comment by j3mdamas** [comment]
Oh, right, that's smart ;)

**Comment by j3mdamas** [comment]
Unless there is more than one troublemaker ahah

**Comment by willingc** [comment]
> Unless there is more than one troublemaker ahah

Let's hope not 😮

**Comment by Carreau** [comment]
> @j3mdamas I would turn off half of them and see if it passes or fails. Then take the failing half and halve again until the troublemaker is isolated.

Yep that's what I meant.

**Comment by j3mdamas** [comment]
I identified it. It's an emoji input extension that I was using: https://chrome.google.com/webstore/detail/emoji-input-by-emojistuff/immhpnclomdloikkpcefncmfgjbkojmh?hl=en-US

Just going to delete it. Issue closed.

**Comment by willingc** [comment]
@j3mdamas Glad you found it. :smile:
