### ISSUE TITLE
Uploading .pynb file to Github

### ISSUE THREAD

**Issue by antoniopieri** [jupyter/help#362]
Hi!

I'm looking to upload a .pynb file to github so that I can share it to somebody who isn't a programmer!

My understanding is that I would then use  https://nbviewer.jupyter.org/ to render the note book. 

Any guidance would be much appreciated :) 

Thanks,

Antonio

**Comment by takluyver** [comment]
Hi! You can put them on Github like any other file - but if you're new to Git and/or Github that might take a bit of getting used to. See https://help.github.com/ for more information about that.

As a simpler alternative, you can put them on [gist](https://gist.github.com/), Github's pastebin. Open the ipynb file in a text editor, select all, copy and paste into gist. Remember to name it with a .ipynb extension.

You're right that you can then use nbviewer, but you may not need to. Github also renders notebooks now - though some bits are cut out for security reasons; you can use nbviewer if that happens.

**Comment by antoniopieri** [comment]
Thanks for your help Thomas!! 

I'll use Gist for now :) 

Have a great day, 

Antonio
