### ISSUE TITLE
How to change the displaly language of modified date

### ISSUE THREAD

**Issue by harupy** [jupyter/help#368]
The image below is how my Jupyter dashbaord looks like. As you can see, the modified dates are in Japanese but I want them to be in English. How can I change them? I use Ubuntu 18.04 LTS and Jupyter 4.4.0.
![screenshot from 2018-06-02 12-10-33](https://user-images.githubusercontent.com/17039389/40878359-030b302c-665e-11e8-8a44-c3beea81d639.png)

**Comment by takluyver** [comment]
I think it goes based on the language set in your browser.

**Comment by harupy** [comment]
Resetting the language in my browser fixed the issue. Thank you.
