### ISSUE TITLE
One-time-token-authentication when running in a docker container

### ISSUE THREAD

**Issue by jonathanrobie** [jupyter/help#369]
I can use one-time-token-authentication when I run directly from the desktop, but not when I run from a container.  How do I fix this?  I am using

When I run Jupyter notebook directly from my desktop (without Docker), the last line assures me that it is `Accepting one-time-token-authenticated connection from ::1` and I can happily paste the URL it supplies into a web browser and authenticate.

When I run it from a container, this message is missing.  The URL is still presented, but authentication does not work when I open it in a web browser.

Here's what the happy path messages look like (when I run directly from the desktop):

```
[C 18:24:18.892 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=5389b6860e9bb8899e767ec6a1`4fd7a47c60cca7af882640
[I 18:24:21.850 NotebookApp] Accepting one-time-token-authenticated connection from ::1
```
But when I use `docker run` to run Jupyter notebook from a container, I get the same messages *except* that there is no messaging telling me that it will accept a one-time-token-authenticated connection.  And it won't.  I have the same problem with `docker run jupyter/scipy-notebook` and when I run a container I built myself.

```
[C 22:38:08.479 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=d86dfe9aff5d99a1cbee526056b2ddcc679f9921ea0256ca
```

**Comment by jonathanrobie** [comment]
The problem was actually something else completely - I wasn't correctly mapping the port to my host.

I'm not sure why the log messages differ, but it doesn't seem to make a difference.

**Comment by yshuolu** [comment]
@jonathanrobie How did you solve this? Did you properly map the ports somehow? Could you please elaborate on your solutions? Thx!

**Comment by laurenfitch** [comment]
> @jonathanrobie How did you solve this? Did you properly map the ports somehow? Could you please elaborate on your solutions? Thx!

I'm having the same problem so it would be great to know what fixed it for you!
