### ISSUE TITLE
Jupyter Notebook Logo and Project Tittle is not showing

### ISSUE THREAD

**Issue by Krishna829** [jupyter/help#375]
At the top Jupyter Logo and Title of the project is not showing. Any Solutions

![screenshot 4](https://user-images.githubusercontent.com/36042569/41548777-82fd1c56-7341-11e8-8a7a-825e60031722.png)

**Comment by takluyver** [comment]
Click view, toggle header.

**Comment by Krishna829** [comment]
OMG its that simple. Thank you
After installing Jupyter I install JupyterThemes and thats when it happened. So i thought its due to that

**Comment by takluyver** [comment]
Themes might be able to affect it, I'm not sure.
