### ISSUE TITLE
Jupyterhub issue

### ISSUE THREAD

**Issue by Lowerit** [jupyter/help#378]
Jupyterhub Troubleshooting

I’ve been troubleshooting this for roughly a total of 20~+ hours, searching for answers, trying different things, reading the proxy logs, and etc. I started at a new job, and began updating the python packages, only to be greeted by the jupyterhub server going down. So I didn’t set any of it up and I’ve just been trying to reverse engineer the whole schema and process.  Any help would be greatly, greatly, appreciated!

My problem: 

I was updating all the python packages in an azure ubuntu server ... When jupyterhub updated from 0.7.~ to 0.9.0, the server stopped working.

So, when I ran the update, I ran it from my home/'username'/file, and jupyterhub happened to be located in the /etc/~ folder on the server.

When the update occurred, it then created in my home/’username’/~ folder, the cookie secret and sqlite files.

When I currently try to run jupyterhub command I get this File:

1.)	```"/usr/local/lib/python3.5/dist-packages/tornado/netutil.py", line 163, in bind_sockets
  sock.bind(sockaddr)
   OSError: [Errno 98] Address already in use```

So here is exactly when the first error occurred, and the errors that were thrown:

1.)	 ```[I 2018-06-21 13:08:29.404 JupyterHub log:100] 200 GET /jupyterhub/hub/api/authorizations/cookie/jupyter-hub-token-‘username’[secret]```

2.)	```[E 2018-06-21 13:09:32.410 ‘username’ web:1590] Uncaught exception GET /jupyterhub/user/‘username’/tree/crawler/analysis/location (my_computers_ip)```

3.)	The errors produced jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'trans'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
`jinja2.exceptions.TemplateNotFound: 500.html`

Fast forward to 2 hours ago [config proxy] 200 GET api/routes was running fine, and now they are not. I assume it is because I tried to edit the jupyterhub_config.py file to see if it would make a difference. Here is the main error thrown from this.

1.)	``` jinja2.exceptions.TemplateNotFound: error.html
and now it's sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: proxies```

So after this took place, the [proxy config] 200 GET stopped it’s fetchall requests.

My hypothesis is that the port used to relaunch the server was bugging out. Since the update occurred while the hub was still running and continued to “run” after all was said and done. I’m sure I will be asked for the config file, and I don’t really have one, as I am not the person who set the jupyterhub up to begin with, and the person who did is gone. 

I am very happy to provide any sort of information possible, and take absolutely any advice! Thanks!

**Comment by willingc** [comment]
@Lowerit Check to see that you do not have a stale proxy still running?

What is the output of `ps -ax | grep configurable`?

**Comment by Lowerit** [comment]
Not really sure where to go from that :/

**Comment by consideRatio** [comment]
@Lowerit I think you should to shut down the proxy now.

The `ps` command @willingc recommended you to use combined with `| grep configurable-http-proxy` found a process running that was using the port that caused the `OSError: [Errno 98] Address already in use`.

So, shut down that process. By running `ps -ax` I learned by inspection that the first number is the process ID. Now, ask that process to shut down with `kill -SIGTERM 2657` or forcefully with the `-SIGKILL` flag instaead.

**Comment by Lowerit** [comment]
Ok awesome thanks I'll try it.

**Comment by Lowerit** [comment]
I'm still getting that error afterward
    OSError: [Errno 98] Address already in use

**Comment by davidbath** [comment]
Looks like you need to track down the process that is listening on that port. 

Another way you can debug this is to use netstat —listen and see if you can identify any jupyter and configurable-http-proxy instances that are still up and listening to ports. Manually kill them off as suggested above and when you are sure nothing is listening in those ports, try starting up jupyterhub again.

**Comment by Lowerit** [comment]
Hi, david, my primary concern is the other ports and users on the server. After killing that port it still wont load and I have a hunch its the :8081 port which is the issue, and I'm not sure how that will effect other users on the ubuntu server.

**Comment by davidbath** [comment]
Ok - so what does netstat report? Which process is using port 8081?

**Comment by Lowerit** [comment]
No direct 8081 processes, but multiple like this : 
75597 ?        S      0:00 links http://127.0.0.1:8081/hub/
 58263 ?        S      0:00 links http://127.0.0.1:8081/hub/admin

. ....  lots of those

**Comment by davidbath** [comment]
That doesn’t look like the output of netstat to me. 

What does 

sudo netstat -nlp | grep :8081

give you?

**Comment by Lowerit** [comment]
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      2280/python3

**Comment by davidbath** [comment]
Ok. So process is 2280, which happens to be python, is listening on 8081 already. 

If you don’t need believe process 2280 to be an old copy of jupyterhub or something related to your work, use the ps command to figure out what process 2280 is and if it is safe to kill or not.

**Comment by Lowerit** [comment]
2280 ?        S      3:45 /usr/bin/python3 /usr/local/bin/jupyterhub --debug --JupyterHub.spawner_class=sudospawner.SudoSpawner

**Comment by davidbath** [comment]
Super! You are getting there!

So you have a copy of jupyterhub already started on port 8081, so when you try and startup a second one it fails to bind to the socket, as it’s already in use. 

I’m guessing it’s reasonable to kill that off, unless someone else is running another jupyterhub on the same server as you!

**Comment by Lowerit** [comment]
thats one of my only concerns. I believe some others may be using jupyter notebooks.
 54696 ?        S      0:01 /usr/bin/python3 /usr/local/bin/jupyter-notebook
 57389 ?        T      0:00 sqlite3 jupyterhub.sqlite
So i'm not sure if killing that will effect them.

**Comment by davidbath** [comment]
Ok - I’m a little confused :) if jupyterhub is up and running already and users are using it, spawning new notebooks etc then .... what’s broken?

**Comment by Lowerit** [comment]
Well, I guess it can only be used locally?

**Comment by davidbath** [comment]
What happens if you go to the hub address? Does it work?

**Comment by Lowerit** [comment]
Just from using links http://127.0.0.1:8000/hub/ . It shows up blank

**Comment by davidbath** [comment]
Cool. Well, if it’s broken now I would say your balance of risk to benefit means you should try killing it and starting it up again.

**Comment by davidbath** [comment]
Did you manage to determine if your configurable-http-proxy was still running? Same diagnostics as above, but a process that contains the name configurable-http-proxy?

**Comment by Lowerit** [comment]
So I killed the configurable-http-proxy. I will kill the other ones now, since it's 5PM and no one will be upset if I disrupt anything

**Comment by davidbath** [comment]
you can probably leave the notebooks running, as their routes should be readded after jupyterhub restarts. I think jupyterhub and configurable-http-proxy have got in a tangle during the accidental upgrade!

**Comment by Lowerit** [comment]
Ok so I just did some fact finding to make sure no one was using it, and I'm guessing that the 4 or 5 processes still running are all stale. I'm going to just kill all of them and try restarting.

**Comment by Lowerit** [comment]
Okay still getting the errors after killing all the processes.

[E 2018-06-27 17:09:28.078 JupyterHub app:1842] Failed to bind hub to http://127.0.0.1:8081/hub/

    OSError: [Errno 98] Address already in use

**Comment by Lowerit** [comment]
So it seems like the configurable http proxy restarts after I try to launch jupyter hub, but that error still persists.

**Comment by davidbath** [comment]
Ok, so can you run the netstat command again and find out what process is using port 8081? It seems that you still have something else that is already using that port (or your process killing didn’t kill off everything).

**Comment by Lowerit** [comment]
yeah lots of local host 8000 and 8001

**Comment by Lowerit** [comment]
tcp        0      0 localhost:35362         localhost:8001          TIME_WAIT 

lots of stuff like that

**Comment by Lowerit** [comment]
Ok, I'm noticing something.. everytime I kill the configurable-http-proxy it restarts itself.

**Comment by davidbath** [comment]
Sure that’s not an old error then? I can’t quite see how the port can already be in use if you cannot see any process using it!

**Comment by Lowerit** [comment]
I'm not sure if you read my last comment about the http config proxy automatically restarting when i kill it

**Comment by davidbath** [comment]
This is jupyterhub keeping it managed, I think. If you kill jupyterhub and the configurable-http-proxy it should stay killed.

**Comment by Lowerit** [comment]
They keep restarting. 

 23373 ?        S      0:00 /usr/bin/python3 /usr/local/bin/jupyterhub --debug --JupyterHub.spawner_class=sudospawner.SudoSpawner
 23383 ?        Ssl    0:00 node /usr/local/bin/configurable-http-proxy --ip 127.0.0.1  --port 8001 --api-ip 127.0.0.1 --api-port 8081 --error-target http://our-website-to-proxy-to:8000/jupyterhub/hub/error

**Comment by Lowerit** [comment]
So when it starts is using:

[I 2018-06-27 17:41:15.693 JupyterHub app:1656] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.0
[I 2018-06-27 17:41:15.694 JupyterHub app:1656] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.0

Should not being using that authenticator?

**Comment by davidbath** [comment]
Ok - then I’m not quite sure why that is. I guess you must have something environment specific like a service manager that is attempting to maintain those services. Which one that is probably depends on which distro you are using and/or how the machine was set up initially. 

However - as a quick check, when they have both auto-restarted, does it work?

**Comment by Lowerit** [comment]
So when I try to go to the website where you can usually login, it's giving me a http 500 error, unable to handle request

**Comment by Lowerit** [comment]
and the log file is telling me there isn't a template.

**Comment by Lowerit** [comment]
Yeah, it's saying no jinja template

**Comment by Lowerit** [comment]
jinja2.exceptions.TemplateNotFound: login.html

**Comment by davidbath** [comment]
Ok - so I think you are now into a config file problem. With two possible issues - (1) that a different config file is being loaded or (2) that you have some settings in your config file that are not compatible with the 0.9 version. 

I’d try and track down which jupyterhub_config.py is being used, and see if you have multiple copies of it on your system. Given you didn’t set it up, you maybe able to work out which is the ‘right’ one by the date, or if you can work out which service manager is spawning jupyterhub this may specify which config file is being used.

**Comment by Lowerit** [comment]
There is only 1 config file on the server, in the /etc/ ,

**Comment by Lowerit** [comment]
Here is the error, it starts with the tornado  



 Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/login.py", line 72, in get
        self.finish(self._render(username=username))
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/login.py", line 41, in _render
        {'next': self.get_argument('next', '')},
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 777, in render_template
        template = self.get_template(name)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 771, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 408, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: login.html

**Comment by davidbath** [comment]
Does your config file attempt to set any values for custom templates?

**Comment by Lowerit** [comment]
## Paths to search for jinja templates.
#c.JupyterHub.template_paths = []

**Comment by Lowerit** [comment]
and
## The Logging format template
#c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'

**Comment by Lowerit** [comment]
Should I take away the hashtag in this segment?

## Class for authenticating users.
#  
#  This should be a class with the following form:
#  
#  - constructor takes one kwarg: `config`, the IPython config object.
#  
#  - is a tornado.gen.coroutine
#  - returns username on success, None on failure
#  - takes two arguments: (handler, data),
#    where `handler` is the calling web.RequestHandler,
#    and `data` is the POST form data from the login page.
#c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'

**Comment by davidbath** [comment]
Only if you want to change it to a different authenticator. 

Curiously it looks like this may be the default auto generated config file. Is there anything it it that suggests it contains the configuration that was set up by whoever you have inherited this from?

Also I think now is the time to figure out what is loading jupyterhub in the first place, and whether it is being called with any particular options.

**Comment by Lowerit** [comment]
Well it might be a default one, but thats the only jupterhub config there is..

**Comment by Lowerit** [comment]
Yeah, well the .conf file is definitely whats doing it automatically 

[program:jupyterhub]
directory=/etc/jupyterhub
command=jupyterhub --debug --JupyterHub.spawner_class=sudospawner.SudoSpawner
user=jupyterhub
autostart=true
autorestart=true
stderr_logfile=/var/log/jupyterhub.log
stdout_logfile=/var/log/jupyterhub.log
~

**Comment by davidbath** [comment]
My concern was whether the previously operating one had been overwritten when you accidentally upgraded and replaced with a default package version. I was just trying to help you determine if this is a ‘point at the right config’ problem or a ‘figure out what the config should be’ kind of problem. 

There are two things I would suggest investigating:

1. It seems that some specific parameters are being passed as command line parameters such as setting the spawner class to be sudoSpawner. What is passing these in? How is jupyterhub being started automatically? This is not standard jupyterhub behaviour so I think it would help to understand your system. 

2. The running process seems to be using /usr/local/bin/python3 but the libraries are loading from python3.5. While there may be nothing wrong at all, it’s worth checking that you don’t have multiple python and/or jupyterhub versions. 

I’m afraid I’ve run out of time (UK time zone) for tonight, but hopefully this can get you a bit closer to understand what your system is trying to do and narrow it down.

**Comment by davidbath** [comment]
Ah cool. Good diagnostics. 

So maybe you can use the date in the jupyterhub config to determine if it’s been freshly created, and perhaps check ‘which jupyterhub’ to help you with the second part.

**Comment by Lowerit** [comment]
What date? I'm not exactly sure what you mean. Also, thanks again for helping me to get this far.

**Comment by consideRatio** [comment]
@davidbath @Lowerit :heartbeat:

**Comment by Lowerit** [comment]
:)  There are multiple python versions in the system.

**Comment by Lowerit** [comment]
The log files from the time the server was created until now have been using python3.5

**Comment by davidbath** [comment]
I just mean check the modify/creation time of your jupyterhub config file. If it’s really recent (like, the day you did the upgrade) then you might assume it got replaced and doesn’t represent the original configuration of the server. If it has an older date on it, then perhaps it has been around since before you did the upgrade, and so perhaps it can be trusted  as a ‘working’ config, at least with the older version of jupyterhub.

**Comment by Lowerit** [comment]
and yeah I see that it's calling to python3

2280 ? S 3:45 /usr/bin/python3 /usr/local/bin/jupyterhub --debug --JupyterHub.spawner_class=sudospawner.SudoSpawner

**Comment by Lowerit** [comment]
So there is this...which I read a few days ago in the changelogs for 0.9.0

The biggest change for 0.9 is the switch to asyncio coroutines everywhere instead of tornado coroutines. Custom Spawners and Authenticators are still free to use tornado coroutines for async methods, as they will continue to work. As part of this upgrade, JupyterHub 0.9 drops support for Python < 3.5 and tornado < 5.0.

**Comment by Lowerit** [comment]
I'm not sure if this means anything for me though

**Comment by Lowerit** [comment]
Actually, it seems like that may very well be the issue.. since the jupyterhub is launched in python3

**Comment by Lowerit** [comment]
So, I still haven't solved it. Any suggestions are much appreciated

**Comment by dhirschfeld** [comment]
In this instance I think `python3` just means some version of `python >= 3` to distinguish it from python2.

You should be able to check exactly what version of Python it is by running it yourself from a terminal:
```
/usr/bin/python3
```
...should start Python which will then print a banner telling you what version of Python it is.

**Comment by consideRatio** [comment]
I have not read everything, but make sure the tornado stuff is installed properly. Also avoid writing `pip install ...` but instead `python3 -m pip install ...` to ensure sanity.

I'm very scared about environments, I've never experienced any joy related to different environments :D

**Comment by willingc** [comment]
@Lowerit Please run the following and post the exact output here.

- `which -a jupyterhub`
- `which -a jupyter`
- `which -a python`
- `which -a python3`
- `python3 -m pip list`

Thanks.

Thanks @consideRatio and @davidbath for troubleshooting help.

**Comment by Lowerit** [comment]
Okay i'm back at it thanks for the advice, i'll post some stuff soon!

**Comment by Lowerit** [comment]
Here are the outputs @willingc requested

~$ which -a jupyterhub
/usr/local/bin/jupyterhub
~$ which -a jupyter
/usr/local/bin/jupyter
~$ which -a python
/usr/bin/python
~$ which -a python3
/usr/bin/python3

~$ python3 -m pip list
Package                         Version               
------------------------------- ----------------------
absl-py                         0.2.2                 
acme                            0.25.1                
alembic                         0.9.9                 
apache-beam                     0.6.0                 
apturl                          0.5.2                 
asn1crypto                      0.24.0                
astor                           0.6.2                 
async-generator                 1.9                   
attrs                           18.1.0                
Automat                         0.7.0                 
avro                            1.8.2                 
backcall                        0.1.0                 
beautifulsoup4                  4.6.0                 
bleach                          1.5.0                 
blinker                         1.3                   
bokeh                           0.13.0                
boto                            2.48.0                
boto3                           1.7.42                
botocore                        1.10.42               
Brlapi                          0.6.4                 
bs4                             0.0.1                 
bz2file                         0.98                  
cachetools                      2.1.0                 
certbot                         0.25.1                
certbot-nginx                   0.25.1                
certifi                         2018.4.16             
cffi                            1.11.5                
chardet                         3.0.4                 
checkbox-support                0.38.0                
chromedriver                    2.24.1                
chromedriver-installer          0.0.6                 
click                           6.7                   
cloud-init                      18.2                  
cmake                           3.11.0                
command-not-found               0.3                   
ConfigArgParse                  0.13.0                
configobj                       5.0.6                 
constantly                      15.1.0                
crcmod                          1.7                   
cryptography                    2.2.2                 
cssselect                       1.0.3                 
cycler                          0.10.0                
cymem                           1.31.2                
Cython                          0.28.3                
decorator                       4.3.0                 
defer                           1.0.6                 
dill                            0.2.8.1               
docutils                        0.14                  
entrypoints                     0.2.3                 
fasteners                       0.14.1                
feedparser                      5.2.1                 
ffmpeg-python                   0.1.12                
funcsigs                        1.0.2                 
future                          0.16.0                
gast                            0.2.0                 
gensim                          3.4.0                 
gitdb2                          2.0.3                 
GitPython                       2.1.10                
google-api-core                 1.2.1                 
google-apitools                 0.5.23                
google-auth                     1.5.0                 
google-auth-httplib2            0.0.3                 
google-chrome                   0.0.0                 
google-cloud-bigquery           1.3.0                 
google-cloud-core               0.28.1                
google-resumable-media          0.3.1                 
googleapis-common-protos        1.5.3                 
googledatastore                 7.0.1                 
grpcio                          1.12.1                
guacamole                       0.9.2                 
h5py                            2.8.0                 
html5lib                        0.9999999             
httplib2                        0.11.3                
hyperlink                       18.0.0                
idna                            2.7                   
incremental                     17.5.0                
ipykernel                       4.8.2                 
ipython                         6.4.0                 
ipython-genutils                0.2.0                 
ipywidgets                      7.2.1                 
itsdangerous                    0.24                  
jedi                            0.12.0                
Jinja2                          2.10                  
jmespath                        0.9.3                 
josepy                          1.1.0                 
jsonpatch                       1.23                  
jsonpointer                     2.0                   
jsonschema                      2.6.0                 
jupyter                         1.0.0                 
jupyter-client                  5.2.3                 
jupyter-console                 5.2.0                 
jupyter-core                    4.4.0                 
jupyterhub                      0.9.0                 
Keras                           2.2.0                 
Keras-Applications              1.0.2                 
Keras-Preprocessing             1.0.1                 
kiwisolver                      1.0.1                 
language-selector               0.1                   
louis                           2.6.4                 
lxml                            4.2.1                 
Mako                            1.0.7                 
Markdown                        2.6.11                
MarkupSafe                      1.0                   
matplotlib                      2.2.2                 
mistune                         0.8.3                 
mock                            2.0.0                 
monotonic                       1.5                   
murmurhash                      0.28.0                
nbconvert                       5.3.1                 
nbformat                        4.4.0                 
ndg-httpsclient                 0.5.0                 
nltk                            3.3                   
nodejs                          0.1.1                 
notebook                        5.5.0                 
numpy                           1.14.5                
oauth2client                    3.0.0                 
oauthlib                        2.1.0                 
olefile                         0.45.1                
onboard                         1.2.0                 
OpenCC                          0.2                   
opencv-python                   3.4.1.15              
optional-django                 0.3.0                 
packaging                       17.1                  
padme                           1.1.1                 
pamela                          0.3.0                 
pandas                          0.23.1                
pandocfilters                   1.4.2                 
parsedatetime                   2.4                   
parsel                          1.4.0                 
parso                           0.2.1                 
pbr                             4.0.4                 
pexpect                         4.6.0                 
pickleshare                     0.7.4                 
Pillow                          5.1.0                 
pip                             10.0.1                
plainbox                        0.38.0                
plotly                          2.7.0                 
pluggy                          0.6.0                 
preshed                         1.0.0                 
prettytable                     0.7.2                 
prometheus-client               0.2.0                 
prompt-toolkit                  1.0.15                
proto-google-cloud-datastore-v1 0.90.4                
protobuf                        3.6.0                 
ptyprocess                      0.5.2                 
py                              1.5.3                 
pyasn1                          0.4.3                 
pyasn1-modules                  0.2.1                 
pycairo                         1.17.0                
pycparser                       2.18                  
pycups                          1.9.73                
pycurl                          7.43.0                
Pygments                        2.2.0                 
pygobject                       3.20.0                
PyICU                           1.9.2                 
PyJWT                           1.6.4                 
pyOpenSSL                       18.0.0                
pyparsing                       2.2.0                 
pyRFC3339                       1.1                   
PySceneDetect                   0.3.6                 
pyserial                        3.0.1                 
pytesseract                     0.2.2                 
python-apt                      1.1.0b1+ubuntu0.16.4.1
python-dateutil                 2.7.3                 
python-debian                   0.1.32                
python-editor                   1.0.3                 
python-oauth2                   1.1.0                 
python-systemd                  231                   
pytz                            2018.4                
pyxdg                           0.25                  
PyYAML                          3.11                  
pyzmq                           17.0.0                
qtconsole                       4.3.1                 
reportlab                       3.3.0                 
requests                        2.19.1                
requests-toolbelt               0.8.0                 
requests-unixsocket             0.1.5                 
rsa                             3.4.2                 
runipy                          0.1.5                 
s3transfer                      0.1.13                
scikit-learn                    0.19.1                
scipy                           1.1.0                 
seaborn                         0.8.1                 
selenium                        3.12.0                
Send2Trash                      1.5.0                 
sessioninstaller                0.0.0                 
setuptools                      39.2.0                
simplegeneric                   0.8.1                 
six                             1.11.0                
sklearn                         0.0                   
smart-open                      1.5.7                 
smmap2                          2.0.3                 
SQLAlchemy                      1.2.8                 
ssh-import-id                   5.6                   
sudospawner                     0.5.2                 
system-service                  0.3                   
tensorboard                     1.8.0                 
tensorflow                      1.8.0                 
tensorflow-tensorboard          1.5.1                 
termcolor                       1.1.0                 
terminado                       0.8.1                 
testpath                        0.3.1                 
tornado                         5.0.2                 
tox                             3.0.0                 
tqdm                            4.23.4                
traitlets                       4.3.2                 
Twisted                         18.4.0                
ubuntu-drivers-common           0.0.0                 
ufw                             0.35                  
unattended-upgrades             0.1                   
unity-scope-calculator          0.1                   
unity-scope-chromiumbookmarks   0.1                   
unity-scope-colourlovers        0.1                   
unity-scope-devhelp             0.1                   
unity-scope-firefoxbookmarks    0.1                   
unity-scope-gdrive              0.7                   
unity-scope-manpages            0.1                   
unity-scope-openclipart         0.1                   
unity-scope-texdoc              0.1                   
unity-scope-tomboy              0.1                   
unity-scope-virtualbox          0.1                   
unity-scope-yelp                0.1                   
unity-scope-zotero              0.1                   
urllib3                         1.23                  
usb-creator                     0.3.0                 
virtualenv                      16.0.0                
w3lib                           1.19.0                
WALinuxAgent                    2.2.20                
wcwidth                         0.1.7                 
webencodings                    0.5.1                 
Werkzeug                        0.14.1                
wheel                           0.31.1                
widgetsnbextension              3.2.1                 
wrapt                           1.10.11               
xdiagnose                       3.8.4.1               
xkit                            0.0.0                 
XlsxWriter                      0.7.3                 
zope.component                  4.4.1                 
zope.event                      4.3.0                 
zope.hookable                   4.2.0                 
zope.interface                  4.5.0

**Comment by Lowerit** [comment]
Also,
/usr/bin$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 

It seems to fine there.

**Comment by Lowerit** [comment]
and the tornado is >5.0

**Comment by willingc** [comment]
What is the output of `ls -al usr/local/bin | grep python`? I think you may have multiple python3 versions installed on your system.

**Comment by Lowerit** [comment]
/$ ls -al usr/local/bin | grep python
-rwxr-xr-x  1 root root     228 Jun 21 12:51 ipython
-rwxr-xr-x  1 root root     228 Jun 21 12:51 ipython3

**Comment by Lowerit** [comment]
So again this is an Azure server shared by about 7 people. There are python2.7, python3, python3.5, and python3.6 directories somewhat scattered.

**Comment by minrk** [comment]
This error:

> no such table: proxies

suggests that the jupyterhub version and database have gotten confused. There is no `proxies` table in jupyterhub > 0.7.

Is it possible that jupyterhub was still running while it was upgraded?


In terms of processes being recreated: there are two things responsible for restarting processes.

1. When JupyterHub starts the proxy, it will restart it any time it stops
2. since supervisor is managing jupyterhub, any time jupyterhub stops, supervisor will restart it

The way to stop jupyterhub if it's run via supervisor is:

    supervisorctl stop jupyterhub

then you can check what supervisor thinks is running with:

    supervisorctl status jupyterhub

Once supervisor thinks jupyterhub shouldn't be running, this is the time to check if there are any leftover processes and kill rogue `jupyterhub` and `configurable-http-proxy` processes. Once you are confident nothing is running, you can begin trying to upgrade (or simply move out of the way, if you want to start fresh) the jupyterhub database, either with `jupyterhub upgrade-db` or `mv jupyterhub.sqlite jupyterhub.sqlite.save-$(date +%Y-%m-%d.%H.%M.%S)`.

At this point, you can try to resume jupyterhub with:

    supervisorctl start jupyterhub

**Comment by Lowerit** [comment]
Thanks a lot that last command helped greatly.

I decided to just bring everything back down to the old versions and the proxy website is working again, just having trouble getting the actual notebooks going.

**Comment by Lowerit** [comment]
I guess we'll be getting an azure admin pretty soon, so I figure I'll just get it to run again for now.. lol

This is the current error i'm getting the file:
[W 2018-07-02 09:13:50.290 JupyterHub pages:32] Disallowing redirect outside JupyterHub: ''

So what would i change to fix that?

**Comment by Lowerit** [comment]
I see that the difference between past successful logins is that it directs here:

--hub-api-url="http://127.0.0.1:8081/jupyterhub/

Currently however it is directing to here:

--hub-api-url="http://127.0.0.1:8000/

**Comment by minrk** [comment]
Are you setting the hub api URL in any configuration? It is odd that these would have multiple values, and very rare that these should be set via config.

**Comment by Lowerit** [comment]
I actually fixed that part! Thanks for reaching out.

Now my issue is that other users can login fine from our login proxy link.

However,  I cannot, I am getting the errors

[D 2018-07-02 14:39:48.583 JupyterHub spawner:63] Spawning ['sudo', '-u', 'myusername', '-nH', '/usr/local/bin/sudospawner']
sudo: a password is required
[E 2018-07-02 14:39:48.598 JupyterHub spawner:83] Failed to get JSON result from mediator: ''
[E 2018-07-02 14:39:48.600 JupyterHub user:245] Unhandled error starting myusername's server: substring not found
E 2018-07-02 14:39:48.634 JupyterHub web:1591] Uncaught exception POST  (LOTS OF INFORMATION WITH PROXY COMMANDS) 
      (File usr/ .....)
      ( ......  ......... )
       ( ......  ......... )
      File "/usr/local/lib/python3.5/dist-packages/sudospawner/spawner.py", line 80, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found

**Comment by Lowerit** [comment]
Another guess would be I need to setup a virtualenv in my directory and install kernels there... or ..

**Comment by minrk** [comment]
If sudo asks for a password that means that the sudoers file is not setup correctly to give the hub user access to launch sudospawner as your username. If you followed [these steps](https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) that would mean that `myusername` needs to be in the JUPYTER_USERS list, e.g.

```bash
Runas_Alias JUPYTER_USERS = myusername, otherusername

# the command(s) the Hub can run on behalf of the above users without needing a password
# the exact path may differ, depending on how sudospawner was installed
Cmnd_Alias JUPYTER_CMD = /usr/local/bin/sudospawner

# actually give the Hub user permission to run the above command on behalf
# of the above users without prompting for a password
jupyterhub ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD
```

**Comment by Lowerit** [comment]
Thank you all very much for your help and support.
