### ISSUE TITLE
Additional Checkpoint Metadata

### ISSUE THREAD

**Issue by AlecAivazis** [jupyter/help#39]
Hey again,

Some background: As I've mentioned a few times, I'm working on a custom checkpoint solution. One thing that I want to add is a "commit message" so that users can provide more context for the actual checkpoint. 

My question has 2 parts:

1. I need to be able to give the user a way to provide this message. Is there a way to modify the checkpoint creation behavior (for example, if i click File > Save and Checkpoint) so that I can bring up a dialog box and prompt the user?
2. I want to show this commit message in the checkpoint dropdown (File > Revert to Checkpoint). Is there a way to modify the representation of the checkpoints in this menu? I found [this](https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/notebook/static/notebook/js/menubar.js#L358) part of the templates which seems to indicate that its hardcoded, but I'm probably missing something.

**Comment by minrk** [comment]
There is not an existing extension point for those two things that I'm aware of. We would need to change the checkpoints API to allow additional information.

**Comment by AlecAivazis** [comment]
Thanks for the quick reply @minrk. I was worried that was the case. 

Do you think you could give me a tip on how to best add that bit of customizability to the API? I'm getting sort of lost looking for the appropriate place.
