### ISSUE TITLE
The Jupyter notebook that never happened

### ISSUE THREAD

**Issue by JohnStone2017** [jupyter/help#397]
Last year I bought Mathematica and found it slowed me down compared to doing math with pencil and paper, on account of the organization of its documentation.

I tried maxima, but it apparently doesn't know that the power series of log (1 + x) sums to log(1 + x), so it is useless to me.

I read about Sympy and spent some months porting my Mathematica notebooks to Jupyter and Sympy. Jupyter is excellent. Sympy is a disaster, and I was defrauded into using it by biased comparisons between it and other computer algebra systems. Sympy is a regression from maxima, which is old and open source. Sage doesn't work with Python 3, which makes it appear to be a dead project.

I will buy Maple today, and start the process of porting my Jupyter notebooks to Maple. This will teach me to trust open source software developers.

**Comment by takluyver** [comment]
This is a forum for getting help with Jupyter.

If you have questions or *constructive* criticism about Sympy or Sage, those projects have their own mailing lists you can use.

If you just want to have a rant about any of these projects, or about open source software in general, feel free to write down your thoughts with pencil and paper.

**Comment by JohnStone2017** [comment]
I don't need to use pencil and paper, you autistic faggot. I'm not "just ranting". I have an A.I. and engineering degree from Stanford and a six-digit budget for my current project. It's going to competent developers not you.

**Comment by takluyver** [comment]
Your post was a textbook example of a rant.

I see you were already warned about Sympy's code of conduct. [Jupyter has one too](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md), and your reply pretty clearly violates it, whether or not your original post did.
