### ISSUE TITLE
download hook for customized kernel 

### ISSUE THREAD

**Issue by BoPeng** [jupyter/help#40]
Is there any hook/API for a customized kernel to control how ipynb is saved? I am working on a kernel named sos and I found that Download as -> SoS (.sos) merely saves all the sources in code cells, ignoring cell index and all the markdown cells. It would be helpful if the kernel can jump in and save some more information.

In addition, one of the biggest concerns I have with using jupyter is version control of the scripts. It would be really helpful to save .ipynb file in a stripped down version without result cells. Something like

```
%cell markdown
# header stuff

%cell code 1
read.table('input.txt')

%cell code 2
...
```

with cell contents exactly as what users input into cells. I do not even need to save in .sos format if such a format exists.

**Comment by minrk** [comment]
Yes, the language_info reply from a kernel can use a custom exporter for the script-export. This must be an nbconvert Exporter, and should be an importable Python class. Your kernel_info_reply should look like this:

```python
{
  'language_info': {
    'nbconvert_exporter': 'soskernel.SoSExporter',
    ...
  },
  ...
}
```

**Comment by BoPeng** [comment]
I followed your suggestion but it did not work. I traced back to `nbconvert/exporters/script.py` and found that

```
    def from_notebook_node(self, nb, resources=None, **kw):
        langinfo = nb.metadata.get('language_info', {})
        
        # delegate to custom exporter, if specified
        exporter_name = langinfo.get('nbconvert_exporter')
        if exporter_name and exporter_name != 'script':
            self.log.debug("Loading script exporter: %s", exporter_name)
            from .export import exporter_map
            if exporter_name not in self._exporters:
                Exporter = exporter_map[exporter_name]
                self._exporters[exporter_name] = Exporter(parent=self)
            exporter = self._exporters[exporter_name]
            return exporter.from_notebook_node(nb, resources, **kw)
```

`exporter_name` is indeed loaded from my language definition, however, `exporter_map` only has `['slides', 'script', 'latex', 'html', 'rst', 'python', 'markdown', 'notebook', 'custom', 'pdf']` so the `Exporter = exporter_map[exporter_name]` caused an `KeyError`. I am using `nbconvert 4.1.0 for py35` shipped with anaconda 3. Should I use another version of `nbconvert`?

**Comment by minrk** [comment]
It must be a full importable class name, such as 'mypackage.MyClass'. You may need to upgrade to nbconvert 4.2.

**Comment by BoPeng** [comment]
Thanks Min. I upgraded to nbconvert 4.2 and everything is working now.

Is there by any chance an import API to import `.sos` files to jupyter notebook? Right now, open `.sos` just import the script as a text file. It would be great to be able to select a kernel to open the file, or I can change my format to allow Jupyter to know what kernel to use to import.

**Comment by takluyver** [comment]
There's no import functionality at the moment - it's just uploading files to the notebook directory. You can use a separate tool to convert a file to a notebook (the nbformat package is useful for constructing notebooks programatically).

**Comment by BoPeng** [comment]
Thanks. I have commands to convert between `.sos` and `.ipynb` (using `nbformat`) but it would be nice to be able to import directly from jupyter.

**Comment by Carreau** [comment]
No you have to use something similar to [ipymd](https://github.com/rossant/ipymd) which is a custom content manager, and know how to load the `.sos` as `.ipynb`.

**Comment by takluyver** [comment]
It's not a crazy idea to add some kind of one-way import plugins as a separate thing from pluggable contents managers, though.
