### ISSUE TITLE
Ipynb viewer for Android

### ISSUE THREAD

**Issue by nandanraj56** [jupyter/help#423]
I want to make a ipynb viewer for Android to make it easier to view notebook files. Is this file format open source? I will not be in trouble if i later wants to publish it on play store?

**Comment by jasongrout** [comment]
The file format is definitely open source: https://nbformat.readthedocs.io/en/latest/

Here are the branding/trademark guidelines for Jupyter (for when you are branding your app): https://github.com/jupyter/governance/blob/master/trademarks.md

Good luck!
