### ISSUE TITLE
jupyter notebook and jupyter console depend on diffrent versions of prompt-toolkit

### ISSUE THREAD

**Issue by talvdav** [jupyter/help#437]
Hi,

i have python 3.7 installed.
I installed jupyter like so:

python -m pip install --upgrade pip
python -m pip install jupyter

i get the following error message:

ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.

so jupyter notebook is broken now but jupyter console works. (witch i don't care for= 

if i do:

python -m pip install --upgrade prompt-tookit

i get:
jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.5 which is incompatible.

now jupyter console is broken but jupyter notebook works.

**Comment by minrk** [comment]
This is fixed by jupyter-console 6
