### ISSUE TITLE
Offline installations.....Possible?

### ISSUE THREAD

**Issue by mymlact** [jupyter/help#44]
Hi Everyone,

I tried posting this via sending an email to jupyter@googlegroups.com, but it bounced, so I apologize if this isn't the correct venue.

I am trying to install jupyterhub in an enterprise environment on RHEL
6.7 systems with no connectivity.

I've read through all of the docs and don't see a way to do an "offline"
installation.  Is there a way to perform an installation without having
pip and npm or git reach out to the internet?

I did see some notes about anaconda, but that looked to only be for the client side, correct me if i'm wrong.

Additionally, everything seemed to be focused towards Ubuntu, any rpm based instructions?

Thanks

Thomas

**Comment by minrk** [comment]
Conda can do [offline installation](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/x2DVu-Y4vhQ) if you fetch the packages you need, you can move over those tarballs to the offline machine. If you include conda-forge as a source, all dependencies, both Python and node, are packaged with conda. You can also maintain your own [channel](http://conda.pydata.org/docs/custom-channels.html) on the offline machine of the packages you want installable.

**Comment by willingc** [comment]
> If you include conda-forge as a source

@mymlact: If you are not familiar with conda-forge, it's a collection of community managed conda packages. https://conda-forge.github.io

To add conda-forge to your conda channels:

    conda config --add channels conda-forge

**Comment by bollwyvl** [comment]
> disclosure: i work at the company behind Anaconda, Continuum Analytics

@mymlact: Another tool for this kind of thing is [constructor](https://github.com/conda/constructor): it's how the anaconda team builds the distribution installers you get off continuum.io. You can basically build your own Mymlactaconda... a lot of the key things in the stack are in defaults, but yeah, you'll definitely want to include `conda-forge`.

You end up with a giant `sh` targeting `/bin/bash`, though, not an rpm... and i totally understand the perspective of wanting to manage deployment stuff with the system package manager. My rpm-building-days are a bit out of sync now (last did so on 5!) but I imagine the content of that `sh` could be massaged into an rpm.

Either way, you'd then have a repeatable, if not reproducible (timestamps! gah!), hands-off way to get to a single file Outside that would populate the `root` conda environment Inside. You'd then probably want to manage your specific deployment in a second environment, such that you could go into downtime, update the root environment, then update the deps without hosing any config you had... but now we're getting into the ops side, where I usually have to duck as real sysadmins throw things at me.

Of course, the other way to go is containers. If you're on RHEL7, you should have pretty good support for those. There are a bunch of [pre-built](https://github.com/jupyter/docker-stacks) images that you could sneakernet on in. But yeah, all of those are going to be debian-based, or at best centos-based. However, most of the steps would end up being similar on RHEL+friends: establish sane unicode/build environment, get funky un-condable things, install conda, install things, install the things your user wants.

**Comment by minrk** [comment]
@bollwyvl I was looking for constructor for this, but couldn't remember its name and couldn't find it by Googling. I knew it existed!

**Comment by mymlact** [comment]
Thanks to everyone for the assistance.

I eventually used the conda-forge method, manually downloaded the packages needed (configurable-http-proxy, libgcc, ncurses, nodejs, pamela and jupyterhub), moved them to the offline system and did local installs using conda.  
*** initially i did this on an online machine and it pulled in the packages, later I couldn't find the libgcc package offline so I just moved it from the system where I did the online install ***

Thanks again

Thomas

**Comment by minrk** [comment]
Glad you got it working!

**Comment by mohanamurali7** [comment]
Though, the issue is closed, just thought of adding the instructions I had followed to install Jupyterhub along with configurable-http-proxy without using npm installs. Could do everything with the help of conda (Thanks to the conda - as it can get and install all the needed packages... even non Python packages. ) I have put the details in the following link:
https://mohanamuraligurunathan.blogspot.in/2018/04/jupyterhub-offline-install-without.html

**Comment by takluyver** [comment]
Thanks!

**Comment by bollwyvl** [comment]
I do like the idea of at some point putting together a non-docker mechanism that can bring the whole shooting match of a JupyterHub.

It's another thing to distribute, but even the excellent post by @mohanamurali7 points out that the number of fiddly bits is still pretty high for someone who just wants to get Hub going on an offline box.

Constructor might be able to answer the mail, though there are a few issues, which may or may not be relevant for Hub:
- [`noarch: python`](https://github.com/conda/constructor/issues/86) (though there appear to be [workarounds](https://github.com/conda/constructor/issues/86#issuecomment-358895352))
- [features](https://github.com/conda/constructor/issues/77) (not sure if this is an issue)

**Comment by FukoH** [comment]
Could you please tell us where are the downloaded packages and what is the format of them?A tar.bz file or a directory containing all necessary files?  I just can't find where are them after using  `conda install --download-only`  @mymlact
