### ISSUE TITLE
How to pass configuration options to nbconvert --execute?

### ISSUE THREAD

**Issue by mgeier** [jupyter/help#45]
I've never really understood how the Jupyter configuration system (all this "traitlets" stuff) works.
Now I have a concrete question and I hope I'll get an answer which will help shed some light on this.

I'm interested in the `InlineBackend.figure_formats` option ([some docs](https://ipython.org/ipython-doc/3/api/generated/IPython.display.html#IPython.display.set_matplotlib_formats)). I know how to use it within a Jupyter notebook, e.g.

```python
%config InlineBackend.figure_formats = {'png', 'pdf'}
```

... and I know how to use it in a Jupyter config file.

But what if I want to pass the option to `nbconvert --execute`?

Actually, that's not enough, I'd like to pass it programmatically from within Python code to `nbconvert`'s `ExecutePreprocessor` ([some docs](http://nbconvert.readthedocs.io/en/latest/api/preprocessors.html#nbconvert.preprocessors.ExecutePreprocessor)).

I saw in the source code that there is a traitlet named `extra_arguments` and it looks like it could be helpful, but I don't know how to use it.

How can I pass the above config option to the `ExecutePreprocessor` constructor?

**Comment by takluyver** [comment]
`InlineBackend` is part of *IPython's* config, not something that you'd set on Jupyter. Only the kernel knows about that. However, you can pass it to the kernel in the command line arguments through the `extra_arguments` traitlet, as you spotted. It should look like this:

```python
ExecutePreprocessor(..., extra_arguments=["--InlineBackend.figure_formats={'png', 'pdf'}"])
```

**Comment by mgeier** [comment]
Thanks for the very quick answer!

That's actually something I tried, but it doesn't seem to have the desired (or any) effect!

It's hard to tell what's going on, because even if I deliberately misspell the option, no error is raised.

What else could I try?

And just out of curiosity, how would the argument to `nbconvert --execute` look like?

**Comment by takluyver** [comment]
Hmm, that's curious. Does setting the option in `ipython_kernel_config.py` work? You might need to double up the `{}` braces or something - I'm not exactly sure about the command line handling.

That option can't currently be passed to nbconvert from the command line: `extra_arguments` isn't configurable. We could make it configurable, but the escaping to pass it through correctly would probably be icky.

**Comment by mgeier** [comment]
Sorry, I messed it up!
It did actually work initially, but I clumsily made another error so it looked like it didn't work.

So everything is fine and the thing I initially tried was actually the right thing to do.

The only thing which would have helped me discovering how the options are supposed to be passed, would be to have an error raised when an unsupported option is given.
But I guess that's not possible?

About passing the option to `nbconvert` on the command line: that's actually not so important, since apparently it honors the settings in `ipython_kernel_config.py`.

@takluyver Thanks for your help and sorry for the noise!

**Comment by mgeier** [comment]
FYI, the reason why I was asking: https://github.com/spatialaudio/nbsphinx/pull/48.

**Comment by takluyver** [comment]
No problem. :-)

Unfortunately, I don't think it's possible to throw an error on unrecognised arguments, because of the way the config system works: we load config from config files and the command line, and then pass it around to the various pieces which use it. So no one piece knows what all the options are.
