### ISSUE TITLE
Guidlines for Start working with Jupiter

### ISSUE THREAD

**Issue by IlanHindy** [jupyter/help#459]
Hi,
I am a computer science student.
I know python pretty well.
I want to use Jupiter as a learning tool.
What I am looking is guidelines for the Markdown (Mainly on what is the easiest way).
The following are the needs:
Combine Right to left text with Left to write text. in one document.
Easy (If possible What you see is What you get) Markdown editing.
Insert formulas
Different Text styles.
The Second thing is that I am looking for easy way to combine interactive programs (like dialogs etc).
I can think of a solution of embedding regular python dialogs (like PySide2 dialogs) into the code.
Is there another (maybe 'Built in' option).
Finally can you recommend of the best way to get help
The best documentation reference and examples that not needs exhausting search for small problems/solutions. 
Tutorial bank
You tube channels 
etc.
Thanks,
Ilan

**Comment by minrk** [comment]
[here](https://guides.github.com/features/mastering-markdown/) is a good markdown reference. You can use something like hackmd.io to get side-by-side rendering of markdown. JupyterLab can do this as well.

For interactive controls in the notebook, [ipywidgets](https://ipywidgets.readthedocs.io) are probably what you are after.

**Comment by IlanHindy** [comment]
Thanks
