### ISSUE TITLE
Win Error 3 system cannot find the path secified

### ISSUE THREAD

**Issue by sean13** [jupyter/help#5]
I did a fresh installation of Anaconda and simply tried to open a Jupyter notebook. It resulted in a long error saying it cannot find the config file. 

FileNotFoundError: [WinError 3] the system cannot find the file path specified: 'P:\\

If I run "jupyter --paths" it results in:
config:
P:\username\.jupyter
C:\users\username\AppData\Local\Continuum\Anaconda3\etc\jupyter
C:\ProgramData\jupyter
data:
C:\users\username\AppData\Roaming\jupyter
C:\users\username\AppData\Local\Continuum\Anaconda3\share\jupyter
C:\ProgramData\jupyter
runtime:
C:\users\username\AppData\Roaming\jupyter\runtime

Most of these locations no not exist on my computer. I don't even have anything mapped to P? Is there a way to point jupyter to the right config file, and where is it stored?

**Comment by willingc** [comment]
@sean13 If you run the following command ``jupyter notebook --debug``, does the notebook open? If not, would you mind entering the information printed out in the console when running that command. Thanks.

**Comment by sean13** [comment]
![2016-04-02 20-18-02_anaconda prompt](https://cloud.githubusercontent.com/assets/18238509/14230521/a62d6558-f910-11e5-8e10-5b99f67533d1.png)
The same printout as before. Please find a picture attached as a .png

**Comment by takluyver** [comment]
I'd guess that you have some erroneous environment variables set. Check for
HOME and things beginning with HOME.

**Comment by sean13** [comment]
Thanks! It was set to P:\User. I switched it to C:\temp and the notebook seemed to open! 

You guys are great!

**Comment by Carreau** [comment]
>  I switched it to `C:\temp`

You might want not to leave it as `C:\temp`, I don't know the rules of file persistence in it, but it's likely to cause trouble.

**Comment by sean13** [comment]
what do you recommend?

**Comment by sean13** [comment]
![2016-04-02 21-02-21_program manager](https://cloud.githubusercontent.com/assets/18238509/14230690/4f5b2778-f916-11e5-9ceb-9f9f9e2e6420.png)
@Carreau you are right, it is complaining about file permissions when I try to create a new notebook. I also tried C:\Users\Username with the same error

**Comment by takluyver** [comment]
I don't think `HOME` is normally set on Windows at all - there may be `HOMEDRIVE` and `HOMEPATH` instead. I'd suggest seeing what happens if you remove the `HOME` environment variable completely.

**Comment by sean13** [comment]
![permission denied](https://cloud.githubusercontent.com/assets/18238509/14250816/fc554d22-fa34-11e5-92f4-177d9eb74184.png)
I removed HOME and it's still not letting me create a new notebook

**Comment by willingc** [comment]
Hi @sean13, Are you still getting the same output in the console as you posted before? https://cloud.githubusercontent.com/assets/18238509/14230690/4f5b2778-f916-11e5-9ceb-9f9f9e2e6420.png

**Comment by sean13** [comment]
Hi @willingc I did a restart and I can create a new notebook! Thanks everyone for helping with this issue!

**Comment by willingc** [comment]
@sean13 I'm glad that it's working :+1: I'll close the issue. You are very welcome! We're glad that we could help :smile:
