### ISSUE TITLE
No output in Lab when recycling WebGL contexts

### ISSUE THREAD

**Issue by janba** [jupyter/help#501]
Dear Jupyter Community,

I have a WebGL related issue that is handled with more grace in notebook than Lab.

I develop a Plot.ly and Jupyter based tool and (really) enjoy the ability to have WebGL graphics from Plot.ly shown inside a Jupyter Notebook. Of course, there are only so many WebGL contexts, and when I run out, I get this message in Safari's developer console.

There are too many active WebGL contexts on this page, the oldest context will be lost.

this is the same in notebook and lab, but in Jupyter Lab  I also get this message right in the output from the cell:

Javascript Error: null is not an object (evaluating 'scene.container.parentNode.removeChild')

_instead_ of the graphics. So, it seems to me that Notebook handles the loss of context in a more graceful manner even if possible the problem is in the Plotly javascript. I am honestly not sure, but it would be great if Lab had the same graceful behaviour as notebook.

Best 
Andreas

**Comment by jasongrout** [comment]
Can you open an issue in the jupyterlab repo with some sample code reproducing the issue? (Perhaps you don't need a webgl context - perhaps any js error will have the same effect? I don't know...)

**Comment by janba** [comment]
Thanks. Yes I will do that. It is possible to reproduce it using a five line script that uses only Plotly.
