### ISSUE TITLE
python2 kernel ImportError «jupyter_client»

### ISSUE THREAD

**Issue by tgerbier** [jupyter/help#52]
Hi,
I am running jupyter on a linux arch. I have both python2 and python3, ipython2 and ipython3 installed.

`jupyter-kernelspec list
Available kernels:
  python3    /usr/local/share/jupyter/kernels/python3
  python2    /usr/share/jupyter/kernels/python2
`

and when I tried to execute the python2 kernel:
`[I 16:36:02.191 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 0b399212-5976-4fb6-b812-825a46fd35c2 restarted
/usr/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/IPython/kernel/__init__.py", line 31, in <module>
    from ipykernel import comm, inprocess
  File "/usr/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/lib/python2.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
ImportError: No module named jupyter_client
`

Seems that there is no jupyter_client module for python2.7 ???

Am I doing anything wrong ?

**Comment by Carreau** [comment]
I guess this has been solved since this is inactive. Thanks!
