### ISSUE TITLE
Kernel doesn't connect with Tornado 6.0.0

### ISSUE THREAD

**Issue by aneroid** [jupyter/help#527]
Just did an upgrade of all my packages and Jupyter stopped connecting to the Python3 kernel. Tornado got upgraded from 5.1.1 to 6.0.0 so uninstalled 6 and re-installed 5, working again.

Also (fyi), saw this error in the console:

    zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited

But I don't think pyzmq==18.0.0 is the cause since it works with that (as well as 17.1.2 previously).

**Comment by aneroid** [comment]
Just saw this in the Jupyter repo: jupyter/jupyter#401
Issue is probably more appropriate there. Closing this one.

**Comment by Yooke** [comment]
same problem
