### ISSUE TITLE
Calling a JS function from a python script repetitively may be causing a memory leak?

### ISSUE THREAD

**Issue by khbilen** [jupyter/help#54]
I execute a python script in a notebook cell, which calls a JS function repetitively. It is WebGL application and a long code. Just to keep it simple, it looks like the folowing. The JSfunction updates an attribute of an object, and then the whole graphic is redrawn. Without the update, there is no memory increase.

```python
while True:
        jso = Javascript("someJSfunction()")
        IPython.display.display_javascript(jso)                // to be able to see the visual output
```

When I look at the memory usage from the Windows Task Manager, I see memory usage is increasing. At first it goes up, and then down (posssibly garbage cleaning), then up, and down again; but after a kind of "threshold", it goes up, and never comes back, resulting at performance degredation.

I thought multiple jso's keep up building and causing the memory leak. Added a new line at the bottom of the loop - del jso - to delete it after display. Script failed to work, and I understand it is not advised tod elete an object, and let the garbage collector do it, but still I am suspicious.

Then I tried several other ways, eliminating  the jso variable, by combining the two lines into one:

```python
IPython.display.display_javascript(Javascript("someJSfunction()"))
```

I got the same problem. Then somewhere I saw there is a   `get_ipython().runcode`    function, and tried:

`get_ipython(runcode('IPython.display.display_javascript(Javascript("someJSfunction()"))')` with same result. ( I am not sure whether executing the code directly in the cell, or with runcode option is faster).

Is it really abusing the Javascript command, to use it over and over again; not intended and not suggested for that kind of usage? Or is it an expected result to have an increasing memory due to ... ?
Any suggestions to do it more effectively?

**Comment by khbilen** [comment]
I made a simple test. Instead of using my programs, I wrote a simple HTML with a small JS function in it, iterating a number and writing it as a header on the browser:

<html>
<head>
<meta charset="utf-8">
<title>Test</title>

<script type="text/javascript">

function incrementNumber(number) {
     number += 1;
     document.getElementsByClassName("pagetitle")[0].innerHTML = "Goodbye " + number;
     }

</script>
</head>

<body >
<h4 class="titlearea win-type-ellipsis" id="title">
     <span class="pagetitle" >
            Hello
     </span>
</h4>                                     
    <br/></body>
</html>

Then execute this HTML file on a notebook cell via Javascript command:

from IPython.display import Javascript, display_javascript, HTML
from time import sleep

HTML(open("JSfunction.html", "r").read())

and finally call this function by the python function in a loop:

def callJS(number):
     jso = Javascript("incrementNumber('%d')" % number)
     display_javascript(jso)

i = 0
while True:
     callJS(i)
     i += 1
     sleep(1.0/60.0)

It started at 221 MB on Firefox 45. Upto 270 MB there were small ups and downs. Afterwards it went all up. I left following at 560 MB.

**Comment by khbilen** [comment]
This notebook cell executed theHTML code I had embedded. I will try putting into quotes, otherwise attach as a file.

"""<html>
<head>
<meta charset="utf-8">
<title>Test</title>

<script type="text/javascript">

function incrementNumber(number) {
     number += 1;
     document.getElementsByClassName("pagetitle")[0].innerHTML = "Goodbye " + number;
     }

</script>
</head>

<body >
<h4 class="titlearea win-type-ellipsis" id="title">
     <span class="pagetitle" >
            Hello
     </span>
</h4>                                     
    <br/></body>
</html>"""

**Comment by minrk** [comment]
Can you tell what process is increasing in memory? Each display of Javascript does add elements to the page, so it should increase the memory usage a little bit, at least until output is cleared.

**Comment by khbilen** [comment]
You can test the simple example I posted above your comment. It is a small HTML doc with a simple function in it, which inrements a number. I call this function from python via the Javascript command, in a loop. You can see memory is increasing, after a little while , where at the beginning it goes up and down and up and down, but finally up and only up...

**Comment by bollwyvl** [comment]
@khbilen Indeed it does add a new `<script>` tag every time. It was pretty common with Bokeh before it started using comms to hand stuff around for things to get very unresponsive when updated by, say, a widget that a user could activate many times a second.

Widgets are probably your best bet for doing reasonably high-performance updates of the screen:
https://nbviewer.jupyter.org/gist/bollwyvl/8c484445cbc149325bdc27cfa2482a7f

I let that run for a pretty long time (in safari, as I don't use much): it started at 72mb, and after 20 minutes got up to 106mb. Not sure why it even went up that much, but pretty sure it's not entirely my doing: another 20 minutes with just the sleep loop and no JS update went from 85mb to 116mb.

You could eke out some more perfomance with custom comms, like bokeh has done, but the above code isn't too awful, i'd say.  Good luck!

**Comment by khbilen** [comment]
Thanks bollwyvl.  That was kind of what I had expected. I knew going through the comms path wpuld b more performant, but if this was a real problem that (if9 can be solved, then, as you said, it may be a good deal for a simple "comms" to get a reasonable performance.

Are you running on Notebook 5.0 or something? I am using 4.1.0 on Python 3.5. It did not give anty error for importing ipywidgets, but then when I execute the updater, I got the following message:

Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"

When I executed teh above command from the command shell, it id not like neither the --py falg nor the --sys. I thought you might be running at a different level?

**Comment by khbilen** [comment]
OK, I upgraded both Notebook and ipywidgets and now everything works fine. It is really quite stable. Memeory fluctuates between 380 and 400. I left monitoring at counter 31000. Now I have to check my actual applications and see how it performs with this new structure. I believe it will be fine. Thanks, All.
