### ISSUE TITLE
Jupyter not rendering/displaying in Chrome/Internet Explorer/Edge browser in Windows 10.

### ISSUE THREAD

**Issue by saumickm** [jupyter/help#546]
I'm trying to open Jupyter but its not displaying in any of the browsers, when I open console it states "blocked due to mime type mismatch". Here's how the errors in the console looks like.
![Errors](https://user-images.githubusercontent.com/48572206/54397167-6cca6200-46ad-11e9-9841-5395c6212b53.png)

**Comment by EloyRD** [comment]
I had the same problem #545.

This issue is related to [https://github.com/jupyter/notebook/issues/4469](url). 
The PR on [https://github.com/jupyter/notebook/pull/4468](url) solves the issue.
You look for the file `notebookapp.py` and add the new line.

**Comment by saumickm** [comment]
Here's what I did, following the instructions here: https://github.com/jupyter/notebook/pull/4468/files to fix the issue:
Go to file explorer and search for the file "notebookapp.py". This particular file was here:  [C:\Users\<username>\Miniconda3\pkgs\notebook-5.7.6-py36_0\Lib\site-packages\"notebook"]  in my case, but this file is always inside the "notebook" directory. There's another file with the same name in the tensorflow directory you don't need to change anything in that. Then open the python file in an Editor 

Press Ctrl+F to find the line "def init_mime_overrides(self):" 
Then delete these two lines :
  # Tornado uses this when serving .css files, causing browsers to reject the stylesheet.
  # We know the mimetype always needs to be text/css for css

and add,

        # Tornado uses this when serving .css and .js files, causing browsers to
        # reject these files. We know the mimetype always needs to be text/css for css
        # and application/javascript for JS, so we override it here.
        mimetypes.add_type('text/css', '.css')
        mimetypes.add_type('application/javascript', '.js')

make sure the indentation is correct for your editor I recommend typing it for that reason instead of copying it.

Thanks to @EloyRD @ciaranlangton
