### ISSUE TITLE
[Noobie] Kernel : "None not found"

### ISSUE THREAD

**Issue by hassanshaikley** [jupyter/help#57]
How come it says  "None not found" for Kernels after I restart the Kernel that created the file. How can I fix this?

**Comment by hassanshaikley** [comment]
Never mind. I see. New has to be clicked on by the top right menu!

**Comment by hassanshaikley** [comment]
How come it says  "None not found" for Kernels after I restart the Kernel that created the file. How can I fix this?

**Comment by hassanshaikley** [comment]
Ok the bug decided to disappear.

**Comment by Carreau** [comment]
Happy it works. Not sure how that can happen.
