### ISSUE TITLE
Python 2, Python 3 Notebook: import sympy

### ISSUE THREAD

**Issue by fiziko** [jupyter/help#60]
----> 1 import sympy

ImportError: No module named sympy

Is this as it should be?

**Comment by takluyver** [comment]
If sympy is not installed in the Python environment where that kernel is running, then yes, that's as it should be. Whether sympy should be installed depends on how you set that environment up.

**Comment by fiziko** [comment]
sure, but visiting https://jupyter.org/, and clicking on "Try it on your browser" https://try.jupyter.org/ I expected to find a Python environment where SymPy is avaiable for import.

**Comment by takluyver** [comment]
OK. As you found, it isn't, but it's a reasonable request. Pinging @rgbkrk @minrk .

**Comment by fperez** [comment]
As this is really a feature request for try.jupyter, I opened it there where we can continue the discussion. Closing this question.
