### ISSUE TITLE
Unable to make jupyter notebook run.

### ISSUE THREAD

**Issue by zachsj** [jupyter/help#62]
This is my first time posting and I'm new to Python, I'm not sure how to format this question.  I apologize if this is not enough info below or incorrect format.  I'm running on Windows 10.  I'm unable to open a notebook, something is wrong with my path I believe.  Here is what I receive when typing in jupyter notebook...

C:\Users\zj\AppData\Local\Programs\Python\Python35-32>jupyter notebook 
Traceback (most recent call last): File "c:\users\zj\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in run_module_as_main "main", mod_spec) File "c:\users\zj\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\zj\AppData\Local\Programs\Python\Python35-32\Scripts\jupyter-notebook.‌​exe__main_.py", line 5, in <module>

Much more of the above and then this error below...

OSError: [WinError 126] The specified module could not be found

**Comment by takluyver** [comment]
Can you copy the last few lines of the traceback?

**Comment by zachsj** [comment]
As in this below?
File "c:\users\zj\appdata\local\programs\python\python35-32\lib\site-packages\zmq_in‌​it_.py", line 37, in <module> libzmq = ctypes.cdll.LoadLibrary(bundled[0]) File "c:\users\zj\appdata\local\programs\python\python35-32\lib\ctypes__init_.py", line 425, in LoadLibrary return self._dlltype(name) File "c:\users\zj\appdata\local\programs\python\python35-32\lib\ctypes_init_.py", line 347, in init self._handle = _dlopen(self._name, mode) 

Then the OSError from above is at the end. 

Thank you

**Comment by takluyver** [comment]
Thanks. How did you install Jupyter?

@minrk, this looks like it's failing to load zmq. Any ideas?

**Comment by zachsj** [comment]
I believe that I just installed via pip.  I'm not sure what zmq is.  Can I somehow install it?

**Comment by takluyver** [comment]
zmq is a library Jupyter uses to communicate with kernels, via its Python bindings pyzmq. It should have been automatically installed if you used pip, but maybe it's worth trying to uninstall and reinstall it:

```
pip uninstall pyzmq
pip install pyzmq
```

**Comment by zachsj** [comment]
Just tried and no luck.  Also tried to uninstall and install jupyter,  
I  believe I was supposed to originally  append to the existing path in the environment variables screen but I had wiped out the existing path and have no idea what it originally was.  Not sure if that may be the issue.

**Comment by minrk** [comment]
It sure is a pyzmq issue. I just made the first release of pyzmq using a new build system, and the Windows wheels [now require VC 2015 redist](https://github.com/zeromq/pyzmq/issues/858#issuecomment-232163119), which they probably shouldn't.

You should be able to work around it for now with:

    pip install "pyzmq<15.3"

**Comment by zachsj** [comment]
I'm getting a bunch of items such as.... failed building wheel and failed cleaning build dir for pyzmq 
error microsoft visual c++ 14.0 required
and then rolling back uninstall of pyzmq

**Comment by minrk** [comment]
That's very strange. What version of Python and pip?

**Comment by zachsj** [comment]
python 3.5.2  pip 8.1.2

**Comment by minrk** [comment]
It shouldn't be trying to compile because there is a wheel. What about

    pip install pyzmq==15.2

?

**Comment by takluyver** [comment]
Closing as this should now be fixed.
