### ISSUE TITLE
Searching feature for notebooks in Jupyter hub

### ISSUE THREAD

**Issue by dvigneshwer** [jupyter/help#63]
Is it possible to search for notebooks in Jupyter hub.

I know its is not there by default has any one tried to implement it? 

Here is a piece of python code which I used to search by generating a json of ipynb notebook in the file system and later attacched it to my proxy link,

```
'''
Task : To search for a particular notebook link in jupyter notebook

Author : Vigneshwer

Date : 14th July 2016

Version : 1.0

'''

#loading modules 
import os 
import fnmatch
import json

#search location and extension
dir_location = "./"
search_ext = "ipynb"

#proxy link
proxy_link = "http://example.com/hub/"

#list of ipython note book names
list_ipynb_name = {}

#searching for all files named .ipynb and saving in a json format
for root, dirs, files in os.walk(dir_location):
	for file_name in files:
		if fnmatch.fnmatch(file_name,"*."+search_ext):
			list_ipynb_name[file_name.split(".")[0]] = proxy_link + str(root[len(dir_location):]) + "/" + str(file_name)

#saving to a json file
with open("ipynb_list.json", "w") as file_object:
	file_object.write(json.dumps(list_ipynb_name,file_object,indent=4))

#loading from the json file
with open('ipynb_list.json') as data_file:    
    data = json.load(data_file)

#searching for a key in json file
search_query = raw_input("Enter the key to search for :-")
flag=False

for key in data.keys():
	if search_query == key:
		print "Ipython notebook link :- " + data[key]
		flag=True
		break

if not flag: 
	print "Ipython Notebook not found"
```

Other ideas would be appreciated, would like to also integrate the logic to jupyter hub with a UI for people to use, perhaps using elasticsearch or solr.

**Comment by parente** [comment]
@dvigneshwer The https://github.com/jupyter-incubator/contentmanagement extension for jupyter notebook has a search UI for files on the local hard drive. It relies on Whoosh for indexing. It could be installed in all notebook servers running in a Jupyter Hub deployment. But it has no specific support for collaborative sharing of files across notebook instances in Hub.

**Comment by dvigneshwer** [comment]
@parente thanks this looks really promising.

But I am facing few problems, search extension poped up in the hub, but unfortunately it was not able to deliver any search results !! 

The above occured with the commands below

```
pip install jupyter_cms
jupyter cms quick-setup --sys-prefix

```
But I was using jupyter notebook 4.1, so I uninstalled above implementation and followed instruction for 4.1 installation 

pip install jupyter_cms  #worked without any error.
```
# See jupyter cms install --help for other options (e.g., --sys-prefix)
jupyter cms install --user --symlink --overwrite
```
Error:
```
[ExtensionApp] CRITICAL | Bad config encountered during initialization:
[ExtensionApp] CRITICAL | Unrecognized flag: '--symlink'

```
I got the simillar error for --user where I replace it with my uname.

How do I fix this ?

Thanks

**Comment by parente** [comment]
Try this as written:

`jupyter cms install --user --overwrite`

You're probably on an OS that doesn't support symlinks. And you don't have to provide a username. The `--user` activates the extension in the current user profile.

**Comment by dvigneshwer** [comment]
I am using ubuntu 14.04 LTS.

Now erros out to display --user is Unrecognized and when I changed it to my username, it says --overwrite is Unrecognized.

I just tried jupyter cms install ( it error out for options to use --help all)

**Comment by parente** [comment]
Are you automating the install in Jupyter Hub somehow or trying it with a single notebook server? I just tried in a fresh notebook 4.1 environment without issue.

[![asciicast](https://asciinema.org/a/a3qiuq210awvc0j6yds2i2u6d.png)](https://asciinema.org/a/a3qiuq210awvc0j6yds2i2u6d)

**Comment by shubhjain26** [comment]
![jupytererror](https://cloud.githubusercontent.com/assets/20471277/16865473/a5d7d782-4a82-11e6-9bc1-c4bbb01b2ce1.png)

I am getting the above error. However "jupyter cms quick-setup --sys-prefix" works in 4.1 and it shows the search button as well but it always says "error fetching result". After that I used "jupyter cms quick-remove --sys-prefix" and tried the mentioned command as shown in screenshot. Any suggestion ?

**Comment by dvigneshwer** [comment]
@parente I am facing the same issue as @shubhjain26 same error

installed jupyter hub using pip install jupyter and also I am not using a mac book.

**Comment by parente** [comment]
Something is wrong if you see the quick setup opinion in 4.1. It's only intended to appear and work in 4.2. Can you post the output of pip freeze for me?

**Comment by shubhjain26** [comment]
![jupyter_freeze](https://cloud.githubusercontent.com/assets/20471277/16871811/a7cd4472-4aa6-11e6-9300-565240b16bc2.png)

@parente : Thanks for your quick response. Here's the output of freeze.

**Comment by parente** [comment]
Can you include notebook in the list?

**Comment by dvigneshwer** [comment]
![screenshot from 2016-07-15 16 37 32](https://cloud.githubusercontent.com/assets/5075497/16872450/8410cf5a-4aaa-11e6-8673-5a2f323b45da.png)

**Comment by parente** [comment]
@dvigneshwer you're on 4.2.1, not 4.1 as stated a few comments up, so the quick-setup option is the correct command. So I don't think install is the problem.

How are you launching the notebook or Jupyter hub? I don't see JHub in the pip output. Are you testing against a single notebook server to start without Jupyter hub?

**Comment by dvigneshwer** [comment]
@parente sorry about the notebook version, got perplexed with the output I got from `jupyter --version` command.

`jupyterhub --version` is **0.6.1**, this output is not there in `pip freeze`

We are launching jupyterhub which spwans multiple single user notebooks.

**Comment by parente** [comment]
OK. Can you paste the URL of one of the notebook instances when you spawn it? I'm thinking there might be a bug in how the CMS extension is looking for its backend API endpoint. You end up seeing the UI, but the search function implemented notebook side is not found when the UI tries to invoke the search API.

**Comment by dvigneshwer** [comment]
I am behind a coprate firewall, will not be able to share an notebook instance.

Can you please tell me the tests that could be helpfull in solving the problem.

**Comment by parente** [comment]
Oh I don't need access to the notebook instance. I just need to see the path part of the URL.

**Comment by dvigneshwer** [comment]
**URL sample:**

Before login,
`https://example.com/hub/login`
After login,
`https://example.com/user/root/tree`

**Comment by parente** [comment]
OK. After login, try putting replacing the value in the URL bar with `https://example.com/user/root/search?qs=ipynb`. Does it return a 404 page? A 500 error page? Nothing at all?

**Comment by dvigneshwer** [comment]
I am getting a 404 page

**Comment by parente** [comment]
What does `jupyter serverextensions list`output for that notebook? Either the server-side search code is not activated properly by the quick-setup (would be surprising: you'd get an error on install) or it's not located under the correct base URL.

**Comment by jtyberg** [comment]
Just as another data point, I was able to use the cms extension on my JupyterHub installation.

Basically, this setup https://github.com/jupyterhub/jupyterhub-deploy-docker

and running a notebook image built using

```
# Pin to a known release for sanity
FROM jupyter/pyspark-notebook:8015c88c4b11

# Do the pip installs as the unprivileged notebook user
USER jovyan

# Install content management 
RUN pip install "jupyter_cms==0.5.*" && \
	jupyter cms quick-setup --sys-prefix
```

Then, 

```
https://myhost.mydomain/user/jtyberg/search?qs=ipynb

{
total: 0,
results: [ ]
}
```

**Comment by shubhjain26** [comment]
![jupyterserver](https://cloud.githubusercontent.com/assets/20471277/16902174/84310fec-4c74-11e6-8f19-8fab991799dd.png)

@parente : That's the output of "jupyter serverextension list" command.

**Comment by parente** [comment]
Everything is installed properly. The URL path seems wrong in your case vs in @jtyberg's setup.

**Comment by dvigneshwer** [comment]
@parente url which @jtyberg is using is same as the one we are using there is no difference.

I tried,
dev.notebook.example.com/user/viki/tree/search?qs=ipynb
dev.notebook.example.com/user/viki/search?qs=ipynb

Both of them give a 404 page only.

**Comment by shubhjain26** [comment]
@parente : It works well with the single user notebook, but it causes problem with the hub.
With the following URL for single standalone notebook, it was working fine:
"localhost:8000/search?qs=*.ipynb"

Also I have a proxy set up for my jupyterhub, could that be causing any problem ? Although to try it out, I have tried running the query over IP as well but no luck.

**Comment by dvigneshwer** [comment]
The jupyter cms is not working in Jupyter hub setup !!

**Comment by parente** [comment]
@dvigneshwer @shubhjain26 When your notebook server starts under jupyter hub, do you see a message `Loaded jupyter_cms` in the log output of the notebook server?

**Comment by dvigneshwer** [comment]
@parente It is working, we reinstalled the plugin with pip3 !! @shubhjain26 will share more detials.
It is able to search through the notebook contents also.

Thanks @parente for the all the help, really appreciate it, have you thought about adding tags to notebooks for enhancing the search capability and usability?

**Comment by shubhjain26** [comment]
@parente : Hi, after making some tweaks and installing the plugin with pip3, the plugin is working fine :). 
Thank you so much for you kind support and patience.

**Comment by parente** [comment]
Great! I'm glad it was a simple install / config problem in the end.

@dvigneshwer There's been discussion of supporting cell tagging in the notebook for a while but no official implementation yet. It's something that should be doable as a cell toolbar extension to either the existing notebook or Jupyter Lab.
