### ISSUE TITLE
Prevent Jupyter from using pyzmq==15.3.0 (Broken on windows)

### ISSUE THREAD

**Issue by nonZero** [jupyter/help#66]
When using pip to install jupyter on windows, pyzmq==15.3.0 currently fails without a decent warning if MSVC++ redistributable are not installed.

This highly affects novice/new developers trying to get into python, installing jupyter on their windows machines, and immediately hitting a dead end, with a cryptic error message, see for example: https://github.com/jupyter/help/issues/62

A small workaround until this is fixed would be limiting jupyter to use pyzmq<15.3.0.

**Comment by minrk** [comment]
pyzmq 15.3 wheels on Windows should be fixed now.

**Comment by takluyver** [comment]
Closing as this should be fixed, and I expect we'd have more people telling us if it wasn't.

**Comment by minrk** [comment]
Indeed, pyzmq 15.3 is fixed, and 15.4 has a new release that should also work.
