### ISSUE TITLE
Notebook does not appear to be json

### ISSUE THREAD

**Issue by palani2002** [jupyter/help#67]
Dear All,

I have the following error when opening the ipynb file.
Error is:
Unable to read notebook ....ipynb notJSONERROR (notebook does not appear to be json) in Ubuntu.

(The error was: SyntaxError: Unexpected token < in JSON at position  :in windows)

Could someone help to solve my JSON error as mentioned ? I  did a lot  of python coding in it.This notebook was opened using chrome browser.

Thanks in advance.

Palani

**Comment by jasongrout** [comment]
Can you post the first part of the file here?

**Comment by palani2002** [comment]
Hello Mr.Jasongrout,

Thanking you for the first-aid service.

Herewith pasted first few lines of html code, also attached screenshot contains error message.
<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">

    <title>IPython Notebook</title>
    <link rel="shortcut icon" type="image/x-icon" href="/static/base/images/favicon.ico?v=30780f272ab4aac64aa073a841546240">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c" type="text/css" />
    <link rel="stylesheet" href="/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

![screenshot from 2016-07-22 10-14-45](https://cloud.githubusercontent.com/assets/10462857/17046832/57bdf1da-4ff5-11e6-998a-86d542274b23.png)


Thanking you Once again.

**Comment by jasongrout** [comment]
It looks to me like that is an html page, not a notebook. How did you save it? Did you use the browser to save the webpage showing the notebook, or did you use the notebook's File > Download As menu?

**Comment by jasongrout** [comment]
But there still may be hope. Where did you get the notebook?

**Comment by palani2002** [comment]
Hello Mr.Jason Grout,

I saved in the notebook . Now unable to view the edited code.

I working in this address ,http://localhost:8888/notebooks.

Thanks.

Regards,
Palani

Warm Regards,
Palani.S

**Comment by jasongrout** [comment]
What you pasted was an html file that looks like it was saved from your browser, not a notebook saved using the File > Download As menu in the notebook. There is a difference between the html file your browser is displaying for you to interact with, and the actual underlying notebook.

The good news is that likely the notebook is somewhere on your computer, if you saved it *from* the localhost address. Do you know what directory the notebook server was launched from? If so, then go to that directory and your .ipynb file should hopefully be there.

**Comment by palani2002** [comment]
Hello Mr.Jason Grout,

Yes . exactly you are right.
File is there in my directory , but when launching i got the error(which
attached as screenshot in earlier mail)

Thanks.

Regards,
Pallani.

Warm Regards,
Palani.S

**Comment by jasongrout** [comment]
That file is corrupted and not a notebook any more. You'll need to get the notebook again from where you originally got it from. Can you do that?

**Comment by takluyver** [comment]
If you rename the file to have a `.html` extension, you might be able to open it in your browser and copy out bits of code.

**Comment by Carreau** [comment]
This has been inactive for 2 month, I'm going to close assuming it has been fixed. Feel free to reopen if needed. Thanks !

**Comment by Saisuchith** [comment]
I have got the error :   
 NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)


and in ipynb file as some red marks when i opened it in atom. I am posting that part:

<<<<<< HEAD
   "execution_count": 22,
=======
   "execution_count": 21,
>>>>>>> a1f5acbaa00bc1b1e5fc3532ba19a013a271542c
   "metadata": {},
   "outputs": [],
   "source": [
    "epoch=2\n",
    "batch=100\n",
    "sp_epoch=X_train.shape[0]"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": 23,
=======
   "execution_count": 22,
>>>>>>> a1f5acbaa00bc1b1e5fc3532ba19a013a271542c
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/2\n",
<<<<<<< HEAD

**Comment by takluyver** [comment]
Somebody has got merge conflicts in the file - those `<<<` and `===` and `>>>` lines are how git shows its merge conflicts. To make it valid, you need to get clean up those, and in each chunk, pick one of the bits inbetween them:

```
<<<<<< HEAD
   Either keep this line...
=======
   ... or this one. But not both!
>>>>>>> a1f5acbaa00bc1b1e5fc3532ba19a013a271542c

**Comment by takluyver** [comment]
And then use [nbdime](http://nbdime.readthedocs.io/en/stable/) to avoid git doing that again.

**Comment by nvinayvarma189** [comment]
hey @takluyver I got the same error here as @Saisuchith 
NotJSONError('Notebook does not appear to be JSON: '{\n "cells": [\n {\n "cell_type": "m...',)

![screenshot from 2018-01-16 19-33-20](https://user-images.githubusercontent.com/30727381/34993175-8f9d7600-faf5-11e7-84e2-08a9b836693f.png)

These are those two lines...
`"{'Rimnicu': (233, 410), 'Timisoara': (94, 410), 'Iasi': (473, 506), 'Neamt': (406, 537), 'Fagaras': (305, 449), 'Giurgiu': (375, 270), 'Urziceni': (456, 350), 'Mehadia': (168, 339), 'Lugoj': (165, 379), 'Sibiu': (207, 457), 'Oradea': (131, 571), 'Zerind': (108, 531), 'Craiova': (253, 288), 'Hirsova': (534, 350), 'Arad': (91, 492), 'Vaslui': (509, 444), 'Drobeta': (165, 299), 'Bucharest': (400, 327), 'Eforie': (562, 293), 'Pitesti': (320, 368)}\n"
`

`"{'Oradea': (131, 571), 'Eforie': (562, 293), 'Timisoara': (94, 410), 'Hirsova': (534, 350), 'Bucharest': (400, 327), 'Rimnicu': (233, 410), 'Fagaras': (305, 449), 'Lugoj': (165, 379), 'Giurgiu': (375, 270), 'Mehadia': (168, 339), 'Pitesti': (320, 368), 'Drobeta': (165, 299), 'Craiova': (253, 288), 'Sibiu': (207, 457), 'Iasi': (473, 506), 'Urziceni': (456, 350), 'Vaslui': (509, 444), 'Neamt': (406, 537), 'Zerind': (108, 531), 'Arad': (91, 492)}\n"
`


Removing one of them did not work for me . Can you please help me with this

**Comment by takluyver** [comment]
You need to remove one of them and also remove those lines highlighted in red - those are the git conflict markers.

**Comment by takluyver** [comment]
The two small red lines on the left are something your editor shows to highlight that something has changed relative to git.

What you've got looks right to me. Check that there isn't a comma at the end of that long line. If it doesn't work, try parsing the file as json and see what the error is.

**Comment by Saisuchith** [comment]
Thank you @takluyver . That notebook was important for me and your method helped me. Thanks again :):)

**Comment by dongjunchuan** [comment]
Today I got the same error as @Saisuchith ,Finally I downloaded the raw file from github，in this way , I got the right ipynb file.

**Comment by Graveflli** [comment]
I changed the suffix with Notepad to cause this same problem.
But I will be fine by creating a new file via the new button in the top right corner of the page.

**Comment by Kidusyohanes** [comment]
One other solution is to delete the current .ipnyb file and running 'jupyter notebook' and navigate to the directory of your project and Click 'New' dropdown to create a new jupyter notebook.
