### ISSUE TITLE
Grab Multiple Cells in Jupyter Notebook

### ISSUE THREAD

**Issue by gaomrx** [jupyter/help#68]
Much desired ability to be able to grab multiple cells at once (like ctrl + click cells) and move them around together. No more splitting and unsplitting cells please.

**Comment by takluyver** [comment]
As you may have discovered, you can select multiple cells using the keyboard (I don't think we've exposed a way to do it with the mouse yet). Hold down shift while pressing up/down. You can cut/paste/delete/execute/etc. the selected range.

If moving around cells with the mouse appeals, have a look at [nteract](https://github.com/nteract/nteract). I'm not sure if it has multiple cells selections too.

**Comment by dan3dewey** [comment]
The shift + click WILL add cells to a multiple selection, BUT you have to click in the blank area to the left of the cell content (column where the, e.g.,  "In [37]:" is.)
