### ISSUE TITLE
Keyboard short-cut "ctrl-shift-p" is used by Firefox already

### ISSUE THREAD

**Issue by SergiyKolesnikov** [jupyter/help#72]
The keyboard short-cut for opening the command palette ("ctrl-shift-p") is used by Firefox and does not function as intended by the jupyter-notebook. Even if the short-cut is disabled or reassigned for Firefox using [an extension](https://github.com/Lord-Kamina/keybinder) it still does not work in the notebook.

I would suggest changing the default short-cut to a semicolon ";", because it is free and very fast to access (which is important for such a useful command).

**Comment by cipri-tom** [comment]
Or better still, make it customisable. I think this is [foreseen in the master branch](https://github.com/jupyter/notebook/issues/1611#issuecomment-234117012).

**Comment by SergiyKolesnikov** [comment]
@cipri-tom I customized the short-cut. I created a `custom.js` file (for my standard Anaconda installation on GNU/Linux it is `~/.jupyter/custom/custom.js`) and added the following code:
`IPython.keyboard_manager.command_shortcuts.add_shortcut(';', 'jupyter-notebook:show-command-palette')`
It makes ";" open the command palette in the command mode.

I use jupyter-core 4.1.1 and notebook 4.2.2 from Anaconda.

I believe, for the latest jupyter notebook the code should be the following:
`Jupyter.keyboard_manager.command_shortcuts.add_shortcut(';', 'jupyter-notebook:show-command-palette')`
I did not test it.

**Comment by cipri-tom** [comment]
@SergiyKolesnikov Thank you! I was going to do it over the weekend. So far, I managed to load the sublime keymap via the `custom.js` and set some emacs preferences which were vital for editing.
Great job!

**Comment by SergiyKolesnikov** [comment]
@cipri-tom I am interested in those emacs short-cuts. Could you share them somewhere?

**Comment by cipri-tom** [comment]
@SergiyKolesnikov ok, my only reminiscence from emacs is `ctrl+a` and `ctrl+e` :laughing: 
But you can load the whole [emacs scheme **approximation**](https://codemirror.net/demo/emacs.html) and edit it by following [these settings](https://codemirror.net/doc/manual.html#keymaps).

Here's what I have:

    require(["codemirror/lib/codemirror", "codemirror/keymap/sublime", "notebook/js/cell"],
    function(cm, sublime_keymap, cell) {
        console.log("loading custom sublime extension");
        let subl = cm.keyMap.sublime;
        // disable ctrl-enter
        delete subl["Ctrl-Enter"];
        delete subl["Shift-Ctrl-Enter"];

        cell.Cell.options_default.cm_config.keyMap = 'sublime';

        var extraKeys = { "Ctrl-A": "goLineStartSmart", "Ctrl-E": "goLineEnd" };
        cell.Cell.options_default.cm_config.extraKeys = extraKeys;
        console.log("DONE: loading custom sublime extension");
    });


Mine sometimes isn't working (although the `console.log` says it's loaded). I just kill and restart the notebook server. Painful, but I'm desperate without it.

**Comment by mdcramer** [comment]
I plugged `IPython.keyboard_manager.command_shortcuts.add_shortcut(';', 'jupyter-notebook:show-command-palette')` and `IPython.keyboard_manager.command_shortcuts.add_shortcut(';', 'jupyter-notebook:show-command-palette')` into the `custom.js` and nothing happens when I type Ctrl and ";".

I'm using jupyter-core 4.2.1 and notebook 4.3.1 from Anaconda. My `custom.js` is located at `~\Anaconda3\Lib\site-packages\notebook\static\custom\custom.js` and I've confirmed that it's getting execute by using a `alert("this is from the custom.js")` that pops up whenever I open a new notebook. Any suggestions?

**Comment by SergiyKolesnikov** [comment]
@mdcramer It stopped working for me too (Anaconda 4.3.0). My workaround for now is to have the following code in the first cell of every notebook:
```
%%javascript
Jupyter.keyboard_manager.command_shortcuts.add_shortcut(';', 'jupyter-notebook:show-command-palette');
```

BTW, the shortcut is just ";" (in the command mode), not "Ctrl+;".

I have tried adding [the examples form the notebook documentation](https://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Custom%20Keyboard%20Shortcuts.html) to `custom.js`, but they do not work either. Interestingly, if you add the `alert()` call after the shortcut code the alert does not appear. This could mean that the shortcut code exits because of some error. I have not found a way to debug `custom.js` to check that yet.

**Comment by SergiyKolesnikov** [comment]
@mdcramer @cipri-tom It finally worked.

The following code in `custom.js` will do the trick:

```
define(['base/js/namespace', 'base/js/events'],
       function(Jupyter, events) {
	   events.on("app_initialized.NotebookApp", function () {
               Jupyter.keyboard_manager.command_shortcuts.add_shortcut(';', 'jupyter-notebook:show-command-palette');
	   });
       });
```

The code is based on [the examples in the default `custom.js`.](https://github.com/jupyter/notebook/blob/master/notebook/static/custom/custom.js)

*Explanation*

I placed the `Jupyter.keyboard_manager ...` line on its own into `custom.js` and ran a JavaScript debugger during a notebook reload. It showed that `Jupyter.keyboard_manager` (and `IPython.keyboard_manager`) is not defined at the time-point `custom.js` is evaluated. Therefore, the call must be postponed until the notebook is initialized, which is done by the above snippet.

**Comment by SergiyKolesnikov** [comment]
Since notebook server v 5.0.0 (Anaconda 4.4.0) there is an "official" alternative key binding for the command palette: `Ctrl-Shift-F`
