### ISSUE TITLE
Installation of Jupyter on Fedora 24

### ISSUE THREAD

**Issue by gbraad** [jupyter/help#74]
Install instructions for Fedora 24 should refer to needing:

```
$ dnf install -y python3-devel redhat-rpm-config gcc-c++ @'Development Tools'; 
```

`redhat-rpm-config` is needed, else `pyzmq` fails with:

    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory

`gcc-c++` is needed else `pyzmq` fails with:

     gcc: error trying to exec 'cc1plus': execvp: No such file or directory

Example of a successful installation can be found [here](https://github.com/gbraad/docker-jupyter/blob/master/fedora/Dockerfile) as a Docker container.

**Comment by takluyver** [comment]
Pyzmq has Linux wheels up on PyPI, so with an up to date version of pip, it should install without needing a compiler. Make sure you have the latest pip and setuptools before installing:

```
pip install --upgrade setuptools pip
```

**Comment by gbraad** [comment]
Running...
```
pip3 install --upgrade setuptools pip
```

... does not seem to update correctly...
```
[root@c3810bae0038 /]# pip3 install --upgrade setuptools pip
Collecting setuptools
  Downloading setuptools-25.2.0-py2.py3-none-any.whl (442kB)
    100% |################################| 446kB 827kB/s 
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 315kB/s 
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 20.1.1
    Uninstalling setuptools-20.1.1:
      Successfully uninstalled setuptools-20.1.1
  Found existing installation: pip 8.0.2
    Uninstalling pip-8.0.2:
      Successfully uninstalled pip-8.0.2
Successfully installed pip-8.0.2 setuptools-20.1.1
You are using pip version 8.0.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I'll investigate more later...

**Comment by gbraad** [comment]
running just

```
$ pip3 install --upgrade pip
```

allows to install

```
$ pip3 install pyzmq
$ pip3 install tornado
$ pip3 install jupyter
```

without any compilation... So something is wrong with Tornado and the latest setuptools.

Might be an idea to include the `pip3 install -U/--upgrade pip` instruction on the installation page of Jupyter.

**Comment by gbraad** [comment]
https://github.com/tornadoweb/tornado/issues/1804

**Comment by gbraad** [comment]
Failing installation is unrelated to Jupyter (closing).

**Comment by avibrazil** [comment]
https://avi.alkalay.net/2018/07/fedora-jupyter-notebook.html
