### ISSUE TITLE
jupyter and julia

### ISSUE THREAD

**Issue by isaco** [jupyter/help#76]
Hi,

jupyter don't show new version of julia even it is on PC in folder .julia/v0.4 , but **old version**.
I use Canopy 64 and w8. How to connect with Julia v0.4 or what to do to work jupyter properly.
Python work well as Julia but alone.

Thank you for instructiona in advance,
Isaco

**Comment by jasongrout** [comment]
Jupyter only shows the kernels that have been installed. You can see these at the command line by doing `jupyter kernelspec list`. My guess is that you'll need to either install the julia kernel for the new julia version (see https://github.com/JuliaLang/IJulia.jl), or if Canopy is automatically supposed to find the julia kernels, you would need to talk with them.

**Comment by Carreau** [comment]
I'm going to guess Jason answer fixed your issue, and I am going to close. Feel free to reopen if needed. Thanks!
