### ISSUE TITLE
Installed Rodeo and it installed  package Jupyter/Ipython.... in /usr/local/lib/python2.7/site-packages... but now 

### ISSUE THREAD

**Issue by raghavkgarg** [jupyter/help#77]
Installed Rodeo and it installed Jupyter/Ipython.... in /usr/local/lib/python2.7/site-packages 
- But now if i go in terminal type "jupyter notebook"
i get
   -bash: jupyter: command not found

**Comment by takluyver** [comment]
Is there a `jupyter` file in `/usr/local/bin`?

**Comment by raghavkgarg** [comment]
No, but i tried reinstalling jupyter . Should i move manually file ?

**Comment by takluyver** [comment]
What does `echo $PATH` show?

**Comment by raghavkgarg** [comment]
Hi , Thanks i checked bin , and then i tried to run jupyter**-**notebook instead of jupiter notebook.
it worked , may be it was because of i had jupyter-console was also present.
Thanks ,
