### ISSUE TITLE
Auto close parentheses

### ISSUE THREAD

**Issue by NanoExplorer** [jupyter/help#78]
After upgrading from notebook 4.2.1 to 4.2.2, the settings file that disables automatically closing parentheses no longer has any effect. I don't know if this is related to https://github.com/jupyter/notebook/issues/1431, so I haven't posted there.

Downgrading to 4.2.1 fixes the problem.

The working behavior in 4.2.1 is to have a `.jupyter/custom/custom.js` file with the line `IPython.CodeCell.options_default.cm_config.autoCloseBrackets=false;`.

Having the automatically closing parentheses on is very annoying to me because if I try to type an end parenthesis before another already existing end parenthesis, it overwrites the already existing one instead of adding a new one (regardless of whether the overwritten parenthesis was added by the auto-close function or manually by me).

**Comment by minrk** [comment]
There was a change in 4.2.2 that changed when custom.js is loaded, which may affect the effect of this configuration. https://github.com/jupyter/notebook/pull/1732 should restore it to the 4.2.1 ordering, at least.

**Comment by gnestor** [comment]
4.2.3 was released last week, so upgrading to it should fix this problem. @NanoExplorer Please confirm that it does!

**Comment by NanoExplorer** [comment]
Yep! I upgraded to 4.2.3 and it works.
