### ISSUE TITLE
Jupyter Cell Error clears all my variables

### ISSUE THREAD

**Issue by yourinoelnelson** [jupyter/help#86]
I install JupyterHub and I am running the jupyter notebok through that. I have a folder which is a clone rep from bitbucket. All this is fine until I get to running my notebook.
If there is no error it runs just fine but if one of the cell errors out I then have to rerun the entire notebook because somehow all my variables have been clear from that one error.

![image](https://cloud.githubusercontent.com/assets/10758934/18992500/a3b1e5aa-86ec-11e6-88a5-ee451549d543.png)

And then when I try to rerun the cell that previously worked I get this:
![image](https://cloud.githubusercontent.com/assets/10758934/18992521/bae851f0-86ec-11e6-8831-f3f1f10667c8.png)

I then have to rerun every single cells in order for it to have the correct variable.
Has this ever happen to anyone, I am assuming this is not standard behavior...

PS: I know my syntax is wrong on that last cell ;)

**Comment by takluyver** [comment]
That doesn't look like all your variables have been cleared. It's just changed dfMAIN.

When you write:

```python
dfMAIN = dfMAIN.loc[dfMAIN.RelationshipCode == 1, 'AccountTypeDesc'] = 'DDA'
```

It is doing something like this:

```python
dfMAIN = 'DDA'
dfMAIN.loc[dfMAIN.RelationshipCode == 1, 'AccountTypeDesc'] = 'DDA'
```

The first bit runs OK, and sets `dfMAIN` to a string. Then the second bit fails. But `dfMAIN` has already been changed, so when you run your previous cell again, it doesn't work.

**Comment by yourinoelnelson** [comment]
That would make sense wouldn't it?? Did not even think about that! ahah 
Thanks for pointing that out!
