### ISSUE TITLE
https://try.jupyter.org/ gives 504 Gateway Time-out

### ISSUE THREAD

**Issue by jocraven** [jupyter/help#88]
was using https://try.jupyter.org/  a few weeks ago when I went back to it over the last few days all I get is

https://try.jupyter.org/ gives 504 Gateway Time-out

**Comment by rgbkrk** [comment]
Odd, tmpnb.org is giving me a valid tmpnb node. Checking it out now.

**Comment by rgbkrk** [comment]
Ah, try jupyter is hardcoded to an old node. I'll get this fixed up.

**Comment by rgbkrk** [comment]
Fixed in https://github.com/jupyter/try.jupyter.org/pull/18

**Comment by DeepakPattnaik** [comment]
Hi,

I just tried opening this today.. it again goes to 504 Gateway Timeout.
Need help !!
