### ISSUE TITLE
jupyter command not found on mac ox

### ISSUE THREAD

**Issue by steinorepearl** [jupyter/help#89]
I just installed jupyter on mac ox el capitan
but bash can't find the command 
$ jupyter notebook
-bash: jupyter: command not found

I did the upgrade 
     $ pip install -U jupyter --user

pip shows the package installed - see below -
so am in mystery as what to setup on my PATH or otherwise set a configuration.

thanks,

pip show jupyter
---
Metadata-Version: 2.0
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
Installer: pip
License: BSD
Location: /Users/<xxx>/Library/Python/2.7/lib/python/site-packages
Requires: nbconvert, notebook, ipykernel, jupyter-console, ipywidgets, qtconsole
Classifiers:
  Intended Audience :: Developers
  Intended Audience :: System Administrators
  Intended Audience :: Science/Research
  License :: OSI Approved :: BSD License
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4

**Comment by takluyver** [comment]
On Linux the directory you need to add to $PATH is `~/.local/bin`, but I don't think that works on OSX. Have a hunt around your home directory for a `bin` folder.

**Comment by minrk** [comment]
I've been meaning to send a patch to pip to show the user where it installed scripts, and warn if it put then not on PATH.

For a `--user` install like that, it would be `~/Library/Python/X.Y/bin`

**Comment by steinorepearl** [comment]
thanks, that was the path I needed.


David Steinore
Pearl Automation
davidsteinore@pearlauto.com
415-259-7079

**Comment by lemioneta** [comment]
I'm having the same issue but I don't understand this advice:
```

I've been meaning to send a patch to pip to show the user where it installed scripts, and warn if it put then not on PATH.

For a --user install like that, it would be ~/Library/Python/X.Y/bin
```

**Comment by takluyver** [comment]
There's an environment variable on your system called $PATH, which tells it where to look when you run a command like `jupyter` in a terminal. You can see this with `echo $PATH`. The place Jupyter can be installed is not normally on $PATH. On a Mac, it is a folder like `/Users/you/Library/Python/3.5/bin`.

You can modify PATH in a file like `~/.bash_profile`, like this:

```shell
PATH=$HOME/.local/bin:$PATH
export PATH
```

**Comment by jimmythongtran** [comment]
I need clarification for my configuration. I am using zsh.

My `pip show jupyter` is:
```
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /Users/Mac/Library/Python/2.7/lib/python/site-packages
Requires: ipywidgets, nbconvert, notebook, jupyter-console, qtconsole, ipykernel
```


My `echo $PATH`, is:
`/Users/Mac/.rvm/gems/ruby-2.0.0-p643/bin:/Users/Mac/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/Mac/.rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Mac/.rvm/bin`

How do I modify `~/.bash_profile`? Here is how it currently looks like:
```
if [ -f ~/.bashrc ]; then
	source ~./bashrc
fi

export PS1="Yes, Sir? "

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# added by Anaconda2 4.4.0 installer
export PATH="/Users/Mac/anaconda/bin:$PATH"

PATH=$HOME/.local/bin:$PATH
export PATH

export PATH=$PATH:./etc/jupyter
```

**Comment by jimmythongtran** [comment]
I resolved my own problem by [changing the shell for mac to bash](http://osxdaily.com/2012/03/21/change-shell-mac-os-x/).

**Comment by takluyver** [comment]
To clarify, `.bash_profile` only affects bash. I expect there's a similar file for zsh, but Anaconda probably only automatically modifies the bash file.

**Comment by mosesemm** [comment]
after install, it added the path to ~/.profile file...had to run
`source ~/.profile`
to make the command available

**Comment by gor181** [comment]
Just cat the bash profile such as:

```shell
cat ~/.bash_profile
```

which gets you:

```shell
# added by Anaconda3 5.0.1 installer
export PATH="/Users/goranudosic/anaconda3/bin:$PATH"
```

And then just copy `export PATH="/Users/goranudosic/anaconda3/bin:$PATH"` to your `~/.zshrc`

**Comment by luckyyang** [comment]
```bash
sudo rm -rf /Library/Frameworks/Python.framework
rm /usr/local/bin/python3*
brew uninstall python3
brew install python3
which python3
python3 -m pip install --upgrade pip
python3 -m pip install jupyter
which jupyter
jupyter notebook
```

Resolved my issue by installing python3 with brew instead of downloading python from pkg file.

**Comment by sercretalphabets** [comment]
sudo rm -rf /Library/Frameworks/Python.framework
rm /usr/local/bin/python3*
brew uninstall python3
brew install python3
which python3
sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install jupyter
which jupyter
jupyter notebook

Solved my problem. I could not install jupyther on my Mac with python 2.7

**Comment by KyleOh** [comment]
```python
sudo rm -rf /Library/Frameworks/Python.framework
rm /usr/local/bin/python3*
brew uninstall python3
brew install python3
which python3
sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install jupyter
which jupyter
jupyter notebook
```

Also helped me. Thanks to luckyyang!
mine was python3.6 and using sierra 10.12.6

**Comment by paulahsan** [comment]
> sudo rm -rf /Library/Frameworks/Python.framework
rm /usr/local/bin/python3*
brew uninstall python3
brew install python3
which python3
sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install jupyter
which jupyter
jupyter notebook

This helped me. Thanks a lot @luckyyang

**Comment by darrenlittlejohn** [comment]
gor181's suggestion solved it for me. Thanks!

**Comment by gajjarsaurabh** [comment]
I was also having the same issue while I was trying to install jupyter using pip command, it showed: 
~bash: jupyter: command not found 
on executing the command: pip install jupyter

so, I typed these two commands and it worked
python3 -m pip install --upgrade pip
python3 -m pip install jupyter

**Comment by eedollmeyer** [comment]
@gajjarsaurabh worked for me, thank you!

**Comment by lanhongvp** [comment]
```
sudo rm -rf /Library/Frameworks/Python.framework
rm /usr/local/bin/python3*
brew uninstall python3
brew install python3
which python3
sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install jupyter
which jupyter
jupyter notebook
```
@luckyyang 

This also helps me, thanks a lot.

**Comment by d-demirci** [comment]
for those of you (like me) who installed on Mac using installer with just clicking next next finish 
then
`export PATH=$PATH:/anaconda3/bin`
next type jupyter to see if it works.

to make this permanent
```
nano ~/.bashrc
export PATH=$PATH:/anaconda3/bin
ctl+x. then y.  (save the file and exit)
source ~/.bashrc
```

**Comment by AdrianMcNeese** [comment]
@luckyyang I already have it installed, but now my issue is re-opening it from the terminal. I tried user/newenv(envioronment name)/bin or user/newenv/bin/activate and trying 'jupyter notebook', but it says that jupyter isn't a command

**Comment by luckyyang** [comment]
@AdrianMcNeese Sorry I don't know why you got that error, seems your `jupyter` is not installed or linked successfully

**Comment by micromouseonline** [comment]
On the mac, at least, if you installed Python using the pkg files rather than home-brew, the installer will  update your PATH variable.

BUT . . . if you do not log in to a new terminal, the change to the PATH will not show up. All I had to do was close and re-open my terminal window and jupyter was able to be run from the command prompt with no trouble.

**Comment by sarthaksahni1989** [comment]
> ```shell
> sudo rm -rf /Library/Frameworks/Python.framework
> rm /usr/local/bin/python3*
> brew uninstall python3
> brew install python3
> which python3
> python3 -m pip install --upgrade pip
> python3 -m pip install jupyter
> which jupyter
> jupyter notebook
> ```
> 
> Resolved my issue by installing python3 with brew instead of downloading python from pkg file.

Hi 

> ```shell
> sudo rm -rf /Library/Frameworks/Python.framework
> rm /usr/local/bin/python3*
> brew uninstall python3
> brew install python3
> which python3
> python3 -m pip install --upgrade pip
> python3 -m pip install jupyter
> which jupyter
> jupyter notebook
> ```
> 
> Resolved my issue by installing python3 with brew instead of downloading python from pkg file.

When I run my third command, I get the following error:

```
SARTHAKs-MacBook-Air:~ sarthaksahni$ sudo rm -rf /Library/Frameworks/Python.framework
Password:
SARTHAKs-MacBook-Air:~ sarthaksahni$ rm /usr/local/bin/python3*
rm: /usr/local/bin/python3: Permission denied
rm: /usr/local/bin/python3-32: Permission denied
rm: /usr/local/bin/python3-config: Permission denied
rm: /usr/local/bin/python3.6: Permission denied
rm: /usr/local/bin/python3.6-32: Permission denied
rm: /usr/local/bin/python3.6-config: Permission denied
rm: /usr/local/bin/python3.6m: Permission denied
rm: /usr/local/bin/python3.6m-config: Permission denied
rm: /usr/local/bin/python3.7: Permission denied
rm: /usr/local/bin/python3.7-config: Permission denied
rm: /usr/local/bin/python3.7m: Permission denied
rm: /usr/local/bin/python3.7m-config: Permission denied
SARTHAKs-MacBook-Air:~ sarthaksahni$ brew uninstall python3
-bash: brew: command not found
```
Can you please help me with this?

**Comment by micromouseonline** [comment]
Install homebrew:

https://brew.sh/

**Comment by sarthaksahni1989** [comment]
> Install homebrew:
> 
> https://brew.sh/

Thanks for getting back.
I did that and then ran all the commands but after the below command, it doesn't get me any result:

`which jupyter`

I might have jupyter previously installed. Do you think that might have caused it?

**Comment by micromouseonline** [comment]
I recently changed my Python install to the pkg versions rather than homebrew so I am afraid I can't really help much now.

Does 

     brew list 

show the jupyter and/or ipython install?

How about when you do a directory listing of /usr/local/bin?

**Comment by sarthaksahni1989** [comment]
@micromouseonline - I couldn't see jupyter/ipython in the 'brew list'.

Don't know what to do now!

**Comment by micromouseonline** [comment]
And what do you see when when you run 

    ls -al /usr/local/bin/python*

**Comment by sarthaksahni1989** [comment]
I installed Anaconda on my machine and it fixed it for me.

Thanks for your help!
