### ISSUE TITLE
Clarification on Notebook Path

### ISSUE THREAD

**Issue by AlecAivazis** [jupyter/help#9]
Hey all,

I'm working on a custom notebook storage solution driven by a RESTful api. In order to provide the required information, the [docs](http://jupyter-notebook.readthedocs.org/en/latest/extending/contents.html) say that both notebooks and directories need the "Full (API-style) path to the entity". Does this mean that the file's path includes the parent directory aswell? Ie, if there is a notebook called `insight.ipynb` and I want it to be "inside" of the directory `/foo`, is the notebook's path `/foo/insight.ipynb` and the directory path simply `/foo`? This seems like it has a bit of repeated data since there is already a relationship between directories and files/notebooks (I should be able to figure out the filepath by looking at what directories i've gone through) but maybe I'm missing something

**Comment by Carreau** [comment]
Hi @AlecAivazis 

From what I read of the docs, yes, you are right. The example in the docs give this example without the leading slash though.

I don't remember exactly the reason for that, I would **guess** that this is for historical reasons and backward compatibility, and that "path" might be enough: Indeed the docs says "Models **may** contain the following entries:" (emphasis mine) 

We'll try to look deeper into that to know exactly what's mandatory and what's not and make that clearer in the docs. If you figure it out on your own before we come to that, feel free to tell us how to fix the docs, or submit a PR. 

Looking forward to see your content manager if you are planning to make it public.

**Comment by Carreau** [comment]
@willingc creating a documentation label and marking as documentation. Feel free to change the color if yellow does not suits you.

**Comment by bollwyvl** [comment]
> This seems like it has a bit of repeated data since there is already a relationship between directories and files/notebooks  (I should be able to figure out the filepath by looking at what directories i've gone through) but maybe I'm missing something

I am also not aware of the precise historical reasoning, but I could see it from a few points of view: we have mostly thought of the Contents Manager path as a tree... but other toplogies are possible. So perhaps `path` is a bit of a misnomer, and more something like `id` or `uri` would be more appropriate. 

Ignoring that for a moment, for a number of cases, we can't always assume getting a "full" tree back, i.e. search results, websocket messages, whatever. It would be useful indeed to know where in the tree it went, without needing a new data structure. The fact that we can treat the "path is a slash-delimited encoding of a tree" as a cheap index is helpful, but by no means necessary!

Also, considering that when we want to _write back_ to an element, already having the full ID information, as provided by the server, means we don't get bitten by slash matching, etc.

**Comment by minrk** [comment]
It's mainly for completeness, and to avoid needing to build paths over and over again, which is often done incorrectly (stripping/adding `/`, missing `path.join`, etc.). Having a full path every time makes it easier and clearer for clients to build URLs correctly. So when you make a file, you always make it with full `/path/to/file.ext`.

**Comment by AlecAivazis** [comment]
Alright that makes sense to me - having the full path at all times really simplifies some of the logic for the backend that powers the content manager. Thanks for all of the info!
