### ISSUE TITLE
head() function not working

### ISSUE THREAD

**Issue by Surender09** [jupyter/help#91]
```python
import pandas as pd
import numpy as np

loop=1
while loop==1:
    print('CBIT Timetables')
    print('1.IT2')
    print('2.Exit')
    print()
    choice=input('Enter ur choice')
    choice=int(choice)
    if choice==1:
        df=input('TT is')
        df=pd.read_excel('Book1.xlsx')
        df.head()
    elif choice==2:
        loop=0 
```

This is my code.But Iam not able to get the output,I dont know why the head( )function is not working in this case.Can you please let me know where the problem is

**Comment by takluyver** [comment]
`df.head()` makes a new dataframe with the first few rows of df. It doesn't do anything to display it. If something is the last line of a cell in IPython, it is displayed automatically, but in your code it's not the last line.

To explicitly display it, you can run:

```
from IPython.display import display
display(df.head())
```

**Comment by Carreau** [comment]
Thanks takluyver for the answer. Closing.

**Comment by ChintuKarthi** [comment]
thanks @takluyver  
This one: 
from IPython.display import display
display(df.head())

works fine :)
