### ISSUE TITLE
Rendering long R dataframes generate NAs if there are characters

### ISSUE THREAD

**Issue by thmosqueiro** [jupyter/help#94]
Hello all
I have been using Jupyter notebooks to handle the data analysis of my projects, and one of them is in R with data frames. I've started seeing warnings and errors (especially when using as.Date) that definitely were not supposed to be there. As far as I can understand, it seems that the root for those errors are in the rendering of the data frame: when the rows are summarized (with ...), if there are strings among the cells that were left out, then an NA will be generated. Because I don't exactly know where to post this issue, I used this (supposedly safe and friendly) space. Hopefully this wasn't reported before -- I could not find anything quite similar.

To reproduce the error, consider the [zipped CSV file](https://github.com/jupyter/help/files/560280/ReproducingError.csv.zip). In a notebook, you can simply run the following commands:

```
library(data.table)
filename <- 'ReproducingError.csv';
df <- data.frame( read.csv( filename) );
```

Then, if you try to visualize this notebook, with the command

```
df
```

then a warning is thrown: "Warning message: In `[<-.factor`(`*tmp*`, ri, value = "⋮"): invalid factor level, NA generated". I captured these messages in the following PNG:

<img width="1106" alt="screen shot 2016-10-29 at 9 37 12 pm" src="https://cloud.githubusercontent.com/assets/5439895/19834525/0b298fb8-9e20-11e6-8d16-6ca883386af7.png">

Then you can see the NAs that I mentioned below (see line 31!):

<img width="512" alt="screen shot 2016-10-29 at 9 37 23 pm" src="https://cloud.githubusercontent.com/assets/5439895/19834526/256591e2-9e20-11e6-927b-54bbd2d8e477.png">

If you remove the first column from the CSV file, which is the only one with characters, the error disappears and you can only see "...". So, according to the error message, during the rendering these "..." are probably converted NAs. I'm not sure about why only with strings thou. This of course does not happen with Python Pandas data frames.

If this is indeed a bug, I could volunteer to fix it, if someone could give me a few pointers. I have experience in programming, just not with the underlying structure of Jupyter.

Best,
Thiago

**Comment by minrk** [comment]
This is a fine place to start! My guess is that it's an issue in the R kernel's display machinery. Ideas, @takluyver?

**Comment by thmosqueiro** [comment]
Totally agreed, @minrk. Good to know that this is the right place to post it. I'm asking for other people to try and reproduce it...

**Comment by takluyver** [comment]
Are all the relevant R packages (IRkernel, IRdisplay, repr) up to date? This sounds like a bug that we'd already fixed.

Ping @flying-sheep

**Comment by thmosqueiro** [comment]
Oh my, @takluyver it right. I'm not that used to R, so all of my python libraries were up to date. However, the IRkernel was not. To update it, all I did was:
```
ibrary(devtools)
install_github(‘IRkernel/repr’)
install_github(‘IRkernel/IRdisplay’)
install_github(‘IRkernel/IRkernel’)
IRkernel::installspec()
```
Now this error message does not appear anymore. Thanks for the hint, I'll be closing this issue myself.

**Comment by takluyver** [comment]
OK, thanks for following up :-)
